//! The code generator, exercised the way a user's crate exercises it.
//!
//! `tests/proto/kv.proto` is compiled by `build.rs` with `Stubs::Kernel` and
//! included here. An integration test is a separate crate, so the generated
//! `::pbrs_grpc::...` paths have to resolve through an ordinary dependency
//! rather than through the `extern crate self as pbrs_grpc` alias the library
//! uses internally. If that ever broke, users would find out and this crate
//! would not; now this file does.
//!
//! All four RPC shapes are driven end to end over loopback.

#![allow(
    clippy::disallowed_methods,
    clippy::let_underscore_must_use,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::too_many_lines,
    clippy::unimplemented,
    unreachable_pub,
    reason = "integration tests"
)]

use pbrs_grpc::{
    ChannelConfig, ClientTls, Code, Identity, Outgoing, Request, Response, ServerTls, Status,
    Streaming,
};
use std::net::SocketAddr;
use std::sync::Arc;
use std::time::Duration;
use tokio::net::TcpListener;

const CA: &str = include_str!("tls_data/ca.crt");
const SERVER_CERT: &str = include_str!("tls_data/server.crt");
const SERVER_KEY: &str = include_str!("tls_data/server.key");

/// Exactly what a user writes: include the generated file and use the names.
mod kv {
    #![allow(missing_docs, unused, reason = "generated by protoc-gen-pbrs")]
    include!(concat!(env!("OUT_DIR"), "/kv.rs"));
}

use kv::{
    Entry, Event, GetRequest, GetResponse, Kind, PutSummary, Store, StoreClient, StoreServer,
    WatchRequest,
};

fn entry(key: &str, value: &[u8]) -> Entry {
    let mut e = Entry::new();
    e.set_key(key);
    e.set_value(value.to_vec());
    e
}

fn event(kind: Kind, key: &str) -> Event {
    let mut ev = Event::new();
    ev.set_kind(kind);
    ev.set_entry(entry(key, b""));
    ev
}

fn key_of(e: &Entry) -> String {
    e.key().to_str().unwrap_or_default().to_owned()
}

/// A memory store that answers all four shapes.
struct MemStore;

impl Store for MemStore {
    async fn get(&self, request: Request<GetRequest>) -> Result<Response<GetResponse>, Status> {
        let key = request
            .get_ref()
            .key()
            .to_str()
            .unwrap_or_default()
            .to_owned();
        if key.is_empty() {
            return Err(Status::invalid_argument("empty key"));
        }
        let mut resp = GetResponse::new();
        resp.set_found(true);
        resp.set_entry(entry(&key, b"value"));
        Ok(Response::new(resp))
    }

    async fn put_all(
        &self,
        request: Request<Streaming<Entry>>,
    ) -> Result<Response<PutSummary>, Status> {
        let mut stream = request.into_inner();
        let mut summary = PutSummary::new();
        let mut entries = 0i64;
        let mut bytes = 0i64;
        while let Some(e) = stream.message().await? {
            entries += 1;
            bytes += e.value().len() as i64;
            summary.keys_mut().push(pbrs::ProtoString::from(key_of(&e)));
        }
        summary.set_entries(entries);
        summary.set_bytes(bytes);
        Ok(Response::new(summary))
    }

    async fn watch(
        &self,
        request: Request<WatchRequest>,
    ) -> Result<Response<Streaming<Event>>, Status> {
        let prefixes: Vec<String> = request
            .get_ref()
            .prefixes()
            .iter()
            .map(|p| p.to_str().unwrap_or_default().to_owned())
            .collect();
        let (tx, stream) = Streaming::channel(8);
        drop(tokio::spawn(async move {
            for prefix in prefixes {
                if tx.send(event(Kind::Put, &prefix)).await.is_err() {
                    return;
                }
            }
        }));
        Ok(Response::new(stream))
    }

    async fn sync(
        &self,
        request: Request<Streaming<Entry>>,
    ) -> Result<Response<Streaming<Event>>, Status> {
        let mut inbound = request.into_inner();
        let (tx, stream) = Streaming::channel(8);
        drop(tokio::spawn(async move {
            loop {
                match inbound.message().await {
                    Ok(Some(e)) => {
                        if tx.send(event(Kind::Delete, &key_of(&e))).await.is_err() {
                            return;
                        }
                    }
                    Ok(None) => break,
                    Err(status) => {
                        tx.fail(status).await;
                        break;
                    }
                }
            }
        }));
        Ok(Response::new(stream))
    }
}

struct TypedFailStore;

impl Store for TypedFailStore {
    async fn get(&self, _: Request<GetRequest>) -> Result<Response<GetResponse>, Status> {
        Err(interceptor_blocked())
    }

    async fn put_all(&self, _: Request<Streaming<Entry>>) -> Result<Response<PutSummary>, Status> {
        Err(interceptor_blocked())
    }

    async fn watch(&self, _: Request<WatchRequest>) -> Result<Response<Streaming<Event>>, Status> {
        Err(interceptor_blocked())
    }

    async fn sync(
        &self,
        _: Request<Streaming<Entry>>,
    ) -> Result<Response<Streaming<Event>>, Status> {
        Err(interceptor_blocked())
    }
}

async fn serve() -> (SocketAddr, tokio::task::JoinHandle<()>) {
    let listener = TcpListener::bind(SocketAddr::from(([127, 0, 0, 1], 0)))
        .await
        .expect("bind");
    let addr = listener.local_addr().expect("addr");
    let handle = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .serve_listener(listener)
            .await
            .ok();
    });
    (addr, handle)
}

async fn client(addr: SocketAddr) -> StoreClient {
    for _ in 0..80 {
        if let Ok(client) = StoreClient::connect(addr).await {
            return client;
        }
        tokio::time::sleep(Duration::from_millis(5)).await;
    }
    panic!("could not connect to {addr}");
}

async fn tls_client(addr: SocketAddr) -> StoreClient {
    let client_tls = ClientTls::ca("localhost", CA).expect("client tls");
    let mut last = None;
    for _ in 0..80 {
        match StoreClient::connect_tls_with(
            addr,
            ChannelConfig::default().timeout(Duration::from_secs(5)),
            client_tls.clone(),
        )
        .await
        {
            Ok(client) => return client,
            Err(e) => {
                last = Some(e);
                tokio::time::sleep(Duration::from_millis(5)).await;
            }
        }
    }
    panic!("could not connect: {last:?}")
}

#[cfg(unix)]
async fn unix_client(path: &std::path::Path) -> StoreClient {
    let mut last = None;
    for _ in 0..80 {
        match StoreClient::connect_unix(path).await {
            Ok(client) => return client,
            Err(e) => {
                last = Some(e);
                tokio::time::sleep(Duration::from_millis(5)).await;
            }
        }
    }
    panic!("could not connect: {last:?}")
}

#[cfg(unix)]
fn unix_sock(prefix: &str) -> std::path::PathBuf {
    static N: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);
    let mut path = std::env::temp_dir();
    path.push(format!(
        "pbrs-grpc-kv-{prefix}-{}-{}.sock",
        std::process::id(),
        N.fetch_add(1, std::sync::atomic::Ordering::Relaxed)
    ));
    let _ = std::fs::remove_file(&path);
    path
}

async fn echo_store_every_shape(client: &StoreClient) {
    let mut get = GetRequest::new();
    get.set_key("alpha");
    let got = client.get(Request::new(get)).await.expect("unary");
    assert!(got.get_ref().found());
    assert_eq!(key_of(got.get_ref().entry()), "alpha");

    let (tx, call) = client.put_all(Request::new(()));
    for (key, value) in [("a", &b"11"[..]), ("b", &b"222"[..])] {
        tx.send(entry(key, value)).await.expect("send");
    }
    tx.close();
    let summary = call.await.expect("client-stream");
    assert_eq!(summary.get_ref().entries(), 2);
    assert_eq!(summary.get_ref().bytes(), 5);
    let keys: Vec<String> = summary
        .get_ref()
        .keys()
        .iter()
        .map(|k| k.to_str().unwrap_or_default().to_owned())
        .collect();
    assert_eq!(keys, ["a", "b"]);

    let mut watch = WatchRequest::new();
    for prefix in ["x", "y", "z"] {
        watch.prefixes_mut().push(pbrs::ProtoString::from(prefix));
    }
    let mut events = client
        .watch(Request::new(watch))
        .await
        .expect("server-stream")
        .into_inner();
    let mut seen = Vec::new();
    while let Some(ev) = events.message().await.expect("event") {
        assert_eq!(ev.kind(), Kind::Put);
        seen.push(key_of(ev.entry()));
    }
    assert_eq!(seen, ["x", "y", "z"]);

    let (tx, call) = client.sync(Request::new(()));
    let mut inbound = call.await.expect("bidi").into_inner();
    for key in ["p", "q"] {
        tx.send(entry(key, b"v")).await.expect("send");
        let ev = inbound.message().await.expect("event").expect("some");
        assert_eq!(ev.kind(), Kind::Delete);
        assert_eq!(key_of(ev.entry()), key);
    }
    tx.close();
    while inbound.message().await.expect("drain").is_some() {}
}

async fn gzip_store_every_shape(client: &StoreClient) {
    let mut get = GetRequest::new();
    get.set_key("alpha");
    let got = client.get(Request::new(get)).await.expect("unary");
    assert!(got.compressed(), "unary gzip");
    assert_eq!(got.encoding(), Some("gzip"), "{:?}", got.encoding());
    assert!(got.get_ref().found());
    assert_eq!(key_of(got.get_ref().entry()), "alpha");

    let (tx, call) = client.put_all(Request::new(()));
    assert!(tx.compress(), "put_all StreamSender must gzip");
    for (key, value) in [("a", &b"11"[..]), ("b", &b"222"[..])] {
        tx.send(entry(key, value)).await.expect("send");
    }
    tx.close();
    let summary = call.await.expect("client-stream");
    assert!(summary.compressed(), "put_all reply gzip");
    assert_eq!(summary.encoding(), Some("gzip"));
    assert_eq!(summary.get_ref().entries(), 2);
    assert_eq!(summary.get_ref().bytes(), 5);

    let mut watch = WatchRequest::new();
    for prefix in ["x", "y", "z"] {
        watch.prefixes_mut().push(pbrs::ProtoString::from(prefix));
    }
    let reply = client
        .watch(Request::new(watch))
        .await
        .expect("server-stream");
    assert_eq!(reply.encoding(), Some("gzip"), "watch encoding");
    let mut events = reply.into_inner();
    let framed = events.next_framed().await.expect("frame").expect("message");
    assert!(framed.compressed, "watch frames gzip");
    assert_eq!(framed.message.kind(), Kind::Put);
    let mut seen = vec![key_of(framed.message.entry())];
    while let Some(ev) = events.message().await.expect("event") {
        assert_eq!(ev.kind(), Kind::Put);
        seen.push(key_of(ev.entry()));
    }
    assert_eq!(seen, ["x", "y", "z"]);

    let (tx, call) = client.sync(Request::new(()));
    assert!(tx.compress(), "sync StreamSender must gzip");
    let reply = call.await.expect("bidi");
    assert_eq!(reply.encoding(), Some("gzip"), "sync encoding");
    let mut inbound = reply.into_inner();
    for key in ["p", "q"] {
        tx.send(entry(key, b"v")).await.expect("send");
        let framed = inbound.next_framed().await.expect("frame").expect("some");
        assert!(framed.compressed, "sync frames gzip");
        assert_eq!(framed.message.kind(), Kind::Delete);
        assert_eq!(key_of(framed.message.entry()), key);
    }
    tx.close();
    while inbound.message().await.expect("drain").is_some() {}
}

async fn assert_store_err_every_shape(client: &StoreClient, want: Code) {
    let mut get = GetRequest::new();
    get.set_key("intercepted");
    let err = client.get(Request::new(get)).await.expect_err("unary");
    assert_eq!(err.code(), want, "{err}");

    let mut watch = WatchRequest::new();
    watch.prefixes_mut().push(pbrs::ProtoString::from("x"));
    let err = client
        .watch(Request::new(watch))
        .await
        .expect_err("server-stream");
    assert_eq!(err.code(), want, "{err}");

    let (tx, call) = client.put_all(Request::new(()));
    let err = call.await.expect_err("client-stream");
    assert_eq!(err.code(), want, "{err}");
    drop(tx);

    let (tx, call) = client.sync(Request::new(()));
    let err = call.await.expect_err("bidi");
    assert_eq!(err.code(), want, "{err}");
    drop(tx);
}

fn fat_store_key() -> String {
    "k".repeat(64)
}

async fn assert_store_oversize_every_shape(client: &StoreClient) {
    let mut get = GetRequest::new();
    get.set_key(fat_store_key());
    let err = client.get(Request::new(get)).await.expect_err("unary");
    assert_eq!(err.code(), Code::ResourceExhausted, "{err}");

    let mut watch = WatchRequest::new();
    watch
        .prefixes_mut()
        .push(pbrs::ProtoString::from(fat_store_key()));
    match client.watch(Request::new(watch)).await {
        Err(err) => assert_eq!(err.code(), Code::ResourceExhausted, "{err}"),
        Ok(resp) => match resp.into_inner().message().await {
            Err(err) => assert_eq!(err.code(), Code::ResourceExhausted, "{err}"),
            Ok(_) => panic!("server-stream over the server cap must fail"),
        },
    }

    let (tx, call) = client.put_all(Request::new(()));
    tx.send(entry(&fat_store_key(), b"v")).await.expect("send");
    tx.close();
    let err = call.await.expect_err("client-stream over the server cap");
    assert_eq!(err.code(), Code::ResourceExhausted, "{err}");

    let (tx, call) = client.sync(Request::new(()));
    tx.send(entry(&fat_store_key(), b"v")).await.expect("send");
    tx.close();
    match call.await {
        Err(err) => assert_eq!(err.code(), Code::ResourceExhausted, "{err}"),
        Ok(resp) => match resp.into_inner().message().await {
            Err(err) => assert_eq!(err.code(), Code::ResourceExhausted, "{err}"),
            Ok(_) => panic!("bidi over the server cap must fail"),
        },
    }
}

fn stamp_outgoing_context(call: &mut Outgoing<'_>) -> Result<(), Status> {
    let path = call.path();
    call.metadata_mut().insert("x-path", path)?;
    let service = call.service();
    call.metadata_mut().set("x-service", service)?;
    let method = call.method();
    call.metadata_mut().set("x-method", method)?;
    let authority = call.authority();
    call.metadata_mut().insert("x-authority", authority)?;
    let scheme = call.scheme();
    call.metadata_mut().set("x-scheme", scheme)?;
    Ok(())
}

fn require_stamped_context(rpc: &mut pbrs_grpc::Rpc) -> Result<(), Status> {
    if rpc.metadata().get("x-path") != Some(rpc.path()) {
        return Err(Status::invalid_argument(format!(
            "x-path {:?} path {}",
            rpc.metadata().get("x-path"),
            rpc.path()
        )));
    }
    if rpc.metadata().get("x-service") != Some(rpc.service()) {
        return Err(Status::invalid_argument(format!(
            "x-service {:?} service {}",
            rpc.metadata().get("x-service"),
            rpc.service()
        )));
    }
    if rpc.metadata().get("x-method") != Some(rpc.method()) {
        return Err(Status::invalid_argument(format!(
            "x-method {:?} method {}",
            rpc.metadata().get("x-method"),
            rpc.method()
        )));
    }
    if rpc.metadata().get("x-authority") != rpc.authority() {
        return Err(Status::invalid_argument(format!(
            "x-authority {:?} authority {:?}",
            rpc.metadata().get("x-authority"),
            rpc.authority()
        )));
    }
    if rpc.metadata().get("x-scheme") != rpc.scheme() {
        return Err(Status::invalid_argument(format!(
            "x-scheme {:?} scheme {:?}",
            rpc.metadata().get("x-scheme"),
            rpc.scheme()
        )));
    }
    Ok(())
}

fn interceptor_blocked() -> Status {
    let mut info = pbrs_grpc::pb::ErrorInfo::new();
    info.set_reason("BLOCKED");
    info.set_domain("example.com");
    Status::with_error_details(
        Code::FailedPrecondition,
        "blocked locally",
        [pbrs_grpc::pb::Any::pack(&info).expect("pack")],
    )
    .expect("details")
}

fn assert_store_blocked(err: &Status) {
    assert_eq!(err.code(), Code::FailedPrecondition, "{err}");
    assert_eq!(err.message(), "blocked locally");
    let info = err
        .rpc()
        .expect("google.rpc.Status")
        .details()
        .get(0)
        .expect("one Any")
        .unpack::<pbrs_grpc::pb::ErrorInfo>()
        .expect("ErrorInfo");
    assert_eq!(info.reason().to_str().unwrap_or(""), "BLOCKED");
    assert_eq!(info.domain().to_str().unwrap_or(""), "example.com");
    let unpacked = err
        .error_details()
        .expect("ErrorDetails")
        .error_info
        .expect("ErrorInfo");
    assert_eq!(unpacked.reason().to_str().unwrap_or(""), "BLOCKED");
    assert_eq!(unpacked.domain().to_str().unwrap_or(""), "example.com");
}

async fn assert_store_blocked_every_shape(client: &StoreClient) {
    let mut get = GetRequest::new();
    get.set_key("intercepted");
    assert_store_blocked(&client.get(Request::new(get)).await.expect_err("unary"));

    let mut watch = WatchRequest::new();
    watch.prefixes_mut().push(pbrs::ProtoString::from("x"));
    match client.watch(Request::new(watch)).await {
        Err(err) => assert_store_blocked(&err),
        Ok(resp) => match resp.into_inner().message().await {
            Err(err) => assert_store_blocked(&err),
            Ok(_) => panic!("server-stream interceptor reject must fail"),
        },
    }

    let (tx, call) = client.put_all(Request::new(()));
    assert_store_blocked(&call.await.expect_err("client-stream"));
    drop(tx);

    let (tx, call) = client.sync(Request::new(()));
    assert_store_blocked(&call.await.expect_err("bidi"));
    drop(tx);
}

#[tokio::test]
async fn generated_stubs_serve_all_four_shapes() {
    let (addr, server) = serve().await;
    echo_store_every_shape(&client(addr).await).await;
    server.abort();
}

#[tokio::test]
async fn generated_stubs_carry_handler_errors() {
    let (addr, server) = serve().await;
    let client = client(addr).await;
    let err = client
        .get(Request::new(GetRequest::new()))
        .await
        .expect_err("empty key");
    assert_eq!(err.code(), Code::InvalidArgument);
    assert_eq!(err.message(), "empty key");
    server.abort();
}

#[tokio::test]
async fn generated_handlers_return_typed_status_on_every_shape() {
    let listener = TcpListener::bind(SocketAddr::from(([127, 0, 0, 1], 0)))
        .await
        .expect("bind");
    let addr = listener.local_addr().expect("addr");
    let server = tokio::spawn(async move {
        StoreServer::new(TypedFailStore)
            .serve_listener(listener)
            .await
            .ok();
    });
    assert_store_blocked_every_shape(&client(addr).await).await;
    server.abort();
}

#[cfg(unix)]
#[tokio::test]
async fn generated_serve_unix_round_trips() {
    static N: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);
    let mut path = std::env::temp_dir();
    path.push(format!(
        "pbrs-grpc-kv-{}-{}.sock",
        std::process::id(),
        N.fetch_add(1, std::sync::atomic::Ordering::Relaxed)
    ));
    let _ = std::fs::remove_file(&path);
    let sock = path.clone();
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore).serve_unix(sock).await.ok();
    });
    let mut last = None;
    let client = {
        let mut found = None;
        for _ in 0..80 {
            match StoreClient::connect_unix(&path).await {
                Ok(client) => {
                    found = Some(client);
                    break;
                }
                Err(e) => {
                    last = Some(e);
                    tokio::time::sleep(Duration::from_millis(5)).await;
                }
            }
        }
        found.unwrap_or_else(|| panic!("could not connect: {last:?}"))
    };
    echo_store_every_shape(&client).await;
    server.abort();
    let _ = std::fs::remove_file(&path);
}

#[cfg(unix)]
#[tokio::test]
async fn generated_unix_send_compressed_gzips_every_shape() {
    let path = unix_sock("gzip");
    let sock = path.clone();
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .send_compressed()
            .serve_unix(sock)
            .await
            .ok();
    });
    gzip_store_every_shape(&unix_client(&path).await.send_compressed()).await;
    server.abort();
    let _ = std::fs::remove_file(&path);
}

#[cfg(unix)]
#[tokio::test]
async fn generated_unix_server_interceptor_rejects_with_typed_status() {
    let path = unix_sock("reject");
    let sock = path.clone();
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .intercept(|_rpc: &mut pbrs_grpc::Rpc| Err(interceptor_blocked()))
            .serve_unix(sock)
            .await
            .ok();
    });
    assert_store_blocked_every_shape(&unix_client(&path).await).await;
    server.abort();
    let _ = std::fs::remove_file(&path);
}

#[cfg(unix)]
#[tokio::test]
async fn generated_unix_client_interceptor_rejects_with_typed_status() {
    let path = unix_sock("client-reject");
    let sock = path.clone();
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore).serve_unix(sock).await.ok();
    });
    let client = unix_client(&path)
        .await
        .intercept(|_: &mut Outgoing<'_>| Err(interceptor_blocked()));
    assert_store_blocked_every_shape(&client).await;
    server.abort();
    let _ = std::fs::remove_file(&path);
}

#[cfg(unix)]
#[tokio::test]
async fn generated_unix_client_interceptor_sees_every_shape_context() {
    let path = unix_sock("context");
    let sock = path.clone();
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .intercept(require_stamped_context)
            .serve_unix(sock)
            .await
            .ok();
    });
    let client = unix_client(&path).await.intercept(stamp_outgoing_context);
    echo_store_every_shape(&client).await;
    server.abort();
    let _ = std::fs::remove_file(&path);
}

#[cfg(unix)]
#[tokio::test]
async fn generated_serve_unix_unlink_replaces_a_leftover() {
    static UNIQ: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);
    let mut path = std::env::temp_dir();
    path.push(format!(
        "pbrs-grpc-kv-unlink-{}-{}.sock",
        std::process::id(),
        UNIQ.fetch_add(1, std::sync::atomic::Ordering::Relaxed)
    ));
    let _ = std::fs::remove_file(&path);
    let leftover = tokio::net::UnixListener::bind(&path).expect("stale");
    drop(leftover);
    let sock = path.clone();
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .serve_unix_unlink(sock)
            .await
            .ok();
    });
    let mut last = None;
    let client = {
        let mut found = None;
        for _ in 0..80 {
            match StoreClient::connect_unix(&path).await {
                Ok(client) => {
                    found = Some(client);
                    break;
                }
                Err(e) => {
                    last = Some(e);
                    tokio::time::sleep(Duration::from_millis(5)).await;
                }
            }
        }
        found.unwrap_or_else(|| panic!("could not connect: {last:?}"))
    };
    echo_store_every_shape(&client).await;
    server.abort();
    let _ = std::fs::remove_file(&path);
}

#[tokio::test]
async fn generated_names_match_the_proto() {
    assert_eq!(StoreServer::<MemStore>::NAME, "kv.Store");
    assert_eq!(StoreClient::NAME, "kv.Store");
    assert_eq!(
        <StoreServer<MemStore> as pbrs_grpc::Service>::NAME,
        "kv.Store"
    );
}

#[tokio::test]
async fn generated_servers_accept_configuration() {
    let listener = TcpListener::bind(SocketAddr::from(([127, 0, 0, 1], 0)))
        .await
        .expect("bind");
    let addr = listener.local_addr().expect("addr");
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .send_compressed()
            .message_limits(pbrs_grpc::MessageLimits::new().with_max_decoding(16))
            .max_concurrent_rpcs(32)
            .max_concurrent_connections(8)
            .timeout(Duration::from_secs(5))
            .keep_alive_interval(Duration::from_secs(30))
            .keep_alive_timeout(Duration::from_secs(10))
            .tcp_keepalive(Duration::from_secs(30))
            .max_connection_age(Duration::from_secs(1800))
            .max_connection_idle(Duration::from_secs(300))
            .max_connection_age_grace(Duration::from_secs(30))
            .handshake_timeout(Duration::from_secs(5))
            .max_concurrent_streams(128)
            .initial_stream_window_size(1024 * 1024)
            .initial_connection_window_size(2 * 1024 * 1024)
            .max_frame_size(32 * 1024)
            .max_header_list_size(8 * 1024)
            .max_send_buffer_size(512 * 1024)
            .max_pending_accept_reset_streams(3)
            .serve_listener(listener)
            .await
            .ok();
    });

    let client = client(addr).await;
    assert_store_oversize_every_shape(&client).await;
    server.abort();
}

#[tokio::test]
async fn generated_servers_mount_on_a_router() {
    let listener = TcpListener::bind(SocketAddr::from(([127, 0, 0, 1], 0)))
        .await
        .expect("bind");
    let addr = listener.local_addr().expect("addr");
    let server = tokio::spawn(async move {
        pbrs_grpc::Router::new()
            .message_limits(pbrs_grpc::MessageLimits::default())
            .send_compressed()
            .max_decoding_message_size(4 * 1024 * 1024)
            .add_service(StoreServer::new(MemStore))
            .add_service(pbrs_grpc::GreeterServer::new(EchoGreeter))
            .serve_listener(listener)
            .await
            .ok();
    });

    let store = client(addr).await;
    echo_store_every_shape(&store).await;

    let greeter = pbrs_grpc::GreeterClient::connect(addr)
        .await
        .expect("connect");
    let mut hello = pbrs_grpc::HelloRequest::new();
    hello.set_name("ada");
    let reply = greeter
        .say_hello(Request::new(hello))
        .await
        .expect("greeter");
    assert_eq!(
        reply.get_ref().message().to_str().unwrap_or_default(),
        "ada"
    );

    server.abort();
}

#[tokio::test]
async fn generated_servers_and_clients_expose_intercept() {
    let listener = TcpListener::bind(SocketAddr::from(([127, 0, 0, 1], 0)))
        .await
        .expect("bind");
    let addr = listener.local_addr().expect("addr");
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .intercept(|rpc: &mut pbrs_grpc::Rpc| {
                if rpc.metadata().get("x-token") != Some("ok") {
                    return Err(Status::unauthenticated("nope"));
                }
                Ok(())
            })
            .serve_listener(listener)
            .await
            .ok();
    });

    let denied = client(addr).await;
    assert_store_err_every_shape(&denied, Code::Unauthenticated).await;

    let allowed = client(addr)
        .await
        .intercept(|call: &mut pbrs_grpc::Outgoing<'_>| {
            call.metadata_mut().insert("x-token", "ok")?;
            Ok(())
        });
    echo_store_every_shape(&allowed).await;

    server.abort();
}

#[tokio::test]
async fn generated_client_interceptor_sees_every_shape_context() {
    let listener = TcpListener::bind(SocketAddr::from(([127, 0, 0, 1], 0)))
        .await
        .expect("bind");
    let addr = listener.local_addr().expect("addr");
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .intercept(require_stamped_context)
            .serve_listener(listener)
            .await
            .ok();
    });
    let client = client(addr).await.intercept(stamp_outgoing_context);
    echo_store_every_shape(&client).await;
    server.abort();
}

#[tokio::test]
async fn generated_client_interceptor_rejects_with_typed_status() {
    let (addr, server) = serve().await;
    let client = client(addr)
        .await
        .intercept(|_: &mut Outgoing<'_>| Err(interceptor_blocked()));
    assert_store_blocked_every_shape(&client).await;
    server.abort();
}

#[tokio::test]
async fn generated_server_interceptor_rejects_with_typed_status() {
    let listener = TcpListener::bind(SocketAddr::from(([127, 0, 0, 1], 0)))
        .await
        .expect("bind");
    let addr = listener.local_addr().expect("addr");
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .intercept(|_rpc: &mut pbrs_grpc::Rpc| Err(interceptor_blocked()))
            .serve_listener(listener)
            .await
            .ok();
    });
    assert_store_blocked_every_shape(&client(addr).await).await;
    server.abort();
}

#[tokio::test]
async fn generated_client_user_agent_is_prefixed() {
    let listener = TcpListener::bind(SocketAddr::from(([127, 0, 0, 1], 0)))
        .await
        .expect("bind");
    let addr = listener.local_addr().expect("addr");
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .intercept(|rpc: &mut pbrs_grpc::Rpc| {
                let md = rpc.metadata();
                let ua = md.get("user-agent").unwrap_or("");
                if !ua.starts_with("kv-test ") || !ua.contains("pbrs-grpc/") {
                    return Err(Status::invalid_argument(format!("user-agent {ua:?}")));
                }
                Ok(())
            })
            .serve_listener(listener)
            .await
            .ok();
    });

    let client = client(addr)
        .await
        .user_agent("kv-test")
        .expect("user-agent");
    echo_store_every_shape(&client).await;

    server.abort();
}

/// A second service, so the router has something to route between.
struct EchoGreeter;

impl pbrs_grpc::Greeter for EchoGreeter {
    async fn say_hello(
        &self,
        request: Request<pbrs_grpc::HelloRequest>,
    ) -> Result<Response<pbrs_grpc::HelloReply>, Status> {
        let mut reply = pbrs_grpc::HelloReply::new();
        reply.set_message(request.get_ref().name());
        Ok(Response::new(reply))
    }
}

#[tokio::test]
async fn omitted_generated_methods_answer_unimplemented() {
    let listener = TcpListener::bind(SocketAddr::from(([127, 0, 0, 1], 0)))
        .await
        .expect("bind");
    let addr = listener.local_addr().expect("addr");
    let server = tokio::spawn(async move {
        pbrs_grpc::GreeterServer::new(EchoGreeter)
            .serve_listener(listener)
            .await
            .ok();
    });
    let client = pbrs_grpc::GreeterClient::connect_lazy(addr)
        .expect("lazy")
        .wait_for_ready()
        .timeout(Duration::from_secs(2));

    let mut hello = pbrs_grpc::HelloRequest::new();
    hello.set_name("ada");
    let reply = client
        .say_hello(Request::new(hello.clone()))
        .await
        .expect("unary");
    assert_eq!(
        reply.get_ref().message().to_str().unwrap_or_default(),
        "ada"
    );

    let err = client
        .server_hello(Request::new(hello))
        .await
        .expect_err("server");
    assert_eq!(err.code(), Code::Unimplemented);
    assert!(err.message().contains("ServerHello"), "{}", err.message());

    let (tx, call) = client.client_hello(Request::new(()));
    tx.close();
    let err = call.await.expect_err("client");
    assert_eq!(err.code(), Code::Unimplemented);
    assert!(err.message().contains("ClientHello"), "{}", err.message());

    server.abort();
}

#[test]
fn generated_server_shares_an_arc_and_unwraps_it() {
    let inner = Arc::new(MemStore);
    let server = StoreServer::from_arc(Arc::clone(&inner));
    assert!(format!("{server:?}").contains("kv.Store"), "{server:?}");
    assert!(Arc::ptr_eq(&server.into_inner(), &inner));
}

#[test]
fn generated_server_into_router_keeps_the_name() {
    let names: Vec<_> = StoreServer::new(MemStore)
        .into_router()
        .service_names()
        .collect();
    assert_eq!(names, ["kv.Store"]);
}

#[test]
fn generated_client_debug_and_into_inner() {
    let client = StoreClient::connect_lazy_with(
        "127.0.0.1:1",
        ChannelConfig::default()
            .timeout(Duration::from_secs(5))
            .wait_for_ready(true),
    )
    .expect("lazy")
    .wait_for_ready()
    .stream_buffer(64)
    .message_limits(pbrs_grpc::MessageLimits::unlimited());
    assert!(format!("{client:?}").contains("127.0.0.1:1"), "{client:?}");
    assert_eq!(client.channel().config().stream_buffer_size(), 64);
    assert_eq!(client.channel().config().limits().max_decoding(), None);
    assert_eq!(client.config(), client.channel().config());
    assert_eq!(client.rpc_timeout(), Some(Duration::from_secs(5)));
    assert!(client.waits_for_ready());
    assert!(!client.compresses_outbound());
    assert_eq!(client.rpc_timeout(), client.channel().rpc_timeout());
    assert_eq!(client.waits_for_ready(), client.channel().waits_for_ready());
    let _ = client.into_inner();
}

#[test]
fn generated_server_config_is_readable_after_overlays() {
    let server = StoreServer::new(MemStore).timeout(Duration::from_secs(5));
    assert_eq!(
        server.server_config().rpc_timeout(),
        Some(Duration::from_secs(5))
    );
    assert_eq!(server.rpc_timeout(), Some(Duration::from_secs(5)));
    assert!(!server.compresses_outbound());
    assert!(server.clone().send_compressed().compresses_outbound());
    let router = server.clone().into_router();
    assert_eq!(
        router.server_config().rpc_timeout(),
        Some(Duration::from_secs(5))
    );
    assert_eq!(router.rpc_timeout(), Some(Duration::from_secs(5)));
}

#[tokio::test]
async fn generated_client_connect_with_and_pool_round_trip() {
    let (addr, server) = serve().await;
    let with = StoreClient::connect_with(
        addr,
        ChannelConfig::default().timeout(Duration::from_secs(5)),
    )
    .await
    .expect("connect_with");
    echo_store_every_shape(&with).await;
    let pooled = StoreClient::connect_pool(addr, 2).await.expect("pool");
    echo_store_every_shape(&pooled).await;
    server.abort();
}

#[cfg(unix)]
#[test]
fn generated_client_connect_unix_lazy() {
    let client =
        StoreClient::connect_unix_lazy("/tmp/pbrs-grpc-does-not-exist.sock").expect("unix lazy");
    let _ = client.into_inner();
}

#[tokio::test]
async fn generated_serve_connection_round_trips() {
    let (client_io, server_io) = tokio::io::duplex(1024 * 1024);
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .serve_connection(server_io)
            .await
            .ok();
    });
    let client = StoreClient::from_io_with(client_io, "localhost", ChannelConfig::default())
        .await
        .expect("from_io");
    echo_store_every_shape(&client).await;
    server.abort();
}

#[tokio::test]
async fn generated_from_io_send_compressed_gzips_every_shape() {
    let (client_io, server_io) = tokio::io::duplex(1024 * 1024);
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .send_compressed()
            .serve_connection(server_io)
            .await
            .ok();
    });
    let client = StoreClient::from_io_with(client_io, "localhost", ChannelConfig::default())
        .await
        .expect("from_io")
        .send_compressed();
    gzip_store_every_shape(&client).await;
    server.abort();
}

#[tokio::test]
async fn generated_from_io_server_interceptor_rejects_with_typed_status() {
    let (client_io, server_io) = tokio::io::duplex(1024 * 1024);
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .intercept(|_rpc: &mut pbrs_grpc::Rpc| Err(interceptor_blocked()))
            .serve_connection(server_io)
            .await
            .ok();
    });
    let client = StoreClient::from_io_with(client_io, "localhost", ChannelConfig::default())
        .await
        .expect("from_io");
    assert_store_blocked_every_shape(&client).await;
    server.abort();
}

#[tokio::test]
async fn generated_from_io_client_interceptor_rejects_with_typed_status() {
    let (client_io, server_io) = tokio::io::duplex(1024 * 1024);
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .serve_connection(server_io)
            .await
            .ok();
    });
    let client = StoreClient::from_io_with(client_io, "localhost", ChannelConfig::default())
        .await
        .expect("from_io")
        .intercept(|_: &mut Outgoing<'_>| Err(interceptor_blocked()));
    assert_store_blocked_every_shape(&client).await;
    server.abort();
}

#[tokio::test]
async fn generated_from_io_client_interceptor_sees_every_shape_context() {
    let (client_io, server_io) = tokio::io::duplex(1024 * 1024);
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .intercept(require_stamped_context)
            .serve_connection(server_io)
            .await
            .ok();
    });
    let client = StoreClient::from_io_with(client_io, "localhost", ChannelConfig::default())
        .await
        .expect("from_io")
        .intercept(stamp_outgoing_context);
    echo_store_every_shape(&client).await;
    server.abort();
}

#[tokio::test]
async fn generated_serve_tls_round_trips_every_shape() {
    let identity = Identity::from_pem(SERVER_CERT, SERVER_KEY).expect("identity");
    let tls = ServerTls::new(identity).expect("server tls");
    let listener = TcpListener::bind(SocketAddr::from(([127, 0, 0, 1], 0)))
        .await
        .expect("bind");
    let addr = listener.local_addr().expect("addr");
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .serve_tls_with_shutdown(listener, std::future::pending(), tls)
            .await
            .ok();
    });
    let client_tls = ClientTls::ca("localhost", CA).expect("client tls");
    let mut last = None;
    let client = {
        let mut found = None;
        for _ in 0..80 {
            match StoreClient::connect_tls_with(
                addr,
                ChannelConfig::default().timeout(Duration::from_secs(5)),
                client_tls.clone(),
            )
            .await
            {
                Ok(client) => {
                    found = Some(client);
                    break;
                }
                Err(e) => {
                    last = Some(e);
                    tokio::time::sleep(Duration::from_millis(5)).await;
                }
            }
        }
        found.unwrap_or_else(|| panic!("could not connect: {last:?}"))
    };
    echo_store_every_shape(&client).await;
    server.abort();
}

#[tokio::test]
async fn generated_connect_tls_lazy_round_trips_every_shape() {
    let identity = Identity::from_pem(SERVER_CERT, SERVER_KEY).expect("identity");
    let tls = ServerTls::new(identity).expect("server tls");
    let listener = TcpListener::bind(SocketAddr::from(([127, 0, 0, 1], 0)))
        .await
        .expect("bind");
    let addr = listener.local_addr().expect("addr");
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .serve_tls_with_shutdown(listener, std::future::pending(), tls)
            .await
            .ok();
    });
    let client_tls = ClientTls::ca("localhost", CA).expect("client tls");
    let client = StoreClient::connect_tls_lazy_with(
        addr,
        ChannelConfig::default().timeout(Duration::from_secs(5)),
        client_tls,
    )
    .expect("tls lazy")
    .wait_for_ready();
    echo_store_every_shape(&client).await;
    server.abort();
}

#[tokio::test]
async fn generated_send_compressed_gzips_every_shape() {
    let listener = TcpListener::bind(SocketAddr::from(([127, 0, 0, 1], 0)))
        .await
        .expect("bind");
    let addr = listener.local_addr().expect("addr");
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .send_compressed()
            .serve_listener(listener)
            .await
            .ok();
    });
    let client = client(addr).await.send_compressed();
    gzip_store_every_shape(&client).await;
    server.abort();
}

#[tokio::test]
async fn generated_tls_send_compressed_gzips_every_shape() {
    let identity = Identity::from_pem(SERVER_CERT, SERVER_KEY).expect("identity");
    let tls = ServerTls::new(identity).expect("server tls");
    let listener = TcpListener::bind(SocketAddr::from(([127, 0, 0, 1], 0)))
        .await
        .expect("bind");
    let addr = listener.local_addr().expect("addr");
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .send_compressed()
            .serve_tls_with_shutdown(listener, std::future::pending(), tls)
            .await
            .ok();
    });
    let client_tls = ClientTls::ca("localhost", CA).expect("client tls");
    let mut last = None;
    let client = {
        let mut found = None;
        for _ in 0..80 {
            match StoreClient::connect_tls_with(
                addr,
                ChannelConfig::default().timeout(Duration::from_secs(5)),
                client_tls.clone(),
            )
            .await
            {
                Ok(client) => {
                    found = Some(client);
                    break;
                }
                Err(e) => {
                    last = Some(e);
                    tokio::time::sleep(Duration::from_millis(5)).await;
                }
            }
        }
        found.unwrap_or_else(|| panic!("could not connect: {last:?}"))
    }
    .send_compressed();
    gzip_store_every_shape(&client).await;
    server.abort();
}

#[tokio::test]
async fn generated_tls_server_interceptor_rejects_with_typed_status() {
    let identity = Identity::from_pem(SERVER_CERT, SERVER_KEY).expect("identity");
    let tls = ServerTls::new(identity).expect("server tls");
    let listener = TcpListener::bind(SocketAddr::from(([127, 0, 0, 1], 0)))
        .await
        .expect("bind");
    let addr = listener.local_addr().expect("addr");
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .intercept(|_rpc: &mut pbrs_grpc::Rpc| Err(interceptor_blocked()))
            .serve_tls_with_shutdown(listener, std::future::pending(), tls)
            .await
            .ok();
    });
    assert_store_blocked_every_shape(&tls_client(addr).await).await;
    server.abort();
}

#[tokio::test]
async fn generated_tls_client_interceptor_rejects_with_typed_status() {
    let identity = Identity::from_pem(SERVER_CERT, SERVER_KEY).expect("identity");
    let tls = ServerTls::new(identity).expect("server tls");
    let listener = TcpListener::bind(SocketAddr::from(([127, 0, 0, 1], 0)))
        .await
        .expect("bind");
    let addr = listener.local_addr().expect("addr");
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .serve_tls_with_shutdown(listener, std::future::pending(), tls)
            .await
            .ok();
    });
    let client = tls_client(addr)
        .await
        .intercept(|_: &mut Outgoing<'_>| Err(interceptor_blocked()));
    assert_store_blocked_every_shape(&client).await;
    server.abort();
}

#[tokio::test]
async fn generated_tls_client_interceptor_sees_every_shape_context() {
    let identity = Identity::from_pem(SERVER_CERT, SERVER_KEY).expect("identity");
    let tls = ServerTls::new(identity).expect("server tls");
    let listener = TcpListener::bind(SocketAddr::from(([127, 0, 0, 1], 0)))
        .await
        .expect("bind");
    let addr = listener.local_addr().expect("addr");
    let server = tokio::spawn(async move {
        StoreServer::new(MemStore)
            .intercept(require_stamped_context)
            .serve_tls_with_shutdown(listener, std::future::pending(), tls)
            .await
            .ok();
    });
    let client = tls_client(addr).await.intercept(stamp_outgoing_context);
    echo_store_every_shape(&client).await;
    server.abort();
}

#[test]
fn generated_stubs_name_encoding_cancel_and_stream_drop() {
    let src = include_str!(concat!(env!("OUT_DIR"), "/kv.rs"));
    assert!(
        src.contains("Inbound `grpc-encoding` is [`::pbrs_grpc::Request::encoding`]"),
        "trait methods must name inbound encoding"
    );
    assert!(
        src.contains("Spawned producers should select on [`::pbrs_grpc::Request::cancelled`] and [`::pbrs_grpc::StreamSender::closed`]"),
        "server-streaming trait methods must name cancelled/closed"
    );
    assert!(
        src.contains("[`::pbrs_grpc::StreamSender::fail`] after a message ships trailing metadata and `grpc-status-details-bin` the same as a handler `Err`."),
        "server-streaming trait methods must name StreamSender::fail trailers"
    );
    assert!(
        src.contains("Spawned work should await [`::pbrs_grpc::Request::cancelled`]"),
        "trait methods must name spawned cancelled"
    );
    assert!(
        src.contains("That signal still fires after the client half-closes the request stream."),
        "client-streaming trait methods must name cancelled after half-close"
    );
    assert!(
        src.contains(
            "Dropping the received [`::pbrs_grpc::Streaming`] before the end resets the RPC."
        ),
        "server-streaming client methods must name stream drop"
    );
    assert!(
        src.contains("A [`::pbrs_grpc::CallHandle`] taken before await cancels the RPC."),
        "unary client methods must name CallHandle"
    );
    assert!(
        src.contains("A [`::pbrs_grpc::CallHandle`] taken before await still cancels while waiting for headers, and still cancels that live stream after headers."),
        "server-streaming and bidi client methods must name CallHandle before and after headers"
    );
    assert!(
        src.contains("Letting the deadline fire RSTs the send half before headers and after headers the same way."),
        "server-streaming and bidi client methods must name deadline RST before and after headers"
    );
    assert!(
        src.contains("A [`::pbrs_grpc::CallHandle`] taken before await still cancels after the sender is closed, while the unary response is pending."),
        "client-streaming client methods must name CallHandle after half-close"
    );
    assert!(
        src.contains("Dropping the [`::pbrs_grpc::Call`] or letting its deadline fire after that half-close resets the same way."),
        "client-streaming client methods must name drop and deadline after half-close"
    );
    assert!(
        src.contains("[`::pbrs_grpc::StreamSender::fail`] resolves the [`::pbrs_grpc::Call`] with that status (no request-side `grpc-status`; the stream is reset with CANCEL)."),
        "client-streaming client methods must name StreamSender::fail"
    );
    assert!(
        src.contains("[`::pbrs_grpc::StreamSender::fail`] before headers resolves the [`::pbrs_grpc::Call`] with that status, not `UNAVAILABLE` from the reset; after headers the received [`::pbrs_grpc::Streaming`] sees [`::pbrs_grpc::Code::Cancelled`], not that status."),
        "bidi client methods must name StreamSender::fail before headers, not UNAVAILABLE, and CANCELLED after headers"
    );
    assert!(
        src.contains(
            "[`::pbrs_grpc::Outgoing::set_timeout`] is that Call's deadline on every call shape."
        ),
        "generated client intercept rustdoc must name set_timeout as the Call deadline"
    );
    assert!(
        src.contains(
            "`clear_compress` then `set_compress(compresses_outbound())` reapplies channel gzip on every call shape."
        ),
        "generated client intercept rustdoc must name gzip reapply after clear"
    );
    assert!(
        src.contains("dropping a streaming Call resets the stream"),
        "client-streaming and bidi pairs must be must_use"
    );
    assert!(
        src.contains("The [`::pbrs_grpc::Call`] is fused after it resolves."),
        "client methods must name fused Call"
    );
    assert!(
        src.contains(
            "channel overlays (`rpc_timeout` / `waits_for_ready` / `compresses_outbound`; `clear_*` opts out of the already-applied default)"
        ),
        "generated intercept rustdoc must name channel overlays and clear_*"
    );
    assert!(
        src.contains("`peer_timeout` / `rpc_timeout` / `effective_timeout`"),
        "generated server intercept rustdoc must name the server timeout overlay"
    );
    assert!(
        src.contains(
            "gzip responses when the client advertises gzip. Applies to every call shape."
        ),
        "generated server send_compressed rustdoc must name every call shape"
    );
    assert!(
        src.contains("Replace both message caps at once. Applies to every call shape."),
        "generated message_limits rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "Cap how many RPCs the process will run at once. Applies to every call shape."
        ),
        "generated max_concurrent_rpcs rustdoc must name every call shape"
    );
    assert!(
        src.contains("Concurrent RPCs allowed per HTTP/2 connection. Applies to every call shape."),
        "generated max_concurrent_streams rustdoc must name every call shape"
    );
    assert!(
        src.contains("`Err` fails that Call on poll, including [`::pbrs_grpc::Status::with_error_details`]; nothing is sent."),
        "generated client intercept rustdoc must name typed Err"
    );
    assert!(
        src.contains("`Err` may carry [`::pbrs_grpc::Status::with_error_details`]; those trailers reach the client."),
        "generated server intercept rustdoc must name typed Err trailers"
    );
    assert!(
        src.contains("Applies to every call shape; `Err` rejects before the body is read."),
        "generated server intercept rustdoc must name reject-before-body on every call shape"
    );
    assert!(
        src.contains(
            "Bind `addr` and serve over TLS until the listener fails. Applies to every call shape."
        ),
        "generated serve_tls rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "Dial over TLS. See [`::pbrs_grpc::Channel::connect_tls`]. Applies to every call shape."
        ),
        "generated connect_tls rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "Cap inbound messages at `limit` bytes. Default 4 MiB. Applies to every call shape."
        ),
        "generated max_decoding rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "Cap outbound messages at `limit` bytes. Default unlimited. Applies to every call shape."
        ),
        "generated max_encoding rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "Wait for a connection instead of failing fast. See [`::pbrs_grpc::Channel::wait_for_ready`]. Applies to every call shape."
        ),
        "generated wait_for_ready rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "Send `:scheme https` from a [`Self::from_io`] channel. See [`::pbrs_grpc::Channel::https_scheme`]. Applies to every call shape."
        ),
        "generated https_scheme rustdoc must name every call shape"
    );
    assert!(
        src.contains("A local [`::pbrs_grpc::Status::with_error_details`] is [`::pbrs_grpc::Status::rpc`] / [`::pbrs_grpc::Status::error_details`] on that Call for every call shape."),
        "generated client intercept rustdoc must name packed Status unpacking on local Err"
    );
    assert!(
        src.contains("Outgoing getters apply to every call shape."),
        "generated client intercept rustdoc must name Outgoing getters on every call shape"
    );
    assert!(
        src.contains(
            "The HTTP/2 `:authority` this client sends. See [`::pbrs_grpc::Channel::authority`]. Applies to every call shape."
        ),
        "generated authority rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "HTTP/2 `:scheme` this client sends. See [`::pbrs_grpc::Channel::scheme`]. Applies to every call shape."
        ),
        "generated scheme rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "The `user-agent` this client sends. See [`::pbrs_grpc::Channel::grpc_user_agent`]. Applies to every call shape."
        ),
        "generated grpc_user_agent rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "Prefix the kernel `user-agent`. See [`::pbrs_grpc::Channel::user_agent`]. Applies to every call shape."
        ),
        "generated user_agent rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "Default per-RPC deadline when the request omits one. See [`::pbrs_grpc::Channel::timeout`]. Applies to every call shape."
        ),
        "generated timeout rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "[`Self::connect`] with [`::pbrs_grpc::ChannelConfig`]. Applies to every call shape."
        ),
        "generated connect_with rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "Open `connections` slots. See [`::pbrs_grpc::Channel::connect_pool`]. Applies to every call shape."
        ),
        "generated connect_pool rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "Dial a Unix domain socket. See [`::pbrs_grpc::Channel::connect_unix`]. Applies to every call shape."
        ),
        "generated connect_unix rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "Speak gRPC over an already-connected byte stream. See [`::pbrs_grpc::Channel::from_io`]. Applies to every call shape."
        ),
        "generated from_io rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "[`Self::from_io`] with [`::pbrs_grpc::ChannelConfig`]. Applies to every call shape."
        ),
        "generated from_io_with rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "Bind `path` and serve h2c over a Unix domain socket. Applies to every call shape."
        ),
        "generated serve_unix rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "Bind `path` after unlinking a crash leftover. A live listener is left alone and this fails with UNAVAILABLE. Applies to every call shape."
        ),
        "generated serve_unix_unlink rustdoc must name every call shape"
    );
    assert!(
        src.contains("HTTP/2 PING keepalive. Applies to every call shape."),
        "generated keep_alive_interval rustdoc must name every call shape"
    );
    assert!(
        src.contains("Send GOAWAY this long after accept. Applies to every call shape."),
        "generated max_connection_age rustdoc must name every call shape"
    );
    assert!(
        src.contains("Serve h2c on an existing Unix listener. Applies to every call shape."),
        "generated serve_unix_listener rustdoc must name every call shape"
    );
    assert!(
        src.contains("Serve until `shutdown` resolves, then drain. Applies to every call shape."),
        "generated serve_with_shutdown rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "Serve over TLS until `shutdown` resolves, then drain. Applies to every call shape."
        ),
        "generated serve_tls_with_shutdown rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "Serve a single already-accepted byte stream until it closes. Applies to every call shape."
        ),
        "generated serve_connection rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "Bind `addr` and serve until the listener fails. Applies to every call shape."
        ),
        "generated serve rustdoc must name every call shape"
    );
    assert!(
        src.contains("Serve on an existing listener until it fails. Applies to every call shape."),
        "generated serve_listener rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "Dial `target`. See [`::pbrs_grpc::Channel::connect`]. Applies to every call shape."
        ),
        "generated connect rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "Dial on the first RPC. See [`::pbrs_grpc::Channel::connect_lazy`]. Applies to every call shape."
        ),
        "generated connect_lazy rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "[`Self::connect_unix`] with [`::pbrs_grpc::ChannelConfig`]. Applies to every call shape."
        ),
        "generated connect_unix_with rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "[`Self::connect_unix`] that dials on the first RPC. Applies to every call shape."
        ),
        "generated connect_unix_lazy rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "[`Self::connect_tls`] with [`::pbrs_grpc::ChannelConfig`]. Applies to every call shape."
        ),
        "generated connect_tls_with rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "[`Self::connect_lazy`] with [`::pbrs_grpc::ChannelConfig`]. Applies to every call shape."
        ),
        "generated connect_lazy_with rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "[`Self::connect_lazy`] over TLS. See [`::pbrs_grpc::Channel::connect_tls_lazy`]. Applies to every call shape."
        ),
        "generated connect_tls_lazy rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "[`Self::connect_tls_lazy`] with [`::pbrs_grpc::ChannelConfig`]. Applies to every call shape."
        ),
        "generated connect_tls_lazy_with rustdoc must name every call shape"
    );
    assert!(
        src.contains(
            "[`Self::connect_unix_lazy`] with [`::pbrs_grpc::ChannelConfig`]. Applies to every call shape."
        ),
        "generated connect_unix_lazy_with rustdoc must name every call shape"
    );
}
