//! Static native-stub routing over full RPC paths.

#![allow(
    clippy::disallowed_methods,
    clippy::expect_used,
    clippy::panic,
    clippy::unwrap_used,
    unreachable_pub,
    reason = "integration tests"
)]

use pbrs_grpc::{Request, Response, Status};
use std::net::SocketAddr;
use std::time::Duration;
use tokio::net::TcpListener;

mod kv {
    #![allow(missing_docs, unused, reason = "generated by protoc-gen-pbrs")]
    include!(concat!(env!("OUT_DIR"), "/kv.rs"));
}

use kv::{GetRequest, GetResponse, Store, StoreClient, StoreServer};

struct EchoGreeter;

impl pbrs_grpc::Greeter for EchoGreeter {
    async fn say_hello(
        &self,
        request: Request<pbrs_grpc::HelloRequest>,
    ) -> Result<Response<pbrs_grpc::HelloReply>, Status> {
        let mut reply = pbrs_grpc::HelloReply::new();
        reply.set_message(request.get_ref().name().to_owned());
        Ok(Response::new(reply))
    }
}

struct KvStore;

impl Store for KvStore {
    async fn get(&self, request: Request<GetRequest>) -> Result<Response<GetResponse>, Status> {
        let mut resp = GetResponse::new();
        resp.set_found(
            !request
                .get_ref()
                .key()
                .to_str()
                .unwrap_or_default()
                .is_empty(),
        );
        Ok(Response::new(resp))
    }
}

async fn store_client(addr: SocketAddr) -> StoreClient {
    for _ in 0..80 {
        if let Ok(client) = StoreClient::connect(addr).await {
            return client;
        }
        tokio::time::sleep(Duration::from_millis(5)).await;
    }
    panic!("could not connect to {addr}");
}

#[test]
fn generated_native_stubs_use_static_full_path_dispatch() {
    let generated =
        std::fs::read_to_string(concat!(env!("OUT_DIR"), "/kv.rs")).expect("generated kv source");

    assert!(
        generated.contains("pub fn add_static_service<S: ::pbrs_grpc::Service>"),
        "generated native server should expose static tuple routing:\n{generated}"
    );
    assert!(
        generated.contains("match rpc.path()"),
        "generated native service dispatch should match the full path:\n{generated}"
    );
    assert!(
        generated.contains("\"/kv.Store/Get\""),
        "generated native service dispatch should include full method paths:\n{generated}"
    );
    assert!(
        !generated.contains("match rpc.method()"),
        "generated native service dispatch should not split the method per RPC:\n{generated}"
    );
}

#[tokio::test]
async fn generated_static_tuple_router_routes_multiple_services() {
    assert!(pbrs_grpc::Router::path_matches_service(
        "/kv.Store/Get",
        "kv.Store"
    ));
    assert!(!pbrs_grpc::Router::path_matches_service(
        "/kv.Storehouse/Get",
        "kv.Store"
    ));

    let listener = TcpListener::bind(SocketAddr::from(([127, 0, 0, 1], 0)))
        .await
        .expect("bind");
    let addr = listener.local_addr().expect("addr");
    let server = tokio::spawn(async move {
        pbrs_grpc::GreeterServer::new(EchoGreeter)
            .add_static_service(StoreServer::new(KvStore))
            .serve_listener(listener)
            .await
            .ok();
    });

    let greeter = pbrs_grpc::GreeterClient::connect(addr)
        .await
        .expect("connect greeter");
    let mut hello = pbrs_grpc::HelloRequest::new();
    hello.set_name("static");
    let reply = greeter
        .say_hello(Request::new(hello))
        .await
        .expect("greeter");
    assert_eq!(reply.get_ref().message().to_str().unwrap(), "static");

    let store = store_client(addr).await;
    let mut get = GetRequest::new();
    get.set_key("answer");
    let got = store.get(Request::new(get)).await.expect("store");
    assert!(got.get_ref().found());

    server.abort();
}
