// @generated by protoc-gen-pbrs
#[allow(unused, non_snake_case, non_camel_case_types, clippy::all)]
mod __gen {
    #![allow(unused, non_snake_case, non_camel_case_types, clippy::all)]
    use pbrs::prelude::*;
    use pbrs::UnknownFields;
    use pbrs::{
        Enum, Map, MapMut, MapView, ParseError, ProtoBytes, ProtoString, Repeated, RepeatedMut,
        RepeatedView, SerializeError, UnknownEnumValue,
    };

    #[repr(transparent)]
    #[derive(Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
    pub struct PubSelf_(i32);
    #[allow(non_upper_case_globals)]
    impl PubSelf_ {
        pub const Enum: PubSelf_ = PubSelf_(0);
        fn constant_name(self) -> Option<&'static str> {
            #[allow(unreachable_patterns)]
            Some(match self.0 {
                0 => "Enum",
                _ => return None,
            })
        }
    }
    impl From<PubSelf_> for i32 {
        fn from(v: PubSelf_) -> i32 {
            v.0
        }
    }
    impl TryFrom<i32> for PubSelf_ {
        type Error = UnknownEnumValue<Self>;
        fn try_from(val: i32) -> Result<Self, Self::Error> {
            if <Self as Enum>::is_known(val) {
                Ok(Self(val))
            } else {
                Err(UnknownEnumValue::new(val))
            }
        }
    }
    impl Default for PubSelf_ {
        fn default() -> Self {
            Self(0)
        }
    }
    impl std::fmt::Debug for PubSelf_ {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            if let Some(n) = self.constant_name() {
                write!(f, "PubSelf_::{n}")
            } else {
                write!(f, "PubSelf_::from({})", self.0)
            }
        }
    }
    impl pbrs::__internal::SealedInternal for PubSelf_ {}
    impl pbrs::Proxied for PubSelf_ {
        type View<'msg> = PubSelf_;
    }
    impl pbrs::AsView for PubSelf_ {
        type Proxied = Self;
        fn as_view(&self) -> Self {
            *self
        }
    }
    impl<'msg> pbrs::IntoView<'msg> for PubSelf_ {
        fn into_view<'shorter>(self) -> Self
        where
            'msg: 'shorter,
        {
            self
        }
    }
    impl Enum for PubSelf_ {
        const NAME: &'static str = "PubSelf_";
        fn is_known(value: i32) -> bool {
            matches!(value, 0)
        }
    }
    #[repr(transparent)]
    #[derive(Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
    pub struct SomeMsgView_(i32);
    #[allow(non_upper_case_globals)]
    impl SomeMsgView_ {
        pub const Unspecified: SomeMsgView_ = SomeMsgView_(0);
        fn constant_name(self) -> Option<&'static str> {
            #[allow(unreachable_patterns)]
            Some(match self.0 {
                0 => "Unspecified",
                _ => return None,
            })
        }
    }
    impl From<SomeMsgView_> for i32 {
        fn from(v: SomeMsgView_) -> i32 {
            v.0
        }
    }
    impl TryFrom<i32> for SomeMsgView_ {
        type Error = UnknownEnumValue<Self>;
        fn try_from(val: i32) -> Result<Self, Self::Error> {
            if <Self as Enum>::is_known(val) {
                Ok(Self(val))
            } else {
                Err(UnknownEnumValue::new(val))
            }
        }
    }
    impl Default for SomeMsgView_ {
        fn default() -> Self {
            Self(0)
        }
    }
    impl std::fmt::Debug for SomeMsgView_ {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            if let Some(n) = self.constant_name() {
                write!(f, "SomeMsgView_::{n}")
            } else {
                write!(f, "SomeMsgView_::from({})", self.0)
            }
        }
    }
    impl pbrs::__internal::SealedInternal for SomeMsgView_ {}
    impl pbrs::Proxied for SomeMsgView_ {
        type View<'msg> = SomeMsgView_;
    }
    impl pbrs::AsView for SomeMsgView_ {
        type Proxied = Self;
        fn as_view(&self) -> Self {
            *self
        }
    }
    impl<'msg> pbrs::IntoView<'msg> for SomeMsgView_ {
        fn into_view<'shorter>(self) -> Self
        where
            'msg: 'shorter,
        {
            self
        }
    }
    impl Enum for SomeMsgView_ {
        const NAME: &'static str = "SomeMsgView_";
        fn is_known(value: i32) -> bool {
            matches!(value, 0)
        }
    }
    #[derive(Clone, Debug)]
    pub struct AccessorsCollide {
        set_x_2: pbrs::rt::LazyMsg<SetX>,
        x: pbrs::rt::LazyMsg<X>,
        x_mut_5: pbrs::rt::OptBool,
        clear_x_7: Option<i32>,
        unknown: UnknownFields,
        cached_size: pbrs::rt::CachedSize,
    }
    impl PartialEq for AccessorsCollide {
        fn eq(&self, other: &Self) -> bool {
            if self.set_x_2 != other.set_x_2 {
                return false;
            }
            if self.x != other.x {
                return false;
            }
            if self.x_mut_5 != other.x_mut_5 {
                return false;
            }
            if self.clear_x_7 != other.clear_x_7 {
                return false;
            }
            self.unknown == other.unknown
        }
    }
    impl Eq for AccessorsCollide {}
    impl Default for AccessorsCollide {
        #[inline(always)]
        fn default() -> Self {
            unsafe { pbrs::rt::zeroed_message() }
        }
    }
    impl AccessorsCollide {
        pub fn new() -> Self {
            Self::default()
        }
        pub const EMPTY_PARSE_OK: bool = true;
        pub const FULL_NAME: &'static str = "type.type.AccessorsCollide";
        pub fn has_set_x_2(&self) -> bool {
            self.set_x_2.is_some()
        }
        pub fn set_x_2(&self) -> &SetX {
            self.set_x_2
                .as_deref()
                .unwrap_or(pbrs::gen_support::default_instance_of())
        }
        pub fn set_x_2_opt(&self) -> Option<&SetX> {
            self.set_x_2.as_deref()
        }
        pub fn set_x_2_view(&self) -> SetXView<'_> {
            SetXView(self.set_x_2())
        }
        pub fn set_set_x_2(&mut self, v: SetX) {
            self.cached_size.dirty();
            self.set_x_2 = pbrs::rt::LazyMsg::from_owned(v);
        }
        pub fn set_x_2_mut(&mut self) -> &mut SetX {
            self.cached_size.dirty();
            self.set_x_2.get_or_insert()
        }
        pub fn clear_set_x_2(&mut self) {
            self.cached_size.dirty();
            self.set_x_2.clear();
        }
        pub fn has_x(&self) -> bool {
            self.x.is_some()
        }
        pub fn x(&self) -> &X {
            self.x
                .as_deref()
                .unwrap_or(pbrs::gen_support::default_instance_of())
        }
        pub fn x_opt(&self) -> Option<&X> {
            self.x.as_deref()
        }
        pub fn x_view(&self) -> XView<'_> {
            XView(self.x())
        }
        pub fn set_x(&mut self, v: X) {
            self.cached_size.dirty();
            self.x = pbrs::rt::LazyMsg::from_owned(v);
        }
        pub fn x_mut(&mut self) -> &mut X {
            self.cached_size.dirty();
            self.x.get_or_insert()
        }
        pub fn clear_x(&mut self) {
            self.cached_size.dirty();
            self.x.clear();
        }
        pub fn has_x_mut_5(&self) -> bool {
            self.x_mut_5.is_some()
        }
        pub fn x_mut_5(&self) -> bool {
            self.x_mut_5.unwrap_or(false)
        }
        pub fn x_mut_5_opt(&self) -> Option<bool> {
            self.x_mut_5.get()
        }
        pub fn set_x_mut_5(&mut self, v: bool) {
            self.cached_size.dirty();
            self.x_mut_5 = pbrs::rt::OptBool::some(v);
        }
        pub fn clear_x_mut_5(&mut self) {
            self.cached_size.dirty();
            self.x_mut_5 = pbrs::rt::OptBool::NONE;
        }
        pub fn has_clear_x_7(&self) -> bool {
            self.clear_x_7.is_some()
        }
        pub fn clear_x_7(&self) -> i32 {
            self.clear_x_7.unwrap_or(0)
        }
        pub fn clear_x_7_opt(&self) -> Option<i32> {
            self.clear_x_7.map(|v| v)
        }
        pub fn set_clear_x_7(&mut self, v: i32) {
            self.cached_size.dirty();
            self.clear_x_7 = Some(v);
        }
        pub fn clear_clear_x_7(&mut self) {
            self.cached_size.dirty();
            self.clear_x_7 = None;
        }
        #[inline(always)]
        fn check_required(&self) -> Result<(), ParseError> {
            Ok(())
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return self.check_required();
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return Ok(());
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(data, wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    2 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            if self.set_x_2.is_some() {
                                let mut ip = 0;
                                let mut sw = None;
                                self.set_x_2.get_or_insert().merge_inner(
                                    &data[s..e],
                                    &mut sw,
                                    &mut ip,
                                    depth + 1,
                                    true,
                                    None,
                                )?;
                            } else {
                                let mut ip = 0;
                                SetX::validate_inner(
                                    &pbrs::rt::Wire::ensure(wire, data).window(s, e),
                                    &mut ip,
                                    depth + 1,
                                )?;
                                self.set_x_2 = pbrs::rt::LazyMsg::from_wire(
                                    pbrs::rt::Wire::ensure(wire, data).window(s, e),
                                );
                            }
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    3 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            if self.x.is_some() {
                                let mut ip = 0;
                                let mut sw = None;
                                self.x.get_or_insert().merge_inner(
                                    &data[s..e],
                                    &mut sw,
                                    &mut ip,
                                    depth + 1,
                                    true,
                                    None,
                                )?;
                            } else {
                                let mut ip = 0;
                                X::validate_inner(
                                    &pbrs::rt::Wire::ensure(wire, data).window(s, e),
                                    &mut ip,
                                    depth + 1,
                                )?;
                                self.x = pbrs::rt::LazyMsg::from_wire(
                                    pbrs::rt::Wire::ensure(wire, data).window(s, e),
                                );
                            }
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    5 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            self.x_mut_5 =
                                pbrs::rt::OptBool::some(pbrs::rt::decode_varint(data, pos)? != 0);
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    7 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            self.clear_x_7 = Some(pbrs::rt::decode_varint(data, pos)? as i32);
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    _ => self
                        .unknown
                        .fields
                        .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            if enforce {
                self.check_required()?;
            }
            Ok(())
        }
        fn validate_inner(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
        ) -> Result<(), ParseError> {
            Self::validate_until(wire, pos, depth, None)
        }
        fn validate_until(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    2 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            let mut ip = 0;
                            SetX::validate_inner(&wire.window(s, e), &mut ip, depth + 1)?;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    3 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            let mut ip = 0;
                            X::validate_inner(&wire.window(s, e), &mut ip, depth + 1)?;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    5 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_varint(data, pos)? != 0;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    7 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_varint(data, pos)? as i32;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    _ => pbrs::rt::skip_field(data, pos, w)?,
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            if let Some(p) = self.set_x_2.wire_bytes() {
                n += pbrs::rt::key_len_value_len(2, p.len() as u64);
            } else if let Some(m) = self.set_x_2.as_deref() {
                n += pbrs::rt::key_len_value_len(2, m.compute_size());
            }
            if let Some(p) = self.x.wire_bytes() {
                n += pbrs::rt::key_len_value_len(3, p.len() as u64);
            } else if let Some(m) = self.x.as_deref() {
                n += pbrs::rt::key_len_value_len(3, m.compute_size());
            }
            if let Some(v) = self.x_mut_5.get() {
                n += pbrs::rt::tag_len(5, pbrs::rt::WIRE_VARINT)
                    + pbrs::rt::varint_len(u64::from(v));
            }
            if let Some(v) = self.clear_x_7 {
                n += pbrs::rt::tag_len(7, pbrs::rt::WIRE_VARINT) + pbrs::rt::varint_len((v) as u64);
            }
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut impl pbrs::rt::WireOut) {
            if let Some(p) = self.set_x_2.wire_bytes() {
                pbrs::rt::encode_len_header(out, 2, p.len() as u64);
                out.extend_from_slice(p);
            } else if let Some(m) = self.set_x_2.as_deref() {
                pbrs::rt::encode_len_header(out, 2, m.compute_size());
                m.write_to(out);
            }
            if let Some(p) = self.x.wire_bytes() {
                pbrs::rt::encode_len_header(out, 3, p.len() as u64);
                out.extend_from_slice(p);
            } else if let Some(m) = self.x.as_deref() {
                pbrs::rt::encode_len_header(out, 3, m.compute_size());
                m.write_to(out);
            }
            if let Some(v) = self.x_mut_5.get() {
                pbrs::rt::encode_tag(out, 5, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, u64::from(v));
            }
            if let Some(v) = self.clear_x_7 {
                pbrs::rt::encode_tag(out, 7, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, v as u64);
            }
            self.unknown.encode(out);
        }
    }
    pbrs::impl_typed_message!(AccessorsCollide, AccessorsCollideView, AccessorsCollideMut);
    #[derive(Clone, Debug)]
    pub struct SetX {
        unknown: UnknownFields,
        cached_size: pbrs::rt::CachedSize,
    }
    impl PartialEq for SetX {
        fn eq(&self, other: &Self) -> bool {
            self.unknown == other.unknown
        }
    }
    impl Eq for SetX {}
    impl Default for SetX {
        #[inline(always)]
        fn default() -> Self {
            unsafe { pbrs::rt::zeroed_message() }
        }
    }
    impl SetX {
        pub fn new() -> Self {
            Self::default()
        }
        pub const EMPTY_PARSE_OK: bool = true;
        pub const FULL_NAME: &'static str = "type.type.AccessorsCollide.SetX";
        #[inline(always)]
        fn check_required(&self) -> Result<(), ParseError> {
            Ok(())
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return self.check_required();
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return Ok(());
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(data, wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    _ => self
                        .unknown
                        .fields
                        .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            if enforce {
                self.check_required()?;
            }
            Ok(())
        }
        fn validate_inner(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
        ) -> Result<(), ParseError> {
            Self::validate_until(wire, pos, depth, None)
        }
        fn validate_until(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    _ => pbrs::rt::skip_field(data, pos, w)?,
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut impl pbrs::rt::WireOut) {
            self.unknown.encode(out);
        }
    }
    pbrs::impl_typed_message!(SetX, SetXView, SetXMut);
    #[derive(Clone, Debug)]
    pub struct X {
        unknown: UnknownFields,
        cached_size: pbrs::rt::CachedSize,
    }
    impl PartialEq for X {
        fn eq(&self, other: &Self) -> bool {
            self.unknown == other.unknown
        }
    }
    impl Eq for X {}
    impl Default for X {
        #[inline(always)]
        fn default() -> Self {
            unsafe { pbrs::rt::zeroed_message() }
        }
    }
    impl X {
        pub fn new() -> Self {
            Self::default()
        }
        pub const EMPTY_PARSE_OK: bool = true;
        pub const FULL_NAME: &'static str = "type.type.AccessorsCollide.X";
        #[inline(always)]
        fn check_required(&self) -> Result<(), ParseError> {
            Ok(())
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return self.check_required();
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return Ok(());
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(data, wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    _ => self
                        .unknown
                        .fields
                        .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            if enforce {
                self.check_required()?;
            }
            Ok(())
        }
        fn validate_inner(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
        ) -> Result<(), ParseError> {
            Self::validate_until(wire, pos, depth, None)
        }
        fn validate_until(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    _ => pbrs::rt::skip_field(data, pos, w)?,
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut impl pbrs::rt::WireOut) {
            self.unknown.encode(out);
        }
    }
    pbrs::impl_typed_message!(X, XView, XMut);
    #[derive(Clone, Debug)]
    pub struct MangleViewTest {
        unknown: UnknownFields,
        cached_size: pbrs::rt::CachedSize,
    }
    impl PartialEq for MangleViewTest {
        fn eq(&self, other: &Self) -> bool {
            self.unknown == other.unknown
        }
    }
    impl Eq for MangleViewTest {}
    impl Default for MangleViewTest {
        #[inline(always)]
        fn default() -> Self {
            unsafe { pbrs::rt::zeroed_message() }
        }
    }
    impl MangleViewTest {
        pub fn new() -> Self {
            Self::default()
        }
        pub const EMPTY_PARSE_OK: bool = true;
        pub const FULL_NAME: &'static str = "type.type.MangleViewTest";
        #[inline(always)]
        fn check_required(&self) -> Result<(), ParseError> {
            Ok(())
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return self.check_required();
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return Ok(());
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(data, wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    _ => self
                        .unknown
                        .fields
                        .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            if enforce {
                self.check_required()?;
            }
            Ok(())
        }
        fn validate_inner(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
        ) -> Result<(), ParseError> {
            Self::validate_until(wire, pos, depth, None)
        }
        fn validate_until(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    _ => pbrs::rt::skip_field(data, pos, w)?,
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut impl pbrs::rt::WireOut) {
            self.unknown.encode(out);
        }
    }
    pbrs::impl_typed_message!(MangleViewTest, MangleViewTestView, MangleViewTestMut);
    #[derive(Clone, Debug)]
    pub struct MangleViewTestView_ {
        unknown: UnknownFields,
        cached_size: pbrs::rt::CachedSize,
    }
    impl PartialEq for MangleViewTestView_ {
        fn eq(&self, other: &Self) -> bool {
            self.unknown == other.unknown
        }
    }
    impl Eq for MangleViewTestView_ {}
    impl Default for MangleViewTestView_ {
        #[inline(always)]
        fn default() -> Self {
            unsafe { pbrs::rt::zeroed_message() }
        }
    }
    impl MangleViewTestView_ {
        pub fn new() -> Self {
            Self::default()
        }
        pub const EMPTY_PARSE_OK: bool = true;
        pub const FULL_NAME: &'static str = "type.type.MangleViewTestView";
        #[inline(always)]
        fn check_required(&self) -> Result<(), ParseError> {
            Ok(())
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return self.check_required();
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return Ok(());
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(data, wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    _ => self
                        .unknown
                        .fields
                        .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            if enforce {
                self.check_required()?;
            }
            Ok(())
        }
        fn validate_inner(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
        ) -> Result<(), ParseError> {
            Self::validate_until(wire, pos, depth, None)
        }
        fn validate_until(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    _ => pbrs::rt::skip_field(data, pos, w)?,
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut impl pbrs::rt::WireOut) {
            self.unknown.encode(out);
        }
    }
    pbrs::impl_typed_message!(
        MangleViewTestView_,
        MangleViewTestView_View,
        MangleViewTestView_Mut
    );
    #[derive(Clone, Debug)]
    pub struct Pub {
        unknown: UnknownFields,
        cached_size: pbrs::rt::CachedSize,
    }
    impl PartialEq for Pub {
        fn eq(&self, other: &Self) -> bool {
            self.unknown == other.unknown
        }
    }
    impl Eq for Pub {}
    impl Default for Pub {
        #[inline(always)]
        fn default() -> Self {
            unsafe { pbrs::rt::zeroed_message() }
        }
    }
    impl Pub {
        pub fn new() -> Self {
            Self::default()
        }
        pub const EMPTY_PARSE_OK: bool = true;
        pub const FULL_NAME: &'static str = "type.type.Pub";
        #[inline(always)]
        fn check_required(&self) -> Result<(), ParseError> {
            Ok(())
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return self.check_required();
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return Ok(());
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(data, wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    _ => self
                        .unknown
                        .fields
                        .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            if enforce {
                self.check_required()?;
            }
            Ok(())
        }
        fn validate_inner(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
        ) -> Result<(), ParseError> {
            Self::validate_until(wire, pos, depth, None)
        }
        fn validate_until(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    _ => pbrs::rt::skip_field(data, pos, w)?,
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut impl pbrs::rt::WireOut) {
            self.unknown.encode(out);
        }
    }
    pbrs::impl_typed_message!(Pub, PubView, PubMut);
    #[derive(Clone, Debug)]
    pub struct Ref {
        r#const: Option<i32>,
        unknown: UnknownFields,
        cached_size: pbrs::rt::CachedSize,
    }
    impl PartialEq for Ref {
        fn eq(&self, other: &Self) -> bool {
            if self.r#const != other.r#const {
                return false;
            }
            self.unknown == other.unknown
        }
    }
    impl Eq for Ref {}
    impl Default for Ref {
        #[inline(always)]
        fn default() -> Self {
            unsafe { pbrs::rt::zeroed_message() }
        }
    }
    impl Ref {
        pub fn new() -> Self {
            Self::default()
        }
        pub const EMPTY_PARSE_OK: bool = true;
        pub const FULL_NAME: &'static str = "type.type.Ref";
        pub fn has_const(&self) -> bool {
            self.r#const.is_some()
        }
        pub fn r#const(&self) -> PubSelf_ {
            PubSelf_(self.r#const.unwrap_or(0))
        }
        pub fn r#const_opt(&self) -> Option<PubSelf_> {
            self.r#const.map(|v| PubSelf_(v))
        }
        pub fn set_const(&mut self, v: impl Into<i32>) {
            self.cached_size.dirty();
            self.r#const = Some(v.into());
        }
        pub fn clear_const(&mut self) {
            self.cached_size.dirty();
            self.r#const = None;
        }
        #[inline(always)]
        fn check_required(&self) -> Result<(), ParseError> {
            Ok(())
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return self.check_required();
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return Ok(());
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(data, wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    3 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            self.r#const = Some(pbrs::rt::decode_varint(data, pos)? as i32);
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    _ => self
                        .unknown
                        .fields
                        .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            if enforce {
                self.check_required()?;
            }
            Ok(())
        }
        fn validate_inner(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
        ) -> Result<(), ParseError> {
            Self::validate_until(wire, pos, depth, None)
        }
        fn validate_until(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    3 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_varint(data, pos)? as i32;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    _ => pbrs::rt::skip_field(data, pos, w)?,
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            if let Some(v) = self.r#const {
                n += pbrs::rt::tag_len(3, pbrs::rt::WIRE_VARINT) + pbrs::rt::varint_len((v) as u64);
            }
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut impl pbrs::rt::WireOut) {
            if let Some(v) = self.r#const {
                pbrs::rt::encode_tag(out, 3, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, v as u64);
            }
            self.unknown.encode(out);
        }
    }
    pbrs::impl_typed_message!(Ref, RefView, RefMut);
    #[derive(Clone, Debug)]
    pub struct Self_ {
        r#for: Option<i32>,
        self_: pbrs::rt::LazyMsg<Self_>,
        r#true: pbrs::rt::OptBool,
        r#false: Option<Box<pbrs::rt::LazyStr>>,
        r#match: Repeated<i32>,
        clear: pbrs::rt::OptBool,
        new_: pbrs::rt::OptBool,
        unknown: UnknownFields,
        cached_size: pbrs::rt::CachedSize,
    }
    impl PartialEq for Self_ {
        fn eq(&self, other: &Self) -> bool {
            if self.r#for != other.r#for {
                return false;
            }
            if self.self_ != other.self_ {
                return false;
            }
            if self.r#true != other.r#true {
                return false;
            }
            if self.r#false != other.r#false {
                return false;
            }
            if self.r#match != other.r#match {
                return false;
            }
            if self.clear != other.clear {
                return false;
            }
            if self.new_ != other.new_ {
                return false;
            }
            self.unknown == other.unknown
        }
    }
    impl Eq for Self_ {}
    impl Default for Self_ {
        #[inline(always)]
        fn default() -> Self {
            unsafe { pbrs::rt::zeroed_message() }
        }
    }
    impl Self_ {
        pub fn new() -> Self {
            Self::default()
        }
        pub const EMPTY_PARSE_OK: bool = true;
        pub const FULL_NAME: &'static str = "type.type.Self";
        pub fn has_for(&self) -> bool {
            self.r#for.is_some()
        }
        pub fn r#for(&self) -> i32 {
            self.r#for.unwrap_or(0)
        }
        pub fn r#for_opt(&self) -> Option<i32> {
            self.r#for.map(|v| v)
        }
        pub fn set_for(&mut self, v: i32) {
            self.cached_size.dirty();
            self.r#for = Some(v);
        }
        pub fn clear_for(&mut self) {
            self.cached_size.dirty();
            self.r#for = None;
        }
        pub fn has_self(&self) -> bool {
            self.self_.is_some()
        }
        pub fn self_(&self) -> &Self_ {
            self.self_
                .as_deref()
                .unwrap_or(pbrs::gen_support::default_instance_of())
        }
        pub fn self__opt(&self) -> Option<&Self_> {
            self.self_.as_deref()
        }
        pub fn self__view(&self) -> Self_View<'_> {
            Self_View(self.self_())
        }
        pub fn set_self(&mut self, v: Self_) {
            self.cached_size.dirty();
            self.self_ = pbrs::rt::LazyMsg::from_owned(v);
        }
        pub fn self__mut(&mut self) -> &mut Self_ {
            self.cached_size.dirty();
            self.self_.get_or_insert()
        }
        pub fn clear_self(&mut self) {
            self.cached_size.dirty();
            self.self_.clear();
        }
        pub fn has_true(&self) -> bool {
            self.r#true.is_some()
        }
        pub fn r#true(&self) -> bool {
            self.r#true.unwrap_or(false)
        }
        pub fn r#true_opt(&self) -> Option<bool> {
            self.r#true.get()
        }
        pub fn set_true(&mut self, v: bool) {
            self.cached_size.dirty();
            self.r#true = pbrs::rt::OptBool::some(v);
        }
        pub fn clear_true(&mut self) {
            self.cached_size.dirty();
            self.r#true = pbrs::rt::OptBool::NONE;
        }
        pub fn has_false(&self) -> bool {
            self.r#false.is_some()
        }
        pub fn r#false(&self) -> &pbrs::ProtoStr {
            self.r#false
                .as_ref()
                .map(|s| s.as_view())
                .unwrap_or_else(|| pbrs::ProtoStr::from_bytes(b""))
        }
        pub fn r#false_opt(&self) -> Option<&pbrs::ProtoStr> {
            self.r#false.as_ref().map(|s| s.as_view())
        }
        pub fn set_false(&mut self, v: impl pbrs::IntoProxied<ProtoString>) {
            self.cached_size.dirty();
            self.r#false = Some(Box::new(pbrs::rt::LazyStr::owned(v.into_proxied())));
        }
        pub fn clear_false(&mut self) {
            self.cached_size.dirty();
            self.r#false = None;
        }
        pub fn r#match(&self) -> RepeatedView<'_, i32> {
            self.r#match.as_view()
        }
        pub fn r#match_mut(&mut self) -> RepeatedMut<'_, i32> {
            self.cached_size.dirty();
            self.r#match.as_mut()
        }
        pub fn set_match(&mut self, v: impl IntoIterator<Item = i32>) {
            self.cached_size.dirty();
            self.r#match = v.into_iter().collect();
        }
        pub fn has_clear(&self) -> bool {
            self.clear.is_some()
        }
        pub fn clear(&self) -> bool {
            self.clear.unwrap_or(false)
        }
        pub fn clear_opt(&self) -> Option<bool> {
            self.clear.get()
        }
        pub fn set_clear(&mut self, v: bool) {
            self.cached_size.dirty();
            self.clear = pbrs::rt::OptBool::some(v);
        }
        pub fn clear_clear(&mut self) {
            self.cached_size.dirty();
            self.clear = pbrs::rt::OptBool::NONE;
        }
        pub fn has_new(&self) -> bool {
            self.new_.is_some()
        }
        pub fn new_(&self) -> bool {
            self.new_.unwrap_or(false)
        }
        pub fn new__opt(&self) -> Option<bool> {
            self.new_.get()
        }
        pub fn set_new(&mut self, v: bool) {
            self.cached_size.dirty();
            self.new_ = pbrs::rt::OptBool::some(v);
        }
        pub fn clear_new(&mut self) {
            self.cached_size.dirty();
            self.new_ = pbrs::rt::OptBool::NONE;
        }
        #[inline(always)]
        fn check_required(&self) -> Result<(), ParseError> {
            Ok(())
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return self.check_required();
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return Ok(());
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(data, wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    1 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            self.r#for = Some(pbrs::rt::decode_varint(data, pos)? as i32);
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    2 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            if self.self_.is_some() {
                                let mut ip = 0;
                                let mut sw = None;
                                self.self_.get_or_insert().merge_inner(
                                    &data[s..e],
                                    &mut sw,
                                    &mut ip,
                                    depth + 1,
                                    true,
                                    None,
                                )?;
                            } else {
                                let mut ip = 0;
                                Self_::validate_inner(
                                    &pbrs::rt::Wire::ensure(wire, data).window(s, e),
                                    &mut ip,
                                    depth + 1,
                                )?;
                                self.self_ = pbrs::rt::LazyMsg::from_wire(
                                    pbrs::rt::Wire::ensure(wire, data).window(s, e),
                                );
                            }
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    3 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            self.r#true =
                                pbrs::rt::OptBool::some(pbrs::rt::decode_varint(data, pos)? != 0);
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    4 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            let b = &data[s..e];
                            self.r#false = Some(Box::new(pbrs::rt::LazyStr::from_span(
                                pbrs::rt::Wire::ensure(wire, data),
                                s,
                                e,
                            )));
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    5 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let p = pbrs::rt::read_len_bytes(data, pos)?;
                            let mut i = 0;
                            while i < p.len() {
                                self.r#match
                                    .push(pbrs::rt::decode_varint(p, &mut i)? as i32);
                            }
                        }
                        pbrs::rt::WIRE_VARINT => {
                            self.r#match
                                .push(pbrs::rt::decode_varint(data, pos)? as i32);
                            let rest = data.len().saturating_sub(*pos);
                            if rest > 2 {
                                self.r#match.reserve(rest / 3);
                            }
                            while *pos < data.len() {
                                let save = *pos;
                                match pbrs::rt::decode_tag(data, pos) {
                                    Ok((n2, w2)) if n2 == 5 && w2 == pbrs::rt::WIRE_VARINT => self
                                        .r#match
                                        .push(pbrs::rt::decode_varint(data, pos)? as i32),
                                    Ok(_) => {
                                        *pos = save;
                                        break;
                                    }
                                    Err(e) => return Err(e),
                                }
                            }
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    6 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            self.clear =
                                pbrs::rt::OptBool::some(pbrs::rt::decode_varint(data, pos)? != 0);
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    7 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            self.new_ =
                                pbrs::rt::OptBool::some(pbrs::rt::decode_varint(data, pos)? != 0);
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    _ => self
                        .unknown
                        .fields
                        .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            if enforce {
                self.check_required()?;
            }
            Ok(())
        }
        fn validate_inner(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
        ) -> Result<(), ParseError> {
            Self::validate_until(wire, pos, depth, None)
        }
        fn validate_until(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    1 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_varint(data, pos)? as i32;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    2 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            let mut ip = 0;
                            Self_::validate_inner(&wire.window(s, e), &mut ip, depth + 1)?;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    3 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_varint(data, pos)? != 0;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    4 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    5 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            pbrs::rt::PackedI32::validate_bytes(&data[s..e])?;
                        }
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_varint(data, pos)? as i32;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    6 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_varint(data, pos)? != 0;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    7 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_varint(data, pos)? != 0;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    _ => pbrs::rt::skip_field(data, pos, w)?,
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            if let Some(v) = self.r#for {
                n += pbrs::rt::tag_len(1, pbrs::rt::WIRE_VARINT) + pbrs::rt::varint_len((v) as u64);
            }
            if let Some(p) = self.self_.wire_bytes() {
                n += pbrs::rt::key_len_value_len(2, p.len() as u64);
            } else if let Some(m) = self.self_.as_deref() {
                n += pbrs::rt::key_len_value_len(2, m.compute_size());
            }
            if let Some(v) = self.r#true.get() {
                n += pbrs::rt::tag_len(3, pbrs::rt::WIRE_VARINT)
                    + pbrs::rt::varint_len(u64::from(v));
            }
            if let Some(s) = &self.r#false {
                n += pbrs::rt::key_len_value_len(4, s.as_bytes().len() as u64);
            }
            for t in self.r#match.iter() {
                n +=
                    pbrs::rt::tag_len(5, pbrs::rt::WIRE_VARINT) + pbrs::rt::varint_len((*t) as u64);
            }
            if let Some(v) = self.clear.get() {
                n += pbrs::rt::tag_len(6, pbrs::rt::WIRE_VARINT)
                    + pbrs::rt::varint_len(u64::from(v));
            }
            if let Some(v) = self.new_.get() {
                n += pbrs::rt::tag_len(7, pbrs::rt::WIRE_VARINT)
                    + pbrs::rt::varint_len(u64::from(v));
            }
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut impl pbrs::rt::WireOut) {
            if let Some(v) = self.r#for {
                pbrs::rt::encode_tag(out, 1, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, v as u64);
            }
            if let Some(p) = self.self_.wire_bytes() {
                pbrs::rt::encode_len_header(out, 2, p.len() as u64);
                out.extend_from_slice(p);
            } else if let Some(m) = self.self_.as_deref() {
                pbrs::rt::encode_len_header(out, 2, m.compute_size());
                m.write_to(out);
            }
            if let Some(v) = self.r#true.get() {
                pbrs::rt::encode_tag(out, 3, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, u64::from(v));
            }
            if let Some(s) = &self.r#false {
                pbrs::rt::encode_len_field(out, 4, s.as_bytes());
            }
            for t in self.r#match.iter() {
                pbrs::rt::encode_tag(out, 5, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, *t as u64);
            }
            if let Some(v) = self.clear.get() {
                pbrs::rt::encode_tag(out, 6, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, u64::from(v));
            }
            if let Some(v) = self.new_.get() {
                pbrs::rt::encode_tag(out, 7, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, u64::from(v));
            }
            self.unknown.encode(out);
        }
    }
    pbrs::impl_typed_message!(Self_, Self_View, Self_Mut);
    #[derive(Clone, Debug)]
    pub struct SomeMsg {
        unknown: UnknownFields,
        cached_size: pbrs::rt::CachedSize,
    }
    impl PartialEq for SomeMsg {
        fn eq(&self, other: &Self) -> bool {
            self.unknown == other.unknown
        }
    }
    impl Eq for SomeMsg {}
    impl Default for SomeMsg {
        #[inline(always)]
        fn default() -> Self {
            unsafe { pbrs::rt::zeroed_message() }
        }
    }
    impl SomeMsg {
        pub fn new() -> Self {
            Self::default()
        }
        pub const EMPTY_PARSE_OK: bool = true;
        pub const FULL_NAME: &'static str = "type.type.SomeMsg";
        #[inline(always)]
        fn check_required(&self) -> Result<(), ParseError> {
            Ok(())
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return self.check_required();
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return Ok(());
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(data, wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    _ => self
                        .unknown
                        .fields
                        .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            if enforce {
                self.check_required()?;
            }
            Ok(())
        }
        fn validate_inner(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
        ) -> Result<(), ParseError> {
            Self::validate_until(wire, pos, depth, None)
        }
        fn validate_until(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    _ => pbrs::rt::skip_field(data, pos, w)?,
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut impl pbrs::rt::WireOut) {
            self.unknown.encode(out);
        }
    }
    pbrs::impl_typed_message!(SomeMsg, SomeMsgView, SomeMsgMut);
    #[derive(Clone, Debug)]
    pub struct r#enum {
        unknown: UnknownFields,
        cached_size: pbrs::rt::CachedSize,
    }
    impl PartialEq for r#enum {
        fn eq(&self, other: &Self) -> bool {
            self.unknown == other.unknown
        }
    }
    impl Eq for r#enum {}
    impl Default for r#enum {
        #[inline(always)]
        fn default() -> Self {
            unsafe { pbrs::rt::zeroed_message() }
        }
    }
    impl r#enum {
        pub fn new() -> Self {
            Self::default()
        }
        pub const EMPTY_PARSE_OK: bool = true;
        pub const FULL_NAME: &'static str = "type.type.enum";
        #[inline(always)]
        fn check_required(&self) -> Result<(), ParseError> {
            Ok(())
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return self.check_required();
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return Ok(());
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(data, wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    _ => self
                        .unknown
                        .fields
                        .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            if enforce {
                self.check_required()?;
            }
            Ok(())
        }
        fn validate_inner(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
        ) -> Result<(), ParseError> {
            Self::validate_until(wire, pos, depth, None)
        }
        fn validate_until(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    _ => pbrs::rt::skip_field(data, pos, w)?,
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut impl pbrs::rt::WireOut) {
            self.unknown.encode(out);
        }
    }
    pbrs::impl_typed_message!(r#enum, r#enumView, r#enumMut);
    pub mod accessors_collide {
        pub use super::SetX;
        pub use super::X;
    }
    pub mod r#pub {
        pub use super::PubSelf_ as Self_;
    }
}
#[allow(unused_imports)]
pub use __gen::*;
