// @generated by protoc-gen-pbrs
#[allow(unused, non_snake_case, non_camel_case_types, clippy::all)]
mod __gen {
    #![allow(unused, non_snake_case, non_camel_case_types, clippy::all)]
    use pbrs::prelude::*;
    use pbrs::UnknownFields;
    use pbrs::{
        Enum, Map, MapMut, MapView, ParseError, ProtoBytes, ProtoString, Repeated, RepeatedMut,
        RepeatedView, SerializeError, UnknownEnumValue,
    };

    #[repr(transparent)]
    #[derive(Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
    pub struct ImportedEnum(i32);
    #[allow(non_upper_case_globals)]
    impl ImportedEnum {
        pub const Unknown: ImportedEnum = ImportedEnum(0);
        pub const Bar: ImportedEnum = ImportedEnum(1);
        fn constant_name(self) -> Option<&'static str> {
            #[allow(unreachable_patterns)]
            Some(match self.0 {
                0 => "Unknown",
                1 => "Bar",
                _ => return None,
            })
        }
    }
    impl From<ImportedEnum> for i32 {
        fn from(v: ImportedEnum) -> i32 {
            v.0
        }
    }
    impl TryFrom<i32> for ImportedEnum {
        type Error = UnknownEnumValue<Self>;
        fn try_from(val: i32) -> Result<Self, Self::Error> {
            if <Self as Enum>::is_known(val) {
                Ok(Self(val))
            } else {
                Err(UnknownEnumValue::new(pbrs::__internal::Private, val))
            }
        }
    }
    impl Default for ImportedEnum {
        fn default() -> Self {
            Self(0)
        }
    }
    impl std::fmt::Debug for ImportedEnum {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            if let Some(n) = self.constant_name() {
                write!(f, "ImportedEnum::{n}")
            } else {
                write!(f, "ImportedEnum::from({})", self.0)
            }
        }
    }
    impl pbrs::__internal::SealedInternal for ImportedEnum {}
    impl pbrs::Proxied for ImportedEnum {
        type View<'msg> = ImportedEnum;
    }
    impl pbrs::AsView for ImportedEnum {
        type Proxied = Self;
        fn as_view(&self) -> Self {
            *self
        }
    }
    impl<'msg> pbrs::IntoView<'msg> for ImportedEnum {
        fn into_view<'shorter>(self) -> Self
        where
            'msg: 'shorter,
        {
            self
        }
    }
    impl Enum for ImportedEnum {
        const NAME: &'static str = "ImportedEnum";
        fn is_known(value: i32) -> bool {
            matches!(value, 0 | 1)
        }
    }
    #[derive(Clone, Debug)]
    pub struct ImportedMessage {
        num: Option<i32>,
        unknown: UnknownFields,
        cached_size: pbrs::rt::CachedSize,
    }
    impl PartialEq for ImportedMessage {
        fn eq(&self, other: &Self) -> bool {
            if self.num != other.num {
                return false;
            }
            self.unknown == other.unknown
        }
    }
    impl Eq for ImportedMessage {}
    impl Default for ImportedMessage {
        #[inline(always)]
        fn default() -> Self {
            unsafe { pbrs::rt::zeroed_message() }
        }
    }
    impl ImportedMessage {
        pub fn new() -> Self {
            Self::default()
        }
        pub const EMPTY_PARSE_OK: bool = true;
        pub const FULL_NAME: &'static str = "imported_types.ImportedMessage";
        pub fn has_num(&self) -> bool {
            self.num.is_some()
        }
        pub fn num(&self) -> i32 {
            self.num.unwrap_or(0)
        }
        pub fn num_opt(&self) -> Option<i32> {
            self.num.map(|v| v)
        }
        pub fn set_num(&mut self, v: i32) {
            self.cached_size.dirty();
            self.num = Some(v);
        }
        pub fn clear_num(&mut self) {
            self.cached_size.dirty();
            self.num = None;
        }
        #[inline(always)]
        fn check_required(&self) -> Result<(), ParseError> {
            Ok(())
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return self.check_required();
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return Ok(());
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(data, wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    1 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            self.num = Some(pbrs::rt::decode_varint(data, pos)? as i32);
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    _ => self
                        .unknown
                        .fields
                        .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            if enforce {
                self.check_required()?;
            }
            Ok(())
        }
        fn validate_inner(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
        ) -> Result<(), ParseError> {
            Self::validate_until(wire, pos, depth, None)
        }
        fn validate_until(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    1 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_varint(data, pos)? as i32;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    _ => pbrs::rt::skip_field(data, pos, w)?,
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            if let Some(v) = self.num {
                n += pbrs::rt::tag_len(1, pbrs::rt::WIRE_VARINT) + pbrs::rt::varint_len((v) as u64);
            }
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut Vec<u8>) {
            if let Some(v) = self.num {
                pbrs::rt::encode_tag(out, 1, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, v as u64);
            }
            self.unknown.encode(out);
        }
    }
    pbrs::impl_typed_message!(ImportedMessage, ImportedMessageView, ImportedMessageMut);
    #[derive(Clone, Debug)]
    pub struct ImportedTypesProto {
        unknown: UnknownFields,
        cached_size: pbrs::rt::CachedSize,
    }
    impl PartialEq for ImportedTypesProto {
        fn eq(&self, other: &Self) -> bool {
            self.unknown == other.unknown
        }
    }
    impl Eq for ImportedTypesProto {}
    impl Default for ImportedTypesProto {
        #[inline(always)]
        fn default() -> Self {
            unsafe { pbrs::rt::zeroed_message() }
        }
    }
    impl ImportedTypesProto {
        pub fn new() -> Self {
            Self::default()
        }
        pub const EMPTY_PARSE_OK: bool = true;
        pub const FULL_NAME: &'static str = "main.ImportedTypesProto";
        #[inline(always)]
        fn check_required(&self) -> Result<(), ParseError> {
            Ok(())
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return self.check_required();
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return Ok(());
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(data, wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    _ => self
                        .unknown
                        .fields
                        .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            if enforce {
                self.check_required()?;
            }
            Ok(())
        }
        fn validate_inner(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
        ) -> Result<(), ParseError> {
            Self::validate_until(wire, pos, depth, None)
        }
        fn validate_until(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    _ => pbrs::rt::skip_field(data, pos, w)?,
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut Vec<u8>) {
            self.unknown.encode(out);
        }
    }
    pbrs::impl_typed_message!(
        ImportedTypesProto,
        ImportedTypesProtoView,
        ImportedTypesProtoMut
    );
    #[derive(Clone, Debug)]
    pub struct Nested {
        unknown: UnknownFields,
        cached_size: pbrs::rt::CachedSize,
    }
    impl PartialEq for Nested {
        fn eq(&self, other: &Self) -> bool {
            self.unknown == other.unknown
        }
    }
    impl Eq for Nested {}
    impl Default for Nested {
        #[inline(always)]
        fn default() -> Self {
            unsafe { pbrs::rt::zeroed_message() }
        }
    }
    impl Nested {
        pub fn new() -> Self {
            Self::default()
        }
        pub const EMPTY_PARSE_OK: bool = true;
        pub const FULL_NAME: &'static str = "main.ImportedTypesProto.Nested";
        #[inline(always)]
        fn check_required(&self) -> Result<(), ParseError> {
            Ok(())
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return self.check_required();
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return Ok(());
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(data, wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    _ => self
                        .unknown
                        .fields
                        .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            if enforce {
                self.check_required()?;
            }
            Ok(())
        }
        fn validate_inner(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
        ) -> Result<(), ParseError> {
            Self::validate_until(wire, pos, depth, None)
        }
        fn validate_until(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    _ => pbrs::rt::skip_field(data, pos, w)?,
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut Vec<u8>) {
            self.unknown.encode(out);
        }
    }
    pbrs::impl_typed_message!(Nested, NestedView, NestedMut);
    #[derive(Clone, Debug)]
    pub struct MsgWithFieldsWithImportedTypes {
        imported_message_field: pbrs::rt::LazyMsg<ImportedMessage>,
        imported_enum_field: Option<i32>,
        imported_message_oneof: pbrs::rt::LazyMsg<ImportedMessage>,
        imported_enum_oneof: Option<i32>,
        unknown: UnknownFields,
        cached_size: pbrs::rt::CachedSize,
    }
    impl PartialEq for MsgWithFieldsWithImportedTypes {
        fn eq(&self, other: &Self) -> bool {
            if self.imported_message_field != other.imported_message_field {
                return false;
            }
            if self.imported_enum_field != other.imported_enum_field {
                return false;
            }
            if self.imported_message_oneof != other.imported_message_oneof {
                return false;
            }
            if self.imported_enum_oneof != other.imported_enum_oneof {
                return false;
            }
            self.unknown == other.unknown
        }
    }
    impl Eq for MsgWithFieldsWithImportedTypes {}
    impl Default for MsgWithFieldsWithImportedTypes {
        #[inline(always)]
        fn default() -> Self {
            unsafe { pbrs::rt::zeroed_message() }
        }
    }
    impl MsgWithFieldsWithImportedTypes {
        pub fn new() -> Self {
            Self::default()
        }
        pub const EMPTY_PARSE_OK: bool = true;
        pub const FULL_NAME: &'static str = "main.MsgWithFieldsWithImportedTypes";
        pub fn has_imported_message_field(&self) -> bool {
            self.imported_message_field.is_some()
        }
        pub fn imported_message_field(&self) -> &ImportedMessage {
            self.imported_message_field
                .as_deref()
                .unwrap_or(pbrs::gen_support::default_instance_of())
        }
        pub fn imported_message_field_opt(&self) -> Option<&ImportedMessage> {
            self.imported_message_field.as_deref()
        }
        pub fn imported_message_field_view(&self) -> ImportedMessageView<'_> {
            ImportedMessageView(self.imported_message_field())
        }
        pub fn set_imported_message_field(&mut self, v: ImportedMessage) {
            self.cached_size.dirty();
            self.imported_message_field = pbrs::rt::LazyMsg::from_owned(v);
        }
        pub fn imported_message_field_mut(&mut self) -> &mut ImportedMessage {
            self.cached_size.dirty();
            self.imported_message_field.get_or_insert()
        }
        pub fn clear_imported_message_field(&mut self) {
            self.cached_size.dirty();
            self.imported_message_field.clear();
        }
        pub fn has_imported_enum_field(&self) -> bool {
            self.imported_enum_field.is_some()
        }
        pub fn imported_enum_field(&self) -> ImportedEnum {
            ImportedEnum(self.imported_enum_field.unwrap_or(0))
        }
        pub fn imported_enum_field_opt(&self) -> Option<ImportedEnum> {
            self.imported_enum_field.map(|v| ImportedEnum(v))
        }
        pub fn set_imported_enum_field(&mut self, v: impl Into<i32>) {
            self.cached_size.dirty();
            self.imported_enum_field = Some(v.into());
        }
        pub fn clear_imported_enum_field(&mut self) {
            self.cached_size.dirty();
            self.imported_enum_field = None;
        }
        pub fn has_imported_message_oneof(&self) -> bool {
            self.imported_message_oneof.is_some()
        }
        pub fn imported_message_oneof(&self) -> &ImportedMessage {
            self.imported_message_oneof
                .as_deref()
                .unwrap_or(pbrs::gen_support::default_instance_of())
        }
        pub fn imported_message_oneof_opt(&self) -> Option<&ImportedMessage> {
            self.imported_message_oneof.as_deref()
        }
        pub fn imported_message_oneof_view(&self) -> ImportedMessageView<'_> {
            ImportedMessageView(self.imported_message_oneof())
        }
        pub fn set_imported_message_oneof(&mut self, v: ImportedMessage) {
            self.cached_size.dirty();
            self.imported_enum_oneof = None;
            self.imported_message_oneof = pbrs::rt::LazyMsg::from_owned(v);
        }
        pub fn imported_message_oneof_mut(&mut self) -> &mut ImportedMessage {
            self.cached_size.dirty();
            self.imported_message_oneof.get_or_insert()
        }
        pub fn clear_imported_message_oneof(&mut self) {
            self.cached_size.dirty();
            self.imported_message_oneof.clear();
        }
        pub fn has_imported_enum_oneof(&self) -> bool {
            self.imported_enum_oneof.is_some()
        }
        pub fn imported_enum_oneof(&self) -> ImportedEnum {
            ImportedEnum(self.imported_enum_oneof.unwrap_or(0))
        }
        pub fn imported_enum_oneof_opt(&self) -> Option<ImportedEnum> {
            self.imported_enum_oneof.map(|v| ImportedEnum(v))
        }
        pub fn set_imported_enum_oneof(&mut self, v: impl Into<i32>) {
            self.cached_size.dirty();
            self.imported_message_oneof = Default::default();
            self.imported_enum_oneof = Some(v.into());
        }
        pub fn clear_imported_enum_oneof(&mut self) {
            self.cached_size.dirty();
            self.imported_enum_oneof = None;
        }
        #[inline(always)]
        fn check_required(&self) -> Result<(), ParseError> {
            Ok(())
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return self.check_required();
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return Ok(());
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(data, wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    1 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            if self.imported_message_field.is_some() {
                                let mut ip = 0;
                                let mut sw = None;
                                self.imported_message_field.get_or_insert().merge_inner(
                                    &data[s..e],
                                    &mut sw,
                                    &mut ip,
                                    depth + 1,
                                    true,
                                    None,
                                )?;
                            } else {
                                let mut ip = 0;
                                ImportedMessage::validate_inner(
                                    &pbrs::rt::Wire::ensure(wire, data).window(s, e),
                                    &mut ip,
                                    depth + 1,
                                )?;
                                self.imported_message_field = pbrs::rt::LazyMsg::from_wire(
                                    pbrs::rt::Wire::ensure(wire, data).window(s, e),
                                );
                            }
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    2 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            self.imported_enum_field =
                                Some(pbrs::rt::decode_varint(data, pos)? as i32);
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    3 => match w {
                        pbrs::rt::WIRE_LEN => {
                            self.imported_enum_oneof = None;
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            if self.imported_message_oneof.is_some() {
                                let mut ip = 0;
                                let mut sw = None;
                                self.imported_message_oneof.get_or_insert().merge_inner(
                                    &data[s..e],
                                    &mut sw,
                                    &mut ip,
                                    depth + 1,
                                    true,
                                    None,
                                )?;
                            } else {
                                let mut ip = 0;
                                ImportedMessage::validate_inner(
                                    &pbrs::rt::Wire::ensure(wire, data).window(s, e),
                                    &mut ip,
                                    depth + 1,
                                )?;
                                self.imported_message_oneof = pbrs::rt::LazyMsg::from_wire(
                                    pbrs::rt::Wire::ensure(wire, data).window(s, e),
                                );
                            }
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    4 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            self.imported_message_oneof = Default::default();
                            self.imported_enum_oneof =
                                Some(pbrs::rt::decode_varint(data, pos)? as i32);
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    _ => self
                        .unknown
                        .fields
                        .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            if enforce {
                self.check_required()?;
            }
            Ok(())
        }
        fn validate_inner(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
        ) -> Result<(), ParseError> {
            Self::validate_until(wire, pos, depth, None)
        }
        fn validate_until(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    1 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            let mut ip = 0;
                            ImportedMessage::validate_inner(
                                &wire.window(s, e),
                                &mut ip,
                                depth + 1,
                            )?;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    2 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_varint(data, pos)? as i32;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    3 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            let mut ip = 0;
                            ImportedMessage::validate_inner(
                                &wire.window(s, e),
                                &mut ip,
                                depth + 1,
                            )?;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    4 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_varint(data, pos)? as i32;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    _ => pbrs::rt::skip_field(data, pos, w)?,
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            if let Some(p) = self.imported_message_field.wire_bytes() {
                n += pbrs::rt::key_len_value_len(1, p.len() as u64);
            } else if let Some(m) = self.imported_message_field.as_deref() {
                n += pbrs::rt::key_len_value_len(1, m.compute_size());
            }
            if let Some(v) = self.imported_enum_field {
                n += pbrs::rt::tag_len(2, pbrs::rt::WIRE_VARINT) + pbrs::rt::varint_len((v) as u64);
            }
            if let Some(p) = self.imported_message_oneof.wire_bytes() {
                n += pbrs::rt::key_len_value_len(3, p.len() as u64);
            } else if let Some(m) = self.imported_message_oneof.as_deref() {
                n += pbrs::rt::key_len_value_len(3, m.compute_size());
            }
            if let Some(v) = self.imported_enum_oneof {
                n += pbrs::rt::tag_len(4, pbrs::rt::WIRE_VARINT) + pbrs::rt::varint_len((v) as u64);
            }
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut Vec<u8>) {
            if let Some(p) = self.imported_message_field.wire_bytes() {
                pbrs::rt::encode_len_header(out, 1, p.len() as u64);
                out.extend_from_slice(p);
            } else if let Some(m) = self.imported_message_field.as_deref() {
                pbrs::rt::encode_len_header(out, 1, m.compute_size());
                m.write_to(out);
            }
            if let Some(v) = self.imported_enum_field {
                pbrs::rt::encode_tag(out, 2, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, v as u64);
            }
            if let Some(p) = self.imported_message_oneof.wire_bytes() {
                pbrs::rt::encode_len_header(out, 3, p.len() as u64);
                out.extend_from_slice(p);
            } else if let Some(m) = self.imported_message_oneof.as_deref() {
                pbrs::rt::encode_len_header(out, 3, m.compute_size());
                m.write_to(out);
            }
            if let Some(v) = self.imported_enum_oneof {
                pbrs::rt::encode_tag(out, 4, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, v as u64);
            }
            self.unknown.encode(out);
        }
    }
    pbrs::impl_typed_message!(
        MsgWithFieldsWithImportedTypes,
        MsgWithFieldsWithImportedTypesView,
        MsgWithFieldsWithImportedTypesMut
    );
    pub mod imported_types_proto {
        pub use super::Nested;
    }
}
#[allow(unused_imports)]
pub use __gen::*;
