// @generated by protoc-gen-pbrs
#[allow(unused, non_snake_case, non_camel_case_types, clippy::all)]
mod __gen {
    #![allow(unused, non_snake_case, non_camel_case_types, clippy::all)]
    use protobuf::prelude::*;
    use protobuf::UnknownFields;
    use protobuf::{
        Enum, Map, MapMut, MapView, ParseError, ProtoBytes, ProtoString, Repeated, RepeatedMut,
        RepeatedView, SerializeError, UnknownEnumValue,
    };

    #[derive(Clone, Debug)]
    pub struct NoFeaturesProto2 {
        my_field: Option<Box<protobuf::rt::LazyStr>>,
        unknown: UnknownFields,
        cached_size: protobuf::rt::CachedSize,
    }
    impl PartialEq for NoFeaturesProto2 {
        fn eq(&self, other: &Self) -> bool {
            if self.my_field != other.my_field {
                return false;
            }
            self.unknown == other.unknown
        }
    }
    impl Eq for NoFeaturesProto2 {}
    impl Default for NoFeaturesProto2 {
        #[inline(always)]
        fn default() -> Self {
            unsafe { protobuf::rt::zeroed_message() }
        }
    }
    impl NoFeaturesProto2 {
        pub fn new() -> Self {
            Self::default()
        }
        pub const EMPTY_PARSE_OK: bool = true;
        pub const FULL_NAME: &'static str = "utf8.NoFeaturesProto2";
        pub fn has_my_field(&self) -> bool {
            self.my_field.is_some()
        }
        pub fn my_field(&self) -> &protobuf::ProtoStr {
            self.my_field
                .as_ref()
                .map(|s| s.as_view())
                .unwrap_or_else(|| protobuf::ProtoStr::from_bytes(b""))
        }
        pub fn my_field_opt(&self) -> Option<&protobuf::ProtoStr> {
            self.my_field.as_ref().map(|s| s.as_view())
        }
        pub fn set_my_field(&mut self, v: impl protobuf::IntoProxied<ProtoString>) {
            self.cached_size.dirty();
            self.my_field = Some(Box::new(protobuf::rt::LazyStr::owned(v.into_proxied())));
        }
        pub fn clear_my_field(&mut self) {
            self.cached_size.dirty();
            self.my_field = None;
        }
        #[inline(always)]
        fn check_required(&self) -> Result<(), ParseError> {
            Ok(())
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return self.check_required();
            }
            let w = protobuf::rt::Wire::from_slice(data);
            let mut pos = 0;
            self.merge_inner(&w, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return Ok(());
            }
            let w = protobuf::rt::Wire::from_slice(data);
            let mut pos = 0;
            self.merge_inner(&w, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            wire: &protobuf::rt::Wire,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            wire: &protobuf::rt::Wire,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > protobuf::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = protobuf::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == protobuf::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    1 => match w {
                        protobuf::rt::WIRE_LEN => {
                            let (s, e) = protobuf::rt::read_len_span(data, pos)?;
                            let b = &data[s..e];
                            self.my_field =
                                Some(Box::new(protobuf::rt::LazyStr::from_span(wire, s, e)));
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(protobuf::rt::capture_unknown(data, pos, n, w)?),
                    },
                    _ => self
                        .unknown
                        .fields
                        .push(protobuf::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            if enforce {
                self.check_required()?;
            }
            Ok(())
        }
        fn validate_inner(
            wire: &protobuf::rt::Wire,
            pos: &mut usize,
            depth: u32,
        ) -> Result<(), ParseError> {
            Self::validate_until(wire, pos, depth, None)
        }
        fn validate_until(
            wire: &protobuf::rt::Wire,
            pos: &mut usize,
            depth: u32,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > protobuf::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = protobuf::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == protobuf::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    1 => match w {
                        protobuf::rt::WIRE_LEN => {
                            let (s, e) = protobuf::rt::read_len_span(data, pos)?;
                        }
                        _ => protobuf::rt::skip_field(data, pos, w)?,
                    },
                    _ => protobuf::rt::skip_field(data, pos, w)?,
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            if let Some(s) = &self.my_field {
                n += protobuf::rt::key_len_value_len(1, s.as_bytes().len() as u64);
            }
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut Vec<u8>) {
            if let Some(s) = &self.my_field {
                protobuf::rt::encode_len_field(out, 1, s.as_bytes());
            }
            self.unknown.encode(out);
        }
    }
    protobuf::impl_typed_message!(NoFeaturesProto2, NoFeaturesProto2View, NoFeaturesProto2Mut);
    #[derive(Clone, Debug)]
    pub struct NoFeaturesProto3 {
        my_field: Option<Box<protobuf::rt::LazyStr>>,
        unknown: UnknownFields,
        cached_size: protobuf::rt::CachedSize,
    }
    impl PartialEq for NoFeaturesProto3 {
        fn eq(&self, other: &Self) -> bool {
            if self.my_field != other.my_field {
                return false;
            }
            self.unknown == other.unknown
        }
    }
    impl Eq for NoFeaturesProto3 {}
    impl Default for NoFeaturesProto3 {
        #[inline(always)]
        fn default() -> Self {
            unsafe { protobuf::rt::zeroed_message() }
        }
    }
    impl NoFeaturesProto3 {
        pub fn new() -> Self {
            Self::default()
        }
        pub const EMPTY_PARSE_OK: bool = true;
        pub const FULL_NAME: &'static str = "utf8.NoFeaturesProto3";
        pub fn has_my_field(&self) -> bool {
            self.my_field.is_some()
        }
        pub fn my_field(&self) -> &protobuf::ProtoStr {
            self.my_field
                .as_ref()
                .map(|s| s.as_view())
                .unwrap_or_else(|| protobuf::ProtoStr::from_bytes(b""))
        }
        pub fn my_field_opt(&self) -> Option<&protobuf::ProtoStr> {
            self.my_field.as_ref().map(|s| s.as_view())
        }
        pub fn set_my_field(&mut self, v: impl protobuf::IntoProxied<ProtoString>) {
            self.cached_size.dirty();
            self.my_field = Some(Box::new(protobuf::rt::LazyStr::owned(v.into_proxied())));
        }
        pub fn clear_my_field(&mut self) {
            self.cached_size.dirty();
            self.my_field = None;
        }
        #[inline(always)]
        fn check_required(&self) -> Result<(), ParseError> {
            Ok(())
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return self.check_required();
            }
            let w = protobuf::rt::Wire::from_slice(data);
            let mut pos = 0;
            self.merge_inner(&w, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return Ok(());
            }
            let w = protobuf::rt::Wire::from_slice(data);
            let mut pos = 0;
            self.merge_inner(&w, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            wire: &protobuf::rt::Wire,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            wire: &protobuf::rt::Wire,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > protobuf::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = protobuf::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == protobuf::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    1 => match w {
                        protobuf::rt::WIRE_LEN => {
                            let (s, e) = protobuf::rt::read_len_span(data, pos)?;
                            let b = &data[s..e];
                            std::str::from_utf8(b).map_err(|_| ParseError::new("invalid utf-8"))?;
                            self.my_field =
                                Some(Box::new(protobuf::rt::LazyStr::from_span(wire, s, e)));
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(protobuf::rt::capture_unknown(data, pos, n, w)?),
                    },
                    _ => self
                        .unknown
                        .fields
                        .push(protobuf::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            if enforce {
                self.check_required()?;
            }
            Ok(())
        }
        fn validate_inner(
            wire: &protobuf::rt::Wire,
            pos: &mut usize,
            depth: u32,
        ) -> Result<(), ParseError> {
            Self::validate_until(wire, pos, depth, None)
        }
        fn validate_until(
            wire: &protobuf::rt::Wire,
            pos: &mut usize,
            depth: u32,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > protobuf::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = protobuf::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == protobuf::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    1 => match w {
                        protobuf::rt::WIRE_LEN => {
                            let (s, e) = protobuf::rt::read_len_span(data, pos)?;
                            std::str::from_utf8(&data[s..e])
                                .map_err(|_| ParseError::new("invalid utf-8"))?;
                        }
                        _ => protobuf::rt::skip_field(data, pos, w)?,
                    },
                    _ => protobuf::rt::skip_field(data, pos, w)?,
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            if let Some(s) = &self.my_field {
                n += protobuf::rt::key_len_value_len(1, s.as_bytes().len() as u64);
            }
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut Vec<u8>) {
            if let Some(s) = &self.my_field {
                protobuf::rt::encode_len_field(out, 1, s.as_bytes());
            }
            self.unknown.encode(out);
        }
    }
    protobuf::impl_typed_message!(NoFeaturesProto3, NoFeaturesProto3View, NoFeaturesProto3Mut);
    #[derive(Clone, Debug)]
    pub struct Verify {
        my_field: Option<Box<protobuf::rt::LazyStr>>,
        unknown: UnknownFields,
        cached_size: protobuf::rt::CachedSize,
    }
    impl PartialEq for Verify {
        fn eq(&self, other: &Self) -> bool {
            if self.my_field != other.my_field {
                return false;
            }
            self.unknown == other.unknown
        }
    }
    impl Eq for Verify {}
    impl Default for Verify {
        #[inline(always)]
        fn default() -> Self {
            unsafe { protobuf::rt::zeroed_message() }
        }
    }
    impl Verify {
        pub fn new() -> Self {
            Self::default()
        }
        pub const EMPTY_PARSE_OK: bool = true;
        pub const FULL_NAME: &'static str = "utf8.Verify";
        pub fn has_my_field(&self) -> bool {
            self.my_field.is_some()
        }
        pub fn my_field(&self) -> &protobuf::ProtoStr {
            self.my_field
                .as_ref()
                .map(|s| s.as_view())
                .unwrap_or_else(|| protobuf::ProtoStr::from_bytes(b""))
        }
        pub fn my_field_opt(&self) -> Option<&protobuf::ProtoStr> {
            self.my_field.as_ref().map(|s| s.as_view())
        }
        pub fn set_my_field(&mut self, v: impl protobuf::IntoProxied<ProtoString>) {
            self.cached_size.dirty();
            self.my_field = Some(Box::new(protobuf::rt::LazyStr::owned(v.into_proxied())));
        }
        pub fn clear_my_field(&mut self) {
            self.cached_size.dirty();
            self.my_field = None;
        }
        #[inline(always)]
        fn check_required(&self) -> Result<(), ParseError> {
            Ok(())
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return self.check_required();
            }
            let w = protobuf::rt::Wire::from_slice(data);
            let mut pos = 0;
            self.merge_inner(&w, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return Ok(());
            }
            let w = protobuf::rt::Wire::from_slice(data);
            let mut pos = 0;
            self.merge_inner(&w, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            wire: &protobuf::rt::Wire,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            wire: &protobuf::rt::Wire,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > protobuf::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = protobuf::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == protobuf::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    1 => match w {
                        protobuf::rt::WIRE_LEN => {
                            let (s, e) = protobuf::rt::read_len_span(data, pos)?;
                            let b = &data[s..e];
                            std::str::from_utf8(b).map_err(|_| ParseError::new("invalid utf-8"))?;
                            self.my_field =
                                Some(Box::new(protobuf::rt::LazyStr::from_span(wire, s, e)));
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(protobuf::rt::capture_unknown(data, pos, n, w)?),
                    },
                    _ => self
                        .unknown
                        .fields
                        .push(protobuf::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            if enforce {
                self.check_required()?;
            }
            Ok(())
        }
        fn validate_inner(
            wire: &protobuf::rt::Wire,
            pos: &mut usize,
            depth: u32,
        ) -> Result<(), ParseError> {
            Self::validate_until(wire, pos, depth, None)
        }
        fn validate_until(
            wire: &protobuf::rt::Wire,
            pos: &mut usize,
            depth: u32,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > protobuf::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = protobuf::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == protobuf::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    1 => match w {
                        protobuf::rt::WIRE_LEN => {
                            let (s, e) = protobuf::rt::read_len_span(data, pos)?;
                            std::str::from_utf8(&data[s..e])
                                .map_err(|_| ParseError::new("invalid utf-8"))?;
                        }
                        _ => protobuf::rt::skip_field(data, pos, w)?,
                    },
                    _ => protobuf::rt::skip_field(data, pos, w)?,
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            if let Some(s) = &self.my_field {
                n += protobuf::rt::key_len_value_len(1, s.as_bytes().len() as u64);
            }
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut Vec<u8>) {
            if let Some(s) = &self.my_field {
                protobuf::rt::encode_len_field(out, 1, s.as_bytes());
            }
            self.unknown.encode(out);
        }
    }
    protobuf::impl_typed_message!(Verify, VerifyView, VerifyMut);
}
#[allow(unused_imports)]
pub use __gen::*;
