// @generated by protoc-gen-pbrs
#[allow(unused, non_snake_case, non_camel_case_types, clippy::all)]
mod __gen {
    #![allow(unused, non_snake_case, non_camel_case_types, clippy::all)]
    use pbrs::prelude::*;
    use pbrs::UnknownFields;
    use pbrs::{
        Enum, Map, MapMut, MapView, ParseError, ProtoBytes, ProtoString, Repeated, RepeatedMut,
        RepeatedView, SerializeError, UnknownEnumValue,
    };

    #[repr(transparent)]
    #[derive(Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
    pub struct NestedEnum(i32);
    #[allow(non_upper_case_globals)]
    impl NestedEnum {
        pub const Unspecified: NestedEnum = NestedEnum(0);
        pub const Foo: NestedEnum = NestedEnum(1);
        pub const Bar: NestedEnum = NestedEnum(2);
        pub const Baz: NestedEnum = NestedEnum(3);
        pub const Neg: NestedEnum = NestedEnum(-1);
        fn constant_name(self) -> Option<&'static str> {
            #[allow(unreachable_patterns)]
            Some(match self.0 {
                0 => "Unspecified",
                1 => "Foo",
                2 => "Bar",
                3 => "Baz",
                -1 => "Neg",
                _ => return None,
            })
        }
    }
    impl From<NestedEnum> for i32 {
        fn from(v: NestedEnum) -> i32 {
            v.0
        }
    }
    impl From<i32> for NestedEnum {
        fn from(val: i32) -> Self {
            Self(val)
        }
    }
    impl Default for NestedEnum {
        fn default() -> Self {
            Self(0)
        }
    }
    impl std::fmt::Debug for NestedEnum {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            if let Some(n) = self.constant_name() {
                write!(f, "NestedEnum::{n}")
            } else {
                write!(f, "NestedEnum::from({})", self.0)
            }
        }
    }
    impl pbrs::__internal::SealedInternal for NestedEnum {}
    impl pbrs::Proxied for NestedEnum {
        type View<'msg> = NestedEnum;
    }
    impl pbrs::AsView for NestedEnum {
        type Proxied = Self;
        fn as_view(&self) -> Self {
            *self
        }
    }
    impl<'msg> pbrs::IntoView<'msg> for NestedEnum {
        fn into_view<'shorter>(self) -> Self
        where
            'msg: 'shorter,
        {
            self
        }
    }
    impl Enum for NestedEnum {
        const NAME: &'static str = "NestedEnum";
        fn is_known(value: i32) -> bool {
            matches!(value, 0 | 1 | 2 | 3 | -1)
        }
    }
    #[derive(Clone, Debug)]
    pub struct TestProto3Optional {
        optional_int32: Option<i32>,
        optional_int64: Option<i64>,
        optional_uint32: Option<u32>,
        optional_uint64: Option<u64>,
        optional_sint32: Option<i32>,
        optional_sint64: Option<i64>,
        optional_fixed32: Option<u32>,
        optional_fixed64: Option<u64>,
        optional_sfixed32: Option<i32>,
        optional_sfixed64: Option<i64>,
        optional_float: Option<f32>,
        optional_double: Option<f64>,
        optional_bool: pbrs::rt::OptBool,
        optional_string: Option<Box<pbrs::rt::LazyStr>>,
        optional_bytes: Option<Box<pbrs::rt::LazyBytes>>,
        optional_cord: Option<Box<pbrs::rt::LazyStr>>,
        optional_nested_message: pbrs::rt::LazyMsg<NestedMessage>,
        lazy_nested_message: pbrs::rt::LazyMsg<NestedMessage>,
        optional_nested_enum: Option<i32>,
        singular_int32: i32,
        singular_int64: i64,
        unknown: UnknownFields,
        cached_size: pbrs::rt::CachedSize,
    }
    impl PartialEq for TestProto3Optional {
        fn eq(&self, other: &Self) -> bool {
            if self.optional_int32 != other.optional_int32 {
                return false;
            }
            if self.optional_int64 != other.optional_int64 {
                return false;
            }
            if self.optional_uint32 != other.optional_uint32 {
                return false;
            }
            if self.optional_uint64 != other.optional_uint64 {
                return false;
            }
            if self.optional_sint32 != other.optional_sint32 {
                return false;
            }
            if self.optional_sint64 != other.optional_sint64 {
                return false;
            }
            if self.optional_fixed32 != other.optional_fixed32 {
                return false;
            }
            if self.optional_fixed64 != other.optional_fixed64 {
                return false;
            }
            if self.optional_sfixed32 != other.optional_sfixed32 {
                return false;
            }
            if self.optional_sfixed64 != other.optional_sfixed64 {
                return false;
            }
            if self.optional_float != other.optional_float {
                return false;
            }
            if self.optional_double != other.optional_double {
                return false;
            }
            if self.optional_bool != other.optional_bool {
                return false;
            }
            if self.optional_string != other.optional_string {
                return false;
            }
            if self.optional_bytes != other.optional_bytes {
                return false;
            }
            if self.optional_cord != other.optional_cord {
                return false;
            }
            if self.optional_nested_message != other.optional_nested_message {
                return false;
            }
            if self.lazy_nested_message != other.lazy_nested_message {
                return false;
            }
            if self.optional_nested_enum != other.optional_nested_enum {
                return false;
            }
            if self.singular_int32 != other.singular_int32 {
                return false;
            }
            if self.singular_int64 != other.singular_int64 {
                return false;
            }
            self.unknown == other.unknown
        }
    }
    impl Eq for TestProto3Optional {}
    impl Default for TestProto3Optional {
        #[inline(always)]
        fn default() -> Self {
            unsafe { pbrs::rt::zeroed_message() }
        }
    }
    impl TestProto3Optional {
        pub fn new() -> Self {
            Self::default()
        }
        pub const EMPTY_PARSE_OK: bool = true;
        pub const FULL_NAME: &'static str = "rust_unittest_proto3_optional.TestProto3Optional";
        pub fn has_optional_int32(&self) -> bool {
            self.optional_int32.is_some()
        }
        pub fn optional_int32(&self) -> i32 {
            self.optional_int32.unwrap_or(0)
        }
        pub fn optional_int32_opt(&self) -> Option<i32> {
            self.optional_int32.map(|v| v)
        }
        pub fn set_optional_int32(&mut self, v: i32) {
            self.cached_size.dirty();
            self.optional_int32 = Some(v);
        }
        pub fn clear_optional_int32(&mut self) {
            self.cached_size.dirty();
            self.optional_int32 = None;
        }
        pub fn has_optional_int64(&self) -> bool {
            self.optional_int64.is_some()
        }
        pub fn optional_int64(&self) -> i64 {
            self.optional_int64.unwrap_or(0)
        }
        pub fn optional_int64_opt(&self) -> Option<i64> {
            self.optional_int64.map(|v| v)
        }
        pub fn set_optional_int64(&mut self, v: i64) {
            self.cached_size.dirty();
            self.optional_int64 = Some(v);
        }
        pub fn clear_optional_int64(&mut self) {
            self.cached_size.dirty();
            self.optional_int64 = None;
        }
        pub fn has_optional_uint32(&self) -> bool {
            self.optional_uint32.is_some()
        }
        pub fn optional_uint32(&self) -> u32 {
            self.optional_uint32.unwrap_or(0)
        }
        pub fn optional_uint32_opt(&self) -> Option<u32> {
            self.optional_uint32.map(|v| v)
        }
        pub fn set_optional_uint32(&mut self, v: u32) {
            self.cached_size.dirty();
            self.optional_uint32 = Some(v);
        }
        pub fn clear_optional_uint32(&mut self) {
            self.cached_size.dirty();
            self.optional_uint32 = None;
        }
        pub fn has_optional_uint64(&self) -> bool {
            self.optional_uint64.is_some()
        }
        pub fn optional_uint64(&self) -> u64 {
            self.optional_uint64.unwrap_or(0)
        }
        pub fn optional_uint64_opt(&self) -> Option<u64> {
            self.optional_uint64.map(|v| v)
        }
        pub fn set_optional_uint64(&mut self, v: u64) {
            self.cached_size.dirty();
            self.optional_uint64 = Some(v);
        }
        pub fn clear_optional_uint64(&mut self) {
            self.cached_size.dirty();
            self.optional_uint64 = None;
        }
        pub fn has_optional_sint32(&self) -> bool {
            self.optional_sint32.is_some()
        }
        pub fn optional_sint32(&self) -> i32 {
            self.optional_sint32.unwrap_or(0)
        }
        pub fn optional_sint32_opt(&self) -> Option<i32> {
            self.optional_sint32.map(|v| v)
        }
        pub fn set_optional_sint32(&mut self, v: i32) {
            self.cached_size.dirty();
            self.optional_sint32 = Some(v);
        }
        pub fn clear_optional_sint32(&mut self) {
            self.cached_size.dirty();
            self.optional_sint32 = None;
        }
        pub fn has_optional_sint64(&self) -> bool {
            self.optional_sint64.is_some()
        }
        pub fn optional_sint64(&self) -> i64 {
            self.optional_sint64.unwrap_or(0)
        }
        pub fn optional_sint64_opt(&self) -> Option<i64> {
            self.optional_sint64.map(|v| v)
        }
        pub fn set_optional_sint64(&mut self, v: i64) {
            self.cached_size.dirty();
            self.optional_sint64 = Some(v);
        }
        pub fn clear_optional_sint64(&mut self) {
            self.cached_size.dirty();
            self.optional_sint64 = None;
        }
        pub fn has_optional_fixed32(&self) -> bool {
            self.optional_fixed32.is_some()
        }
        pub fn optional_fixed32(&self) -> u32 {
            self.optional_fixed32.unwrap_or(0)
        }
        pub fn optional_fixed32_opt(&self) -> Option<u32> {
            self.optional_fixed32.map(|v| v)
        }
        pub fn set_optional_fixed32(&mut self, v: u32) {
            self.cached_size.dirty();
            self.optional_fixed32 = Some(v);
        }
        pub fn clear_optional_fixed32(&mut self) {
            self.cached_size.dirty();
            self.optional_fixed32 = None;
        }
        pub fn has_optional_fixed64(&self) -> bool {
            self.optional_fixed64.is_some()
        }
        pub fn optional_fixed64(&self) -> u64 {
            self.optional_fixed64.unwrap_or(0)
        }
        pub fn optional_fixed64_opt(&self) -> Option<u64> {
            self.optional_fixed64.map(|v| v)
        }
        pub fn set_optional_fixed64(&mut self, v: u64) {
            self.cached_size.dirty();
            self.optional_fixed64 = Some(v);
        }
        pub fn clear_optional_fixed64(&mut self) {
            self.cached_size.dirty();
            self.optional_fixed64 = None;
        }
        pub fn has_optional_sfixed32(&self) -> bool {
            self.optional_sfixed32.is_some()
        }
        pub fn optional_sfixed32(&self) -> i32 {
            self.optional_sfixed32.unwrap_or(0)
        }
        pub fn optional_sfixed32_opt(&self) -> Option<i32> {
            self.optional_sfixed32.map(|v| v)
        }
        pub fn set_optional_sfixed32(&mut self, v: i32) {
            self.cached_size.dirty();
            self.optional_sfixed32 = Some(v);
        }
        pub fn clear_optional_sfixed32(&mut self) {
            self.cached_size.dirty();
            self.optional_sfixed32 = None;
        }
        pub fn has_optional_sfixed64(&self) -> bool {
            self.optional_sfixed64.is_some()
        }
        pub fn optional_sfixed64(&self) -> i64 {
            self.optional_sfixed64.unwrap_or(0)
        }
        pub fn optional_sfixed64_opt(&self) -> Option<i64> {
            self.optional_sfixed64.map(|v| v)
        }
        pub fn set_optional_sfixed64(&mut self, v: i64) {
            self.cached_size.dirty();
            self.optional_sfixed64 = Some(v);
        }
        pub fn clear_optional_sfixed64(&mut self) {
            self.cached_size.dirty();
            self.optional_sfixed64 = None;
        }
        pub fn has_optional_float(&self) -> bool {
            self.optional_float.is_some()
        }
        pub fn optional_float(&self) -> f32 {
            self.optional_float.unwrap_or(0.0)
        }
        pub fn optional_float_opt(&self) -> Option<f32> {
            self.optional_float.map(|v| v)
        }
        pub fn set_optional_float(&mut self, v: f32) {
            self.cached_size.dirty();
            self.optional_float = Some(v);
        }
        pub fn clear_optional_float(&mut self) {
            self.cached_size.dirty();
            self.optional_float = None;
        }
        pub fn has_optional_double(&self) -> bool {
            self.optional_double.is_some()
        }
        pub fn optional_double(&self) -> f64 {
            self.optional_double.unwrap_or(0.0)
        }
        pub fn optional_double_opt(&self) -> Option<f64> {
            self.optional_double.map(|v| v)
        }
        pub fn set_optional_double(&mut self, v: f64) {
            self.cached_size.dirty();
            self.optional_double = Some(v);
        }
        pub fn clear_optional_double(&mut self) {
            self.cached_size.dirty();
            self.optional_double = None;
        }
        pub fn has_optional_bool(&self) -> bool {
            self.optional_bool.is_some()
        }
        pub fn optional_bool(&self) -> bool {
            self.optional_bool.unwrap_or(false)
        }
        pub fn optional_bool_opt(&self) -> Option<bool> {
            self.optional_bool.get()
        }
        pub fn set_optional_bool(&mut self, v: bool) {
            self.cached_size.dirty();
            self.optional_bool = pbrs::rt::OptBool::some(v);
        }
        pub fn clear_optional_bool(&mut self) {
            self.cached_size.dirty();
            self.optional_bool = pbrs::rt::OptBool::NONE;
        }
        pub fn has_optional_string(&self) -> bool {
            self.optional_string.is_some()
        }
        pub fn optional_string(&self) -> &pbrs::ProtoStr {
            self.optional_string
                .as_ref()
                .map(|s| s.as_view())
                .unwrap_or_else(|| pbrs::ProtoStr::from_bytes(b""))
        }
        pub fn optional_string_opt(&self) -> Option<&pbrs::ProtoStr> {
            self.optional_string.as_ref().map(|s| s.as_view())
        }
        pub fn set_optional_string(&mut self, v: impl pbrs::IntoProxied<ProtoString>) {
            self.cached_size.dirty();
            self.optional_string = Some(Box::new(pbrs::rt::LazyStr::owned(
                v.into_proxied(pbrs::__internal::Private),
            )));
        }
        pub fn clear_optional_string(&mut self) {
            self.cached_size.dirty();
            self.optional_string = None;
        }
        pub fn optional_bytes(&self) -> &[u8] {
            self.optional_bytes
                .as_ref()
                .map(|b| b.as_bytes())
                .unwrap_or(b"")
        }
        pub fn optional_bytes_opt(&self) -> Option<&[u8]> {
            self.optional_bytes.as_ref().map(|b| b.as_bytes())
        }
        pub fn has_optional_bytes(&self) -> bool {
            self.optional_bytes.is_some()
        }
        pub fn set_optional_bytes(&mut self, v: impl pbrs::IntoProxied<ProtoBytes>) {
            self.cached_size.dirty();
            self.optional_bytes = Some(Box::new(pbrs::rt::LazyBytes::owned(
                v.into_proxied(pbrs::__internal::Private),
            )));
        }
        pub fn clear_optional_bytes(&mut self) {
            self.cached_size.dirty();
            self.optional_bytes = None;
        }
        pub fn has_optional_cord(&self) -> bool {
            self.optional_cord.is_some()
        }
        pub fn optional_cord(&self) -> &pbrs::ProtoStr {
            self.optional_cord
                .as_ref()
                .map(|s| s.as_view())
                .unwrap_or_else(|| pbrs::ProtoStr::from_bytes(b""))
        }
        pub fn optional_cord_opt(&self) -> Option<&pbrs::ProtoStr> {
            self.optional_cord.as_ref().map(|s| s.as_view())
        }
        pub fn set_optional_cord(&mut self, v: impl pbrs::IntoProxied<ProtoString>) {
            self.cached_size.dirty();
            self.optional_cord = Some(Box::new(pbrs::rt::LazyStr::owned(
                v.into_proxied(pbrs::__internal::Private),
            )));
        }
        pub fn clear_optional_cord(&mut self) {
            self.cached_size.dirty();
            self.optional_cord = None;
        }
        pub fn has_optional_nested_message(&self) -> bool {
            self.optional_nested_message.is_some()
        }
        pub fn optional_nested_message(&self) -> &NestedMessage {
            self.optional_nested_message
                .as_deref()
                .unwrap_or(pbrs::gen_support::default_instance_of())
        }
        pub fn optional_nested_message_opt(&self) -> Option<&NestedMessage> {
            self.optional_nested_message.as_deref()
        }
        pub fn optional_nested_message_view(&self) -> NestedMessageView<'_> {
            NestedMessageView(self.optional_nested_message())
        }
        pub fn set_optional_nested_message(&mut self, v: NestedMessage) {
            self.cached_size.dirty();
            self.optional_nested_message = pbrs::rt::LazyMsg::from_owned(v);
        }
        pub fn optional_nested_message_mut(&mut self) -> &mut NestedMessage {
            self.cached_size.dirty();
            self.optional_nested_message.get_or_insert()
        }
        pub fn clear_optional_nested_message(&mut self) {
            self.cached_size.dirty();
            self.optional_nested_message.clear();
        }
        pub fn has_lazy_nested_message(&self) -> bool {
            self.lazy_nested_message.is_some()
        }
        pub fn lazy_nested_message(&self) -> &NestedMessage {
            self.lazy_nested_message
                .as_deref()
                .unwrap_or(pbrs::gen_support::default_instance_of())
        }
        pub fn lazy_nested_message_opt(&self) -> Option<&NestedMessage> {
            self.lazy_nested_message.as_deref()
        }
        pub fn lazy_nested_message_view(&self) -> NestedMessageView<'_> {
            NestedMessageView(self.lazy_nested_message())
        }
        pub fn set_lazy_nested_message(&mut self, v: NestedMessage) {
            self.cached_size.dirty();
            self.lazy_nested_message = pbrs::rt::LazyMsg::from_owned(v);
        }
        pub fn lazy_nested_message_mut(&mut self) -> &mut NestedMessage {
            self.cached_size.dirty();
            self.lazy_nested_message.get_or_insert()
        }
        pub fn clear_lazy_nested_message(&mut self) {
            self.cached_size.dirty();
            self.lazy_nested_message.clear();
        }
        pub fn has_optional_nested_enum(&self) -> bool {
            self.optional_nested_enum.is_some()
        }
        pub fn optional_nested_enum(&self) -> NestedEnum {
            NestedEnum(self.optional_nested_enum.unwrap_or(0))
        }
        pub fn optional_nested_enum_opt(&self) -> Option<NestedEnum> {
            self.optional_nested_enum.map(|v| NestedEnum(v))
        }
        pub fn set_optional_nested_enum(&mut self, v: impl Into<i32>) {
            self.cached_size.dirty();
            self.optional_nested_enum = Some(v.into());
        }
        pub fn clear_optional_nested_enum(&mut self) {
            self.cached_size.dirty();
            self.optional_nested_enum = None;
        }
        pub fn singular_int32(&self) -> i32 {
            self.singular_int32
        }
        pub fn set_singular_int32(&mut self, v: i32) {
            self.cached_size.dirty();
            self.singular_int32 = v;
        }
        pub fn singular_int64(&self) -> i64 {
            self.singular_int64
        }
        pub fn set_singular_int64(&mut self, v: i64) {
            self.cached_size.dirty();
            self.singular_int64 = v;
        }
        #[inline(always)]
        fn check_required(&self) -> Result<(), ParseError> {
            Ok(())
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return self.check_required();
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return Ok(());
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(data, wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    1 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            self.optional_int32 = Some(pbrs::rt::decode_varint(data, pos)? as i32);
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    2 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            self.optional_int64 = Some(pbrs::rt::decode_varint(data, pos)? as i64);
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    3 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            self.optional_uint32 = Some(pbrs::rt::decode_varint(data, pos)? as u32);
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    4 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            self.optional_uint64 = Some(pbrs::rt::decode_varint(data, pos)?);
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    5 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            self.optional_sint32 = Some(pbrs::rt::decode_zigzag32(
                                pbrs::rt::decode_varint(data, pos)?,
                            ));
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    6 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            self.optional_sint64 = Some(pbrs::rt::decode_zigzag64(
                                pbrs::rt::decode_varint(data, pos)?,
                            ));
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    7 => match w {
                        pbrs::rt::WIRE_I32 => {
                            self.optional_fixed32 = Some(pbrs::rt::read_fixed32(data, pos)?);
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    8 => match w {
                        pbrs::rt::WIRE_I64 => {
                            self.optional_fixed64 = Some(pbrs::rt::read_fixed64(data, pos)?);
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    9 => match w {
                        pbrs::rt::WIRE_I32 => {
                            self.optional_sfixed32 =
                                Some(pbrs::rt::read_fixed32(data, pos)? as i32);
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    10 => match w {
                        pbrs::rt::WIRE_I64 => {
                            self.optional_sfixed64 =
                                Some(pbrs::rt::read_fixed64(data, pos)? as i64);
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    11 => match w {
                        pbrs::rt::WIRE_I32 => {
                            self.optional_float =
                                Some(f32::from_bits(pbrs::rt::read_fixed32(data, pos)?));
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    12 => match w {
                        pbrs::rt::WIRE_I64 => {
                            self.optional_double =
                                Some(f64::from_bits(pbrs::rt::read_fixed64(data, pos)?));
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    13 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            self.optional_bool =
                                pbrs::rt::OptBool::some(pbrs::rt::decode_varint(data, pos)? != 0);
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    14 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            let b = &data[s..e];
                            std::str::from_utf8(b).map_err(|_| ParseError::new("invalid utf-8"))?;
                            self.optional_string = Some(Box::new(pbrs::rt::LazyStr::from_span(
                                pbrs::rt::Wire::ensure(wire, data),
                                s,
                                e,
                            )));
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    15 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            self.optional_bytes = Some(Box::new(pbrs::rt::LazyBytes::from_wire(
                                pbrs::rt::Wire::ensure(wire, data).window(s, e),
                            )));
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    16 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            let b = &data[s..e];
                            std::str::from_utf8(b).map_err(|_| ParseError::new("invalid utf-8"))?;
                            self.optional_cord = Some(Box::new(pbrs::rt::LazyStr::from_span(
                                pbrs::rt::Wire::ensure(wire, data),
                                s,
                                e,
                            )));
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    18 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            if self.optional_nested_message.is_some() {
                                let mut ip = 0;
                                let mut sw = None;
                                self.optional_nested_message.get_or_insert().merge_inner(
                                    &data[s..e],
                                    &mut sw,
                                    &mut ip,
                                    depth + 1,
                                    true,
                                    None,
                                )?;
                            } else {
                                let mut ip = 0;
                                NestedMessage::validate_inner(
                                    &pbrs::rt::Wire::ensure(wire, data).window(s, e),
                                    &mut ip,
                                    depth + 1,
                                )?;
                                self.optional_nested_message = pbrs::rt::LazyMsg::from_wire(
                                    pbrs::rt::Wire::ensure(wire, data).window(s, e),
                                );
                            }
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    19 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            if self.lazy_nested_message.is_some() {
                                let mut ip = 0;
                                let mut sw = None;
                                self.lazy_nested_message.get_or_insert().merge_inner(
                                    &data[s..e],
                                    &mut sw,
                                    &mut ip,
                                    depth + 1,
                                    true,
                                    None,
                                )?;
                            } else {
                                let mut ip = 0;
                                NestedMessage::validate_inner(
                                    &pbrs::rt::Wire::ensure(wire, data).window(s, e),
                                    &mut ip,
                                    depth + 1,
                                )?;
                                self.lazy_nested_message = pbrs::rt::LazyMsg::from_wire(
                                    pbrs::rt::Wire::ensure(wire, data).window(s, e),
                                );
                            }
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    21 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            self.optional_nested_enum =
                                Some(pbrs::rt::decode_varint(data, pos)? as i32);
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    22 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            self.singular_int32 = pbrs::rt::decode_varint(data, pos)? as i32;
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    23 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            self.singular_int64 = pbrs::rt::decode_varint(data, pos)? as i64;
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    _ => self
                        .unknown
                        .fields
                        .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            if enforce {
                self.check_required()?;
            }
            Ok(())
        }
        fn validate_inner(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
        ) -> Result<(), ParseError> {
            Self::validate_until(wire, pos, depth, None)
        }
        fn validate_until(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    1 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_varint(data, pos)? as i32;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    2 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_varint(data, pos)? as i64;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    3 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_varint(data, pos)? as u32;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    4 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_varint(data, pos)?;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    5 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_zigzag32(pbrs::rt::decode_varint(data, pos)?);
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    6 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_zigzag64(pbrs::rt::decode_varint(data, pos)?);
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    7 => match w {
                        pbrs::rt::WIRE_I32 => {
                            let _ = pbrs::rt::read_fixed32(data, pos)?;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    8 => match w {
                        pbrs::rt::WIRE_I64 => {
                            let _ = pbrs::rt::read_fixed64(data, pos)?;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    9 => match w {
                        pbrs::rt::WIRE_I32 => {
                            let _ = pbrs::rt::read_fixed32(data, pos)? as i32;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    10 => match w {
                        pbrs::rt::WIRE_I64 => {
                            let _ = pbrs::rt::read_fixed64(data, pos)? as i64;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    11 => match w {
                        pbrs::rt::WIRE_I32 => {
                            let _ = f32::from_bits(pbrs::rt::read_fixed32(data, pos)?);
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    12 => match w {
                        pbrs::rt::WIRE_I64 => {
                            let _ = f64::from_bits(pbrs::rt::read_fixed64(data, pos)?);
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    13 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_varint(data, pos)? != 0;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    14 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            std::str::from_utf8(&data[s..e])
                                .map_err(|_| ParseError::new("invalid utf-8"))?;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    15 => match w {
                        pbrs::rt::WIRE_LEN => {
                            pbrs::rt::read_len_span(data, pos)?;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    16 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            std::str::from_utf8(&data[s..e])
                                .map_err(|_| ParseError::new("invalid utf-8"))?;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    18 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            let mut ip = 0;
                            NestedMessage::validate_inner(&wire.window(s, e), &mut ip, depth + 1)?;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    19 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            let mut ip = 0;
                            NestedMessage::validate_inner(&wire.window(s, e), &mut ip, depth + 1)?;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    21 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_varint(data, pos)? as i32;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    22 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_varint(data, pos)? as i32;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    23 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_varint(data, pos)? as i64;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    _ => pbrs::rt::skip_field(data, pos, w)?,
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            if let Some(v) = self.optional_int32 {
                n += pbrs::rt::tag_len(1, pbrs::rt::WIRE_VARINT) + pbrs::rt::varint_len((v) as u64);
            }
            if let Some(v) = self.optional_int64 {
                n += pbrs::rt::tag_len(2, pbrs::rt::WIRE_VARINT) + pbrs::rt::varint_len((v) as u64);
            }
            if let Some(v) = self.optional_uint32 {
                n += pbrs::rt::tag_len(3, pbrs::rt::WIRE_VARINT) + pbrs::rt::varint_len((v) as u64);
            }
            if let Some(v) = self.optional_uint64 {
                n += pbrs::rt::tag_len(4, pbrs::rt::WIRE_VARINT) + pbrs::rt::varint_len((v) as u64);
            }
            if let Some(v) = self.optional_sint32 {
                n += pbrs::rt::tag_len(5, pbrs::rt::WIRE_VARINT)
                    + pbrs::rt::varint_len(pbrs::rt::encode_zigzag32(v));
            }
            if let Some(v) = self.optional_sint64 {
                n += pbrs::rt::tag_len(6, pbrs::rt::WIRE_VARINT)
                    + pbrs::rt::varint_len(pbrs::rt::encode_zigzag64(v));
            }
            if let Some(v) = self.optional_fixed32 {
                n += pbrs::rt::tag_len(7, pbrs::rt::WIRE_I32) + 4;
            }
            if let Some(v) = self.optional_fixed64 {
                n += pbrs::rt::tag_len(8, pbrs::rt::WIRE_I64) + 8;
            }
            if let Some(v) = self.optional_sfixed32 {
                n += pbrs::rt::tag_len(9, pbrs::rt::WIRE_I32) + 4;
            }
            if let Some(v) = self.optional_sfixed64 {
                n += pbrs::rt::tag_len(10, pbrs::rt::WIRE_I64) + 8;
            }
            if let Some(v) = self.optional_float {
                n += pbrs::rt::tag_len(11, pbrs::rt::WIRE_I32) + 4;
            }
            if let Some(v) = self.optional_double {
                n += pbrs::rt::tag_len(12, pbrs::rt::WIRE_I64) + 8;
            }
            if let Some(v) = self.optional_bool.get() {
                n += pbrs::rt::tag_len(13, pbrs::rt::WIRE_VARINT)
                    + pbrs::rt::varint_len(u64::from(v));
            }
            if let Some(s) = &self.optional_string {
                n += pbrs::rt::key_len_value_len(14, s.as_bytes().len() as u64);
            }
            if let Some(s) = &self.optional_bytes {
                n += pbrs::rt::key_len_value_len(15, s.as_bytes().len() as u64);
            }
            if let Some(s) = &self.optional_cord {
                n += pbrs::rt::key_len_value_len(16, s.as_bytes().len() as u64);
            }
            if let Some(p) = self.optional_nested_message.wire_bytes() {
                n += pbrs::rt::key_len_value_len(18, p.len() as u64);
            } else if let Some(m) = self.optional_nested_message.as_deref() {
                n += pbrs::rt::key_len_value_len(18, m.compute_size());
            }
            if let Some(p) = self.lazy_nested_message.wire_bytes() {
                n += pbrs::rt::key_len_value_len(19, p.len() as u64);
            } else if let Some(m) = self.lazy_nested_message.as_deref() {
                n += pbrs::rt::key_len_value_len(19, m.compute_size());
            }
            if let Some(v) = self.optional_nested_enum {
                n +=
                    pbrs::rt::tag_len(21, pbrs::rt::WIRE_VARINT) + pbrs::rt::varint_len((v) as u64);
            }
            if self.singular_int32 != 0 {
                n += pbrs::rt::tag_len(22, pbrs::rt::WIRE_VARINT)
                    + pbrs::rt::varint_len((self.singular_int32) as u64);
            }
            if self.singular_int64 != 0 {
                n += pbrs::rt::tag_len(23, pbrs::rt::WIRE_VARINT)
                    + pbrs::rt::varint_len((self.singular_int64) as u64);
            }
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut Vec<u8>) {
            if let Some(v) = self.optional_int32 {
                pbrs::rt::encode_tag(out, 1, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, v as u64);
            }
            if let Some(v) = self.optional_int64 {
                pbrs::rt::encode_tag(out, 2, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, v as u64);
            }
            if let Some(v) = self.optional_uint32 {
                pbrs::rt::encode_tag(out, 3, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, v as u64);
            }
            if let Some(v) = self.optional_uint64 {
                pbrs::rt::encode_tag(out, 4, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, v as u64);
            }
            if let Some(v) = self.optional_sint32 {
                pbrs::rt::encode_tag(out, 5, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, pbrs::rt::encode_zigzag32(v));
            }
            if let Some(v) = self.optional_sint64 {
                pbrs::rt::encode_tag(out, 6, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, pbrs::rt::encode_zigzag64(v));
            }
            if let Some(v) = self.optional_fixed32 {
                pbrs::rt::encode_tag(out, 7, pbrs::rt::WIRE_I32);
                (out).extend_from_slice(&(v).to_le_bytes());
            }
            if let Some(v) = self.optional_fixed64 {
                pbrs::rt::encode_tag(out, 8, pbrs::rt::WIRE_I64);
                (out).extend_from_slice(&(v).to_le_bytes());
            }
            if let Some(v) = self.optional_sfixed32 {
                pbrs::rt::encode_tag(out, 9, pbrs::rt::WIRE_I32);
                (out).extend_from_slice(&((v) as u32).to_le_bytes());
            }
            if let Some(v) = self.optional_sfixed64 {
                pbrs::rt::encode_tag(out, 10, pbrs::rt::WIRE_I64);
                (out).extend_from_slice(&((v) as u64).to_le_bytes());
            }
            if let Some(v) = self.optional_float {
                pbrs::rt::encode_tag(out, 11, pbrs::rt::WIRE_I32);
                (out).extend_from_slice(&(v).to_bits().to_le_bytes());
            }
            if let Some(v) = self.optional_double {
                pbrs::rt::encode_tag(out, 12, pbrs::rt::WIRE_I64);
                (out).extend_from_slice(&(v).to_bits().to_le_bytes());
            }
            if let Some(v) = self.optional_bool.get() {
                pbrs::rt::encode_tag(out, 13, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, u64::from(v));
            }
            if let Some(s) = &self.optional_string {
                pbrs::rt::encode_len_field(out, 14, s.as_bytes());
            }
            if let Some(s) = &self.optional_bytes {
                pbrs::rt::encode_len_field(out, 15, s.as_bytes());
            }
            if let Some(s) = &self.optional_cord {
                pbrs::rt::encode_len_field(out, 16, s.as_bytes());
            }
            if let Some(p) = self.optional_nested_message.wire_bytes() {
                pbrs::rt::encode_len_header(out, 18, p.len() as u64);
                out.extend_from_slice(p);
            } else if let Some(m) = self.optional_nested_message.as_deref() {
                pbrs::rt::encode_len_header(out, 18, m.compute_size());
                m.write_to(out);
            }
            if let Some(p) = self.lazy_nested_message.wire_bytes() {
                pbrs::rt::encode_len_header(out, 19, p.len() as u64);
                out.extend_from_slice(p);
            } else if let Some(m) = self.lazy_nested_message.as_deref() {
                pbrs::rt::encode_len_header(out, 19, m.compute_size());
                m.write_to(out);
            }
            if let Some(v) = self.optional_nested_enum {
                pbrs::rt::encode_tag(out, 21, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, v as u64);
            }
            if self.singular_int32 != 0 {
                pbrs::rt::encode_tag(out, 22, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, self.singular_int32 as u64);
            }
            if self.singular_int64 != 0 {
                pbrs::rt::encode_tag(out, 23, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, self.singular_int64 as u64);
            }
            self.unknown.encode(out);
        }
    }
    pbrs::impl_typed_message!(
        TestProto3Optional,
        TestProto3OptionalView,
        TestProto3OptionalMut
    );
    #[derive(Clone, Debug)]
    pub struct NestedMessage {
        bb: Option<i32>,
        unknown: UnknownFields,
        cached_size: pbrs::rt::CachedSize,
    }
    impl PartialEq for NestedMessage {
        fn eq(&self, other: &Self) -> bool {
            if self.bb != other.bb {
                return false;
            }
            self.unknown == other.unknown
        }
    }
    impl Eq for NestedMessage {}
    impl Default for NestedMessage {
        #[inline(always)]
        fn default() -> Self {
            unsafe { pbrs::rt::zeroed_message() }
        }
    }
    impl NestedMessage {
        pub fn new() -> Self {
            Self::default()
        }
        pub const EMPTY_PARSE_OK: bool = true;
        pub const FULL_NAME: &'static str =
            "rust_unittest_proto3_optional.TestProto3Optional.NestedMessage";
        pub fn has_bb(&self) -> bool {
            self.bb.is_some()
        }
        pub fn bb(&self) -> i32 {
            self.bb.unwrap_or(0)
        }
        pub fn bb_opt(&self) -> Option<i32> {
            self.bb.map(|v| v)
        }
        pub fn set_bb(&mut self, v: i32) {
            self.cached_size.dirty();
            self.bb = Some(v);
        }
        pub fn clear_bb(&mut self) {
            self.cached_size.dirty();
            self.bb = None;
        }
        #[inline(always)]
        fn check_required(&self) -> Result<(), ParseError> {
            Ok(())
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return self.check_required();
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return Ok(());
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(data, wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    1 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            self.bb = Some(pbrs::rt::decode_varint(data, pos)? as i32);
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    _ => self
                        .unknown
                        .fields
                        .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            if enforce {
                self.check_required()?;
            }
            Ok(())
        }
        fn validate_inner(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
        ) -> Result<(), ParseError> {
            Self::validate_until(wire, pos, depth, None)
        }
        fn validate_until(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    1 => match w {
                        pbrs::rt::WIRE_VARINT => {
                            let _ = pbrs::rt::decode_varint(data, pos)? as i32;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    _ => pbrs::rt::skip_field(data, pos, w)?,
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            if let Some(v) = self.bb {
                n += pbrs::rt::tag_len(1, pbrs::rt::WIRE_VARINT) + pbrs::rt::varint_len((v) as u64);
            }
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut Vec<u8>) {
            if let Some(v) = self.bb {
                pbrs::rt::encode_tag(out, 1, pbrs::rt::WIRE_VARINT);
                pbrs::rt::encode_varint(out, v as u64);
            }
            self.unknown.encode(out);
        }
    }
    pbrs::impl_typed_message!(NestedMessage, NestedMessageView, NestedMessageMut);
    #[derive(Clone, Debug)]
    pub struct TestProto3OptionalMessage {
        nested_message: pbrs::rt::LazyMsg<TestProto3OptionalMessageNestedMessage>,
        optional_nested_message: pbrs::rt::LazyMsg<TestProto3OptionalMessageNestedMessage>,
        unknown: UnknownFields,
        cached_size: pbrs::rt::CachedSize,
    }
    impl PartialEq for TestProto3OptionalMessage {
        fn eq(&self, other: &Self) -> bool {
            if self.nested_message != other.nested_message {
                return false;
            }
            if self.optional_nested_message != other.optional_nested_message {
                return false;
            }
            self.unknown == other.unknown
        }
    }
    impl Eq for TestProto3OptionalMessage {}
    impl Default for TestProto3OptionalMessage {
        #[inline(always)]
        fn default() -> Self {
            unsafe { pbrs::rt::zeroed_message() }
        }
    }
    impl TestProto3OptionalMessage {
        pub fn new() -> Self {
            Self::default()
        }
        pub const EMPTY_PARSE_OK: bool = true;
        pub const FULL_NAME: &'static str =
            "rust_unittest_proto3_optional.TestProto3OptionalMessage";
        pub fn has_nested_message(&self) -> bool {
            self.nested_message.is_some()
        }
        pub fn nested_message(&self) -> &TestProto3OptionalMessageNestedMessage {
            self.nested_message
                .as_deref()
                .unwrap_or(pbrs::gen_support::default_instance_of())
        }
        pub fn nested_message_opt(&self) -> Option<&TestProto3OptionalMessageNestedMessage> {
            self.nested_message.as_deref()
        }
        pub fn nested_message_view(&self) -> TestProto3OptionalMessageNestedMessageView<'_> {
            TestProto3OptionalMessageNestedMessageView(self.nested_message())
        }
        pub fn set_nested_message(&mut self, v: TestProto3OptionalMessageNestedMessage) {
            self.cached_size.dirty();
            self.nested_message = pbrs::rt::LazyMsg::from_owned(v);
        }
        pub fn nested_message_mut(&mut self) -> &mut TestProto3OptionalMessageNestedMessage {
            self.cached_size.dirty();
            self.nested_message.get_or_insert()
        }
        pub fn clear_nested_message(&mut self) {
            self.cached_size.dirty();
            self.nested_message.clear();
        }
        pub fn has_optional_nested_message(&self) -> bool {
            self.optional_nested_message.is_some()
        }
        pub fn optional_nested_message(&self) -> &TestProto3OptionalMessageNestedMessage {
            self.optional_nested_message
                .as_deref()
                .unwrap_or(pbrs::gen_support::default_instance_of())
        }
        pub fn optional_nested_message_opt(
            &self,
        ) -> Option<&TestProto3OptionalMessageNestedMessage> {
            self.optional_nested_message.as_deref()
        }
        pub fn optional_nested_message_view(
            &self,
        ) -> TestProto3OptionalMessageNestedMessageView<'_> {
            TestProto3OptionalMessageNestedMessageView(self.optional_nested_message())
        }
        pub fn set_optional_nested_message(&mut self, v: TestProto3OptionalMessageNestedMessage) {
            self.cached_size.dirty();
            self.optional_nested_message = pbrs::rt::LazyMsg::from_owned(v);
        }
        pub fn optional_nested_message_mut(
            &mut self,
        ) -> &mut TestProto3OptionalMessageNestedMessage {
            self.cached_size.dirty();
            self.optional_nested_message.get_or_insert()
        }
        pub fn clear_optional_nested_message(&mut self) {
            self.cached_size.dirty();
            self.optional_nested_message.clear();
        }
        #[inline(always)]
        fn check_required(&self) -> Result<(), ParseError> {
            Ok(())
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return self.check_required();
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return Ok(());
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(data, wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    1 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            if self.nested_message.is_some() {
                                let mut ip = 0;
                                let mut sw = None;
                                self.nested_message.get_or_insert().merge_inner(
                                    &data[s..e],
                                    &mut sw,
                                    &mut ip,
                                    depth + 1,
                                    true,
                                    None,
                                )?;
                            } else {
                                let mut ip = 0;
                                TestProto3OptionalMessageNestedMessage::validate_inner(
                                    &pbrs::rt::Wire::ensure(wire, data).window(s, e),
                                    &mut ip,
                                    depth + 1,
                                )?;
                                self.nested_message = pbrs::rt::LazyMsg::from_wire(
                                    pbrs::rt::Wire::ensure(wire, data).window(s, e),
                                );
                            }
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    2 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            if self.optional_nested_message.is_some() {
                                let mut ip = 0;
                                let mut sw = None;
                                self.optional_nested_message.get_or_insert().merge_inner(
                                    &data[s..e],
                                    &mut sw,
                                    &mut ip,
                                    depth + 1,
                                    true,
                                    None,
                                )?;
                            } else {
                                let mut ip = 0;
                                TestProto3OptionalMessageNestedMessage::validate_inner(
                                    &pbrs::rt::Wire::ensure(wire, data).window(s, e),
                                    &mut ip,
                                    depth + 1,
                                )?;
                                self.optional_nested_message = pbrs::rt::LazyMsg::from_wire(
                                    pbrs::rt::Wire::ensure(wire, data).window(s, e),
                                );
                            }
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    _ => self
                        .unknown
                        .fields
                        .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            if enforce {
                self.check_required()?;
            }
            Ok(())
        }
        fn validate_inner(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
        ) -> Result<(), ParseError> {
            Self::validate_until(wire, pos, depth, None)
        }
        fn validate_until(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    1 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            let mut ip = 0;
                            TestProto3OptionalMessageNestedMessage::validate_inner(
                                &wire.window(s, e),
                                &mut ip,
                                depth + 1,
                            )?;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    2 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            let mut ip = 0;
                            TestProto3OptionalMessageNestedMessage::validate_inner(
                                &wire.window(s, e),
                                &mut ip,
                                depth + 1,
                            )?;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    _ => pbrs::rt::skip_field(data, pos, w)?,
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            if let Some(p) = self.nested_message.wire_bytes() {
                n += pbrs::rt::key_len_value_len(1, p.len() as u64);
            } else if let Some(m) = self.nested_message.as_deref() {
                n += pbrs::rt::key_len_value_len(1, m.compute_size());
            }
            if let Some(p) = self.optional_nested_message.wire_bytes() {
                n += pbrs::rt::key_len_value_len(2, p.len() as u64);
            } else if let Some(m) = self.optional_nested_message.as_deref() {
                n += pbrs::rt::key_len_value_len(2, m.compute_size());
            }
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut Vec<u8>) {
            if let Some(p) = self.nested_message.wire_bytes() {
                pbrs::rt::encode_len_header(out, 1, p.len() as u64);
                out.extend_from_slice(p);
            } else if let Some(m) = self.nested_message.as_deref() {
                pbrs::rt::encode_len_header(out, 1, m.compute_size());
                m.write_to(out);
            }
            if let Some(p) = self.optional_nested_message.wire_bytes() {
                pbrs::rt::encode_len_header(out, 2, p.len() as u64);
                out.extend_from_slice(p);
            } else if let Some(m) = self.optional_nested_message.as_deref() {
                pbrs::rt::encode_len_header(out, 2, m.compute_size());
                m.write_to(out);
            }
            self.unknown.encode(out);
        }
    }
    pbrs::impl_typed_message!(
        TestProto3OptionalMessage,
        TestProto3OptionalMessageView,
        TestProto3OptionalMessageMut
    );
    #[derive(Clone, Debug)]
    pub struct TestProto3OptionalMessageNestedMessage {
        s: pbrs::rt::LazyStr,
        unknown: UnknownFields,
        cached_size: pbrs::rt::CachedSize,
    }
    impl PartialEq for TestProto3OptionalMessageNestedMessage {
        fn eq(&self, other: &Self) -> bool {
            if self.s != other.s {
                return false;
            }
            self.unknown == other.unknown
        }
    }
    impl Eq for TestProto3OptionalMessageNestedMessage {}
    impl Default for TestProto3OptionalMessageNestedMessage {
        #[inline(always)]
        fn default() -> Self {
            unsafe { pbrs::rt::zeroed_message() }
        }
    }
    impl TestProto3OptionalMessageNestedMessage {
        pub fn new() -> Self {
            Self::default()
        }
        pub const EMPTY_PARSE_OK: bool = true;
        pub const FULL_NAME: &'static str =
            "rust_unittest_proto3_optional.TestProto3OptionalMessage.NestedMessage";
        pub fn s(&self) -> &pbrs::ProtoStr {
            self.s.as_view()
        }
        pub fn set_s(&mut self, v: impl pbrs::IntoProxied<ProtoString>) {
            self.cached_size.dirty();
            self.s = pbrs::rt::LazyStr::owned(v.into_proxied(pbrs::__internal::Private));
        }
        #[inline(always)]
        fn check_required(&self) -> Result<(), ParseError> {
            Ok(())
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return self.check_required();
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            if data.is_empty() {
                return Ok(());
            }
            let mut pos = 0;
            let mut wire = None;
            self.merge_inner(data, &mut wire, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(data, wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            data: &[u8],
            wire: &mut Option<pbrs::rt::Wire>,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    1 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            let b = &data[s..e];
                            std::str::from_utf8(b).map_err(|_| ParseError::new("invalid utf-8"))?;
                            self.s = pbrs::rt::LazyStr::from_span(
                                pbrs::rt::Wire::ensure(wire, data),
                                s,
                                e,
                            );
                        }
                        _ => self
                            .unknown
                            .fields
                            .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                    },
                    _ => self
                        .unknown
                        .fields
                        .push(pbrs::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            if enforce {
                self.check_required()?;
            }
            Ok(())
        }
        fn validate_inner(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
        ) -> Result<(), ParseError> {
            Self::validate_until(wire, pos, depth, None)
        }
        fn validate_until(
            wire: &pbrs::rt::Wire,
            pos: &mut usize,
            depth: u32,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > pbrs::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = pbrs::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == pbrs::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match n {
                    1 => match w {
                        pbrs::rt::WIRE_LEN => {
                            let (s, e) = pbrs::rt::read_len_span(data, pos)?;
                            std::str::from_utf8(&data[s..e])
                                .map_err(|_| ParseError::new("invalid utf-8"))?;
                        }
                        _ => pbrs::rt::skip_field(data, pos, w)?,
                    },
                    _ => pbrs::rt::skip_field(data, pos, w)?,
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            if !self.s.is_empty() {
                n += pbrs::rt::key_len_value_len(1, self.s.as_bytes().len() as u64);
            }
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut Vec<u8>) {
            if !self.s.is_empty() {
                pbrs::rt::encode_len_field(out, 1, self.s.as_bytes());
            }
            self.unknown.encode(out);
        }
    }
    pbrs::impl_typed_message!(
        TestProto3OptionalMessageNestedMessage,
        TestProto3OptionalMessageNestedMessageView,
        TestProto3OptionalMessageNestedMessageMut
    );
    pub mod test_proto3_optional {
        pub use super::NestedEnum;
        pub use super::NestedMessage;
    }
    pub mod test_proto3_optional_message {
        pub use super::TestProto3OptionalMessageNestedMessage as NestedMessage;
    }
}
#[allow(unused_imports)]
pub use __gen::*;
