// @generated by protoc-gen-pure-protobuf
#[allow(unused, non_snake_case, non_camel_case_types, clippy::all)]
mod __gen {
    #![allow(unused, non_snake_case, non_camel_case_types, clippy::all)]
    use protobuf::prelude::*;
    use protobuf::UnknownFields;
    use protobuf::{
        Map, MapMut, MapView, ParseError, ProtoBytes, ProtoString, Repeated, RepeatedMut,
        RepeatedView, SerializeError,
    };

    #[derive(Clone, Debug, PartialEq)]
    pub struct TestProto3Optional {
        optional_int32: Option<i32>,
        optional_int64: Option<i64>,
        optional_uint32: Option<u32>,
        optional_uint64: Option<u64>,
        optional_sint32: Option<i32>,
        optional_sint64: Option<i64>,
        optional_fixed32: Option<u32>,
        optional_fixed64: Option<u64>,
        optional_sfixed32: Option<i32>,
        optional_sfixed64: Option<i64>,
        optional_float: Option<f32>,
        optional_double: Option<f64>,
        optional_bool: Option<bool>,
        optional_string: Option<protobuf::rt::LazyStr>,
        optional_bytes: Option<protobuf::rt::LazyBytes>,
        optional_cord: Option<protobuf::rt::LazyStr>,
        optional_nested_message: protobuf::rt::LazyMsg<NestedMessage>,
        lazy_nested_message: protobuf::rt::LazyMsg<NestedMessage>,
        optional_nested_enum: Option<i32>,
        singular_int32: i32,
        singular_int64: i64,
        unknown: UnknownFields,
        cached_size: protobuf::rt::CachedSize,
    }
    impl Default for TestProto3Optional {
        fn default() -> Self {
            Self {
                optional_int32: None,
                optional_int64: None,
                optional_uint32: None,
                optional_uint64: None,
                optional_sint32: None,
                optional_sint64: None,
                optional_fixed32: None,
                optional_fixed64: None,
                optional_sfixed32: None,
                optional_sfixed64: None,
                optional_float: None,
                optional_double: None,
                optional_bool: None,
                optional_string: None,
                optional_bytes: None,
                optional_cord: None,
                optional_nested_message: Default::default(),
                lazy_nested_message: Default::default(),
                optional_nested_enum: None,
                singular_int32: Default::default(),
                singular_int64: Default::default(),
                unknown: UnknownFields::default(),
                cached_size: protobuf::rt::CachedSize::default(),
            }
        }
    }
    impl TestProto3Optional {
        pub fn new() -> Self {
            Self::default()
        }
        pub const FULL_NAME: &'static str = "rust_unittest_proto3_optional.TestProto3Optional";
        pub fn has_optional_int32(&self) -> bool {
            self.optional_int32.is_some()
        }
        pub fn optional_int32(&self) -> i32 {
            self.optional_int32.unwrap_or_default()
        }
        pub fn set_optional_int32(&mut self, v: i32) {
            self.cached_size.dirty();
            self.optional_int32 = Some(v);
        }
        pub fn clear_optional_int32(&mut self) {
            self.cached_size.dirty();
            self.optional_int32 = None;
        }
        pub fn has_optional_int64(&self) -> bool {
            self.optional_int64.is_some()
        }
        pub fn optional_int64(&self) -> i64 {
            self.optional_int64.unwrap_or_default()
        }
        pub fn set_optional_int64(&mut self, v: i64) {
            self.cached_size.dirty();
            self.optional_int64 = Some(v);
        }
        pub fn clear_optional_int64(&mut self) {
            self.cached_size.dirty();
            self.optional_int64 = None;
        }
        pub fn has_optional_uint32(&self) -> bool {
            self.optional_uint32.is_some()
        }
        pub fn optional_uint32(&self) -> u32 {
            self.optional_uint32.unwrap_or_default()
        }
        pub fn set_optional_uint32(&mut self, v: u32) {
            self.cached_size.dirty();
            self.optional_uint32 = Some(v);
        }
        pub fn clear_optional_uint32(&mut self) {
            self.cached_size.dirty();
            self.optional_uint32 = None;
        }
        pub fn has_optional_uint64(&self) -> bool {
            self.optional_uint64.is_some()
        }
        pub fn optional_uint64(&self) -> u64 {
            self.optional_uint64.unwrap_or_default()
        }
        pub fn set_optional_uint64(&mut self, v: u64) {
            self.cached_size.dirty();
            self.optional_uint64 = Some(v);
        }
        pub fn clear_optional_uint64(&mut self) {
            self.cached_size.dirty();
            self.optional_uint64 = None;
        }
        pub fn has_optional_sint32(&self) -> bool {
            self.optional_sint32.is_some()
        }
        pub fn optional_sint32(&self) -> i32 {
            self.optional_sint32.unwrap_or_default()
        }
        pub fn set_optional_sint32(&mut self, v: i32) {
            self.cached_size.dirty();
            self.optional_sint32 = Some(v);
        }
        pub fn clear_optional_sint32(&mut self) {
            self.cached_size.dirty();
            self.optional_sint32 = None;
        }
        pub fn has_optional_sint64(&self) -> bool {
            self.optional_sint64.is_some()
        }
        pub fn optional_sint64(&self) -> i64 {
            self.optional_sint64.unwrap_or_default()
        }
        pub fn set_optional_sint64(&mut self, v: i64) {
            self.cached_size.dirty();
            self.optional_sint64 = Some(v);
        }
        pub fn clear_optional_sint64(&mut self) {
            self.cached_size.dirty();
            self.optional_sint64 = None;
        }
        pub fn has_optional_fixed32(&self) -> bool {
            self.optional_fixed32.is_some()
        }
        pub fn optional_fixed32(&self) -> u32 {
            self.optional_fixed32.unwrap_or_default()
        }
        pub fn set_optional_fixed32(&mut self, v: u32) {
            self.cached_size.dirty();
            self.optional_fixed32 = Some(v);
        }
        pub fn clear_optional_fixed32(&mut self) {
            self.cached_size.dirty();
            self.optional_fixed32 = None;
        }
        pub fn has_optional_fixed64(&self) -> bool {
            self.optional_fixed64.is_some()
        }
        pub fn optional_fixed64(&self) -> u64 {
            self.optional_fixed64.unwrap_or_default()
        }
        pub fn set_optional_fixed64(&mut self, v: u64) {
            self.cached_size.dirty();
            self.optional_fixed64 = Some(v);
        }
        pub fn clear_optional_fixed64(&mut self) {
            self.cached_size.dirty();
            self.optional_fixed64 = None;
        }
        pub fn has_optional_sfixed32(&self) -> bool {
            self.optional_sfixed32.is_some()
        }
        pub fn optional_sfixed32(&self) -> i32 {
            self.optional_sfixed32.unwrap_or_default()
        }
        pub fn set_optional_sfixed32(&mut self, v: i32) {
            self.cached_size.dirty();
            self.optional_sfixed32 = Some(v);
        }
        pub fn clear_optional_sfixed32(&mut self) {
            self.cached_size.dirty();
            self.optional_sfixed32 = None;
        }
        pub fn has_optional_sfixed64(&self) -> bool {
            self.optional_sfixed64.is_some()
        }
        pub fn optional_sfixed64(&self) -> i64 {
            self.optional_sfixed64.unwrap_or_default()
        }
        pub fn set_optional_sfixed64(&mut self, v: i64) {
            self.cached_size.dirty();
            self.optional_sfixed64 = Some(v);
        }
        pub fn clear_optional_sfixed64(&mut self) {
            self.cached_size.dirty();
            self.optional_sfixed64 = None;
        }
        pub fn has_optional_float(&self) -> bool {
            self.optional_float.is_some()
        }
        pub fn optional_float(&self) -> f32 {
            self.optional_float.unwrap_or_default()
        }
        pub fn set_optional_float(&mut self, v: f32) {
            self.cached_size.dirty();
            self.optional_float = Some(v);
        }
        pub fn clear_optional_float(&mut self) {
            self.cached_size.dirty();
            self.optional_float = None;
        }
        pub fn has_optional_double(&self) -> bool {
            self.optional_double.is_some()
        }
        pub fn optional_double(&self) -> f64 {
            self.optional_double.unwrap_or_default()
        }
        pub fn set_optional_double(&mut self, v: f64) {
            self.cached_size.dirty();
            self.optional_double = Some(v);
        }
        pub fn clear_optional_double(&mut self) {
            self.cached_size.dirty();
            self.optional_double = None;
        }
        pub fn has_optional_bool(&self) -> bool {
            self.optional_bool.is_some()
        }
        pub fn optional_bool(&self) -> bool {
            self.optional_bool.unwrap_or_default()
        }
        pub fn set_optional_bool(&mut self, v: bool) {
            self.cached_size.dirty();
            self.optional_bool = Some(v);
        }
        pub fn clear_optional_bool(&mut self) {
            self.cached_size.dirty();
            self.optional_bool = None;
        }
        pub fn has_optional_string(&self) -> bool {
            self.optional_string.is_some()
        }
        pub fn optional_string(&self) -> &protobuf::ProtoStr {
            self.optional_string
                .as_ref()
                .map(|s| s.as_view())
                .unwrap_or_else(|| protobuf::ProtoStr::from_bytes(b""))
        }
        pub fn set_optional_string(&mut self, v: impl protobuf::IntoProxied<ProtoString>) {
            self.cached_size.dirty();
            self.optional_string = Some(protobuf::rt::LazyStr::owned(v.into_proxied()));
        }
        pub fn clear_optional_string(&mut self) {
            self.cached_size.dirty();
            self.optional_string = None;
        }
        pub fn optional_bytes(&self) -> &[u8] {
            self.optional_bytes
                .as_ref()
                .map(|b| b.as_bytes())
                .unwrap_or(&[])
        }
        pub fn has_optional_bytes(&self) -> bool {
            self.optional_bytes.is_some()
        }
        pub fn set_optional_bytes(&mut self, v: impl protobuf::IntoProxied<ProtoBytes>) {
            self.cached_size.dirty();
            self.optional_bytes = Some(protobuf::rt::LazyBytes::owned(v.into_proxied()));
        }
        pub fn has_optional_cord(&self) -> bool {
            self.optional_cord.is_some()
        }
        pub fn optional_cord(&self) -> &protobuf::ProtoStr {
            self.optional_cord
                .as_ref()
                .map(|s| s.as_view())
                .unwrap_or_else(|| protobuf::ProtoStr::from_bytes(b""))
        }
        pub fn set_optional_cord(&mut self, v: impl protobuf::IntoProxied<ProtoString>) {
            self.cached_size.dirty();
            self.optional_cord = Some(protobuf::rt::LazyStr::owned(v.into_proxied()));
        }
        pub fn clear_optional_cord(&mut self) {
            self.cached_size.dirty();
            self.optional_cord = None;
        }
        pub fn has_optional_nested_message(&self) -> bool {
            self.optional_nested_message.is_some()
        }
        pub fn optional_nested_message(&self) -> Option<&NestedMessage> {
            self.optional_nested_message.as_deref()
        }
        pub fn optional_nested_message_view(&self) -> Option<NestedMessageView<'_>> {
            self.optional_nested_message
                .as_deref()
                .map(NestedMessageView)
        }
        pub fn set_optional_nested_message(&mut self, v: NestedMessage) {
            self.cached_size.dirty();
            self.optional_nested_message = protobuf::rt::LazyMsg::from_owned(v);
        }
        pub fn optional_nested_message_mut(&mut self) -> &mut NestedMessage {
            self.cached_size.dirty();
            self.optional_nested_message.get_or_insert()
        }
        pub fn clear_optional_nested_message(&mut self) {
            self.cached_size.dirty();
            self.optional_nested_message.clear();
        }
        pub fn has_lazy_nested_message(&self) -> bool {
            self.lazy_nested_message.is_some()
        }
        pub fn lazy_nested_message(&self) -> Option<&NestedMessage> {
            self.lazy_nested_message.as_deref()
        }
        pub fn lazy_nested_message_view(&self) -> Option<NestedMessageView<'_>> {
            self.lazy_nested_message.as_deref().map(NestedMessageView)
        }
        pub fn set_lazy_nested_message(&mut self, v: NestedMessage) {
            self.cached_size.dirty();
            self.lazy_nested_message = protobuf::rt::LazyMsg::from_owned(v);
        }
        pub fn lazy_nested_message_mut(&mut self) -> &mut NestedMessage {
            self.cached_size.dirty();
            self.lazy_nested_message.get_or_insert()
        }
        pub fn clear_lazy_nested_message(&mut self) {
            self.cached_size.dirty();
            self.lazy_nested_message.clear();
        }
        pub fn has_optional_nested_enum(&self) -> bool {
            self.optional_nested_enum.is_some()
        }
        pub fn optional_nested_enum(&self) -> i32 {
            self.optional_nested_enum.unwrap_or_default()
        }
        pub fn set_optional_nested_enum(&mut self, v: i32) {
            self.cached_size.dirty();
            self.optional_nested_enum = Some(v);
        }
        pub fn clear_optional_nested_enum(&mut self) {
            self.cached_size.dirty();
            self.optional_nested_enum = None;
        }
        pub fn singular_int32(&self) -> i32 {
            self.singular_int32
        }
        pub fn set_singular_int32(&mut self, v: i32) {
            self.cached_size.dirty();
            self.singular_int32 = v;
        }
        pub fn singular_int64(&self) -> i64 {
            self.singular_int64
        }
        pub fn set_singular_int64(&mut self, v: i64) {
            self.cached_size.dirty();
            self.singular_int64 = v;
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            let w = protobuf::rt::Wire::from_slice(data);
            let mut pos = 0;
            self.merge_inner(&w, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            let w = protobuf::rt::Wire::from_slice(data);
            let mut pos = 0;
            self.merge_inner(&w, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            wire: &protobuf::rt::Wire,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            wire: &protobuf::rt::Wire,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > protobuf::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = protobuf::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == protobuf::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match (n, w) {
                    (1, protobuf::rt::WIRE_VARINT) => {
                        self.optional_int32 = Some(protobuf::rt::decode_varint(data, pos)? as i32);
                    }
                    (2, protobuf::rt::WIRE_VARINT) => {
                        self.optional_int64 = Some(protobuf::rt::decode_varint(data, pos)? as i64);
                    }
                    (3, protobuf::rt::WIRE_VARINT) => {
                        self.optional_uint32 = Some(protobuf::rt::decode_varint(data, pos)? as u32);
                    }
                    (4, protobuf::rt::WIRE_VARINT) => {
                        self.optional_uint64 = Some(protobuf::rt::decode_varint(data, pos)?);
                    }
                    (5, protobuf::rt::WIRE_VARINT) => {
                        self.optional_sint32 = Some(protobuf::rt::decode_zigzag32(
                            protobuf::rt::decode_varint(data, pos)?,
                        ));
                    }
                    (6, protobuf::rt::WIRE_VARINT) => {
                        self.optional_sint64 = Some(protobuf::rt::decode_zigzag64(
                            protobuf::rt::decode_varint(data, pos)?,
                        ));
                    }
                    (7, protobuf::rt::WIRE_I32) => {
                        self.optional_fixed32 = Some(protobuf::rt::read_fixed32(data, pos)?);
                    }
                    (8, protobuf::rt::WIRE_I64) => {
                        self.optional_fixed64 = Some(protobuf::rt::read_fixed64(data, pos)?);
                    }
                    (9, protobuf::rt::WIRE_I32) => {
                        self.optional_sfixed32 =
                            Some(protobuf::rt::read_fixed32(data, pos)? as i32);
                    }
                    (10, protobuf::rt::WIRE_I64) => {
                        self.optional_sfixed64 =
                            Some(protobuf::rt::read_fixed64(data, pos)? as i64);
                    }
                    (11, protobuf::rt::WIRE_I32) => {
                        self.optional_float =
                            Some(f32::from_bits(protobuf::rt::read_fixed32(data, pos)?));
                    }
                    (12, protobuf::rt::WIRE_I64) => {
                        self.optional_double =
                            Some(f64::from_bits(protobuf::rt::read_fixed64(data, pos)?));
                    }
                    (13, protobuf::rt::WIRE_VARINT) => {
                        self.optional_bool = Some(protobuf::rt::decode_varint(data, pos)? != 0);
                    }
                    (14, protobuf::rt::WIRE_LEN) => {
                        let (s, e) = protobuf::rt::read_len_span(data, pos)?;
                        let b = &data[s..e];
                        std::str::from_utf8(b).map_err(|_| ParseError::new("invalid utf-8"))?;
                        self.optional_string =
                            Some(protobuf::rt::LazyStr::from_wire(wire.window(s, e)));
                    }
                    (15, protobuf::rt::WIRE_LEN) => {
                        let (s, e) = protobuf::rt::read_len_span(data, pos)?;
                        self.optional_bytes =
                            Some(protobuf::rt::LazyBytes::from_wire(wire.window(s, e)));
                    }
                    (16, protobuf::rt::WIRE_LEN) => {
                        let (s, e) = protobuf::rt::read_len_span(data, pos)?;
                        let b = &data[s..e];
                        std::str::from_utf8(b).map_err(|_| ParseError::new("invalid utf-8"))?;
                        self.optional_cord =
                            Some(protobuf::rt::LazyStr::from_wire(wire.window(s, e)));
                    }
                    (18, protobuf::rt::WIRE_LEN) => {
                        let (s, e) = protobuf::rt::read_len_span(data, pos)?;
                        if self.optional_nested_message.is_some() {
                            let mut ip = 0;
                            self.optional_nested_message.get_or_insert().merge_inner(
                                &wire.window(s, e),
                                &mut ip,
                                depth + 1,
                                true,
                                None,
                            )?;
                        } else {
                            let mut inner = NestedMessage::default();
                            let mut ip = 0;
                            inner.merge_inner(
                                &wire.window(s, e),
                                &mut ip,
                                depth + 1,
                                true,
                                None,
                            )?;
                            self.optional_nested_message =
                                protobuf::rt::LazyMsg::from_parsed(inner, wire.window(s, e));
                        }
                    }
                    (19, protobuf::rt::WIRE_LEN) => {
                        let (s, e) = protobuf::rt::read_len_span(data, pos)?;
                        if self.lazy_nested_message.is_some() {
                            let mut ip = 0;
                            self.lazy_nested_message.get_or_insert().merge_inner(
                                &wire.window(s, e),
                                &mut ip,
                                depth + 1,
                                true,
                                None,
                            )?;
                        } else {
                            let mut inner = NestedMessage::default();
                            let mut ip = 0;
                            inner.merge_inner(
                                &wire.window(s, e),
                                &mut ip,
                                depth + 1,
                                true,
                                None,
                            )?;
                            self.lazy_nested_message =
                                protobuf::rt::LazyMsg::from_parsed(inner, wire.window(s, e));
                        }
                    }
                    (21, protobuf::rt::WIRE_VARINT) => {
                        self.optional_nested_enum =
                            Some(protobuf::rt::decode_varint(data, pos)? as i32);
                    }
                    (22, protobuf::rt::WIRE_VARINT) => {
                        self.singular_int32 = protobuf::rt::decode_varint(data, pos)? as i32;
                    }
                    (23, protobuf::rt::WIRE_VARINT) => {
                        self.singular_int64 = protobuf::rt::decode_varint(data, pos)? as i64;
                    }
                    _ => self
                        .unknown
                        .fields
                        .push(protobuf::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            if let Some(v) = self.optional_int32 {
                n += protobuf::rt::tag_len(1, protobuf::rt::WIRE_VARINT)
                    + protobuf::rt::varint_len((v) as u64);
            }
            if let Some(v) = self.optional_int64 {
                n += protobuf::rt::tag_len(2, protobuf::rt::WIRE_VARINT)
                    + protobuf::rt::varint_len((v) as u64);
            }
            if let Some(v) = self.optional_uint32 {
                n += protobuf::rt::tag_len(3, protobuf::rt::WIRE_VARINT)
                    + protobuf::rt::varint_len((v) as u64);
            }
            if let Some(v) = self.optional_uint64 {
                n += protobuf::rt::tag_len(4, protobuf::rt::WIRE_VARINT)
                    + protobuf::rt::varint_len((v) as u64);
            }
            if let Some(v) = self.optional_sint32 {
                n += protobuf::rt::tag_len(5, protobuf::rt::WIRE_VARINT)
                    + protobuf::rt::varint_len(protobuf::rt::encode_zigzag32(v));
            }
            if let Some(v) = self.optional_sint64 {
                n += protobuf::rt::tag_len(6, protobuf::rt::WIRE_VARINT)
                    + protobuf::rt::varint_len(protobuf::rt::encode_zigzag64(v));
            }
            if let Some(v) = self.optional_fixed32 {
                n += protobuf::rt::tag_len(7, protobuf::rt::WIRE_I32) + 4;
            }
            if let Some(v) = self.optional_fixed64 {
                n += protobuf::rt::tag_len(8, protobuf::rt::WIRE_I64) + 8;
            }
            if let Some(v) = self.optional_sfixed32 {
                n += protobuf::rt::tag_len(9, protobuf::rt::WIRE_I32) + 4;
            }
            if let Some(v) = self.optional_sfixed64 {
                n += protobuf::rt::tag_len(10, protobuf::rt::WIRE_I64) + 8;
            }
            if let Some(v) = self.optional_float {
                n += protobuf::rt::tag_len(11, protobuf::rt::WIRE_I32) + 4;
            }
            if let Some(v) = self.optional_double {
                n += protobuf::rt::tag_len(12, protobuf::rt::WIRE_I64) + 8;
            }
            if let Some(v) = self.optional_bool {
                n += protobuf::rt::tag_len(13, protobuf::rt::WIRE_VARINT)
                    + protobuf::rt::varint_len(u64::from(v));
            }
            if let Some(s) = &self.optional_string {
                n += protobuf::rt::key_len_value_len(14, s.as_bytes().len() as u64);
            }
            if let Some(s) = &self.optional_bytes {
                n += protobuf::rt::key_len_value_len(15, s.as_bytes().len() as u64);
            }
            if let Some(s) = &self.optional_cord {
                n += protobuf::rt::key_len_value_len(16, s.as_bytes().len() as u64);
            }
            if let Some(p) = self.optional_nested_message.wire_bytes() {
                n += protobuf::rt::key_len_value_len(18, p.len() as u64);
            } else if let Some(m) = self.optional_nested_message.as_deref() {
                n += protobuf::rt::key_len_value_len(18, m.compute_size());
            }
            if let Some(p) = self.lazy_nested_message.wire_bytes() {
                n += protobuf::rt::key_len_value_len(19, p.len() as u64);
            } else if let Some(m) = self.lazy_nested_message.as_deref() {
                n += protobuf::rt::key_len_value_len(19, m.compute_size());
            }
            if let Some(v) = self.optional_nested_enum {
                n += protobuf::rt::tag_len(21, protobuf::rt::WIRE_VARINT)
                    + protobuf::rt::varint_len((v) as u64);
            }
            if self.singular_int32 != 0 {
                n += protobuf::rt::tag_len(22, protobuf::rt::WIRE_VARINT)
                    + protobuf::rt::varint_len((self.singular_int32) as u64);
            }
            if self.singular_int64 != 0 {
                n += protobuf::rt::tag_len(23, protobuf::rt::WIRE_VARINT)
                    + protobuf::rt::varint_len((self.singular_int64) as u64);
            }
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut Vec<u8>) {
            if let Some(v) = self.optional_int32 {
                protobuf::rt::encode_tag(out, 1, protobuf::rt::WIRE_VARINT);
                protobuf::rt::encode_varint(out, v as u64);
            }
            if let Some(v) = self.optional_int64 {
                protobuf::rt::encode_tag(out, 2, protobuf::rt::WIRE_VARINT);
                protobuf::rt::encode_varint(out, v as u64);
            }
            if let Some(v) = self.optional_uint32 {
                protobuf::rt::encode_tag(out, 3, protobuf::rt::WIRE_VARINT);
                protobuf::rt::encode_varint(out, v as u64);
            }
            if let Some(v) = self.optional_uint64 {
                protobuf::rt::encode_tag(out, 4, protobuf::rt::WIRE_VARINT);
                protobuf::rt::encode_varint(out, v as u64);
            }
            if let Some(v) = self.optional_sint32 {
                protobuf::rt::encode_tag(out, 5, protobuf::rt::WIRE_VARINT);
                protobuf::rt::encode_varint(out, protobuf::rt::encode_zigzag32(v));
            }
            if let Some(v) = self.optional_sint64 {
                protobuf::rt::encode_tag(out, 6, protobuf::rt::WIRE_VARINT);
                protobuf::rt::encode_varint(out, protobuf::rt::encode_zigzag64(v));
            }
            if let Some(v) = self.optional_fixed32 {
                protobuf::rt::encode_tag(out, 7, protobuf::rt::WIRE_I32);
                (out).extend_from_slice(&(v).to_le_bytes());
            }
            if let Some(v) = self.optional_fixed64 {
                protobuf::rt::encode_tag(out, 8, protobuf::rt::WIRE_I64);
                (out).extend_from_slice(&(v).to_le_bytes());
            }
            if let Some(v) = self.optional_sfixed32 {
                protobuf::rt::encode_tag(out, 9, protobuf::rt::WIRE_I32);
                (out).extend_from_slice(&((v) as u32).to_le_bytes());
            }
            if let Some(v) = self.optional_sfixed64 {
                protobuf::rt::encode_tag(out, 10, protobuf::rt::WIRE_I64);
                (out).extend_from_slice(&((v) as u64).to_le_bytes());
            }
            if let Some(v) = self.optional_float {
                protobuf::rt::encode_tag(out, 11, protobuf::rt::WIRE_I32);
                (out).extend_from_slice(&(v).to_bits().to_le_bytes());
            }
            if let Some(v) = self.optional_double {
                protobuf::rt::encode_tag(out, 12, protobuf::rt::WIRE_I64);
                (out).extend_from_slice(&(v).to_bits().to_le_bytes());
            }
            if let Some(v) = self.optional_bool {
                protobuf::rt::encode_tag(out, 13, protobuf::rt::WIRE_VARINT);
                protobuf::rt::encode_varint(out, u64::from(v));
            }
            if let Some(s) = &self.optional_string {
                protobuf::rt::encode_len_field(out, 14, s.as_bytes());
            }
            if let Some(s) = &self.optional_bytes {
                protobuf::rt::encode_len_field(out, 15, s.as_bytes());
            }
            if let Some(s) = &self.optional_cord {
                protobuf::rt::encode_len_field(out, 16, s.as_bytes());
            }
            if let Some(p) = self.optional_nested_message.wire_bytes() {
                protobuf::rt::encode_len_header(out, 18, p.len() as u64);
                out.extend_from_slice(p);
            } else if let Some(m) = self.optional_nested_message.as_deref() {
                protobuf::rt::encode_len_header(out, 18, m.compute_size());
                m.write_to(out);
            }
            if let Some(p) = self.lazy_nested_message.wire_bytes() {
                protobuf::rt::encode_len_header(out, 19, p.len() as u64);
                out.extend_from_slice(p);
            } else if let Some(m) = self.lazy_nested_message.as_deref() {
                protobuf::rt::encode_len_header(out, 19, m.compute_size());
                m.write_to(out);
            }
            if let Some(v) = self.optional_nested_enum {
                protobuf::rt::encode_tag(out, 21, protobuf::rt::WIRE_VARINT);
                protobuf::rt::encode_varint(out, v as u64);
            }
            if self.singular_int32 != 0 {
                protobuf::rt::encode_tag(out, 22, protobuf::rt::WIRE_VARINT);
                protobuf::rt::encode_varint(out, self.singular_int32 as u64);
            }
            if self.singular_int64 != 0 {
                protobuf::rt::encode_tag(out, 23, protobuf::rt::WIRE_VARINT);
                protobuf::rt::encode_varint(out, self.singular_int64 as u64);
            }
            self.unknown.encode(out);
        }
    }
    protobuf::impl_typed_message!(
        TestProto3Optional,
        TestProto3OptionalView,
        TestProto3OptionalMut
    );
    #[derive(Clone, Debug, PartialEq)]
    pub struct NestedMessage {
        bb: Option<i32>,
        unknown: UnknownFields,
        cached_size: protobuf::rt::CachedSize,
    }
    impl Default for NestedMessage {
        fn default() -> Self {
            Self {
                bb: None,
                unknown: UnknownFields::default(),
                cached_size: protobuf::rt::CachedSize::default(),
            }
        }
    }
    impl NestedMessage {
        pub fn new() -> Self {
            Self::default()
        }
        pub const FULL_NAME: &'static str =
            "rust_unittest_proto3_optional.TestProto3Optional.NestedMessage";
        pub fn has_bb(&self) -> bool {
            self.bb.is_some()
        }
        pub fn bb(&self) -> i32 {
            self.bb.unwrap_or_default()
        }
        pub fn set_bb(&mut self, v: i32) {
            self.cached_size.dirty();
            self.bb = Some(v);
        }
        pub fn clear_bb(&mut self) {
            self.cached_size.dirty();
            self.bb = None;
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            let w = protobuf::rt::Wire::from_slice(data);
            let mut pos = 0;
            self.merge_inner(&w, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            let w = protobuf::rt::Wire::from_slice(data);
            let mut pos = 0;
            self.merge_inner(&w, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            wire: &protobuf::rt::Wire,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            wire: &protobuf::rt::Wire,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > protobuf::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = protobuf::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == protobuf::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match (n, w) {
                    (1, protobuf::rt::WIRE_VARINT) => {
                        self.bb = Some(protobuf::rt::decode_varint(data, pos)? as i32);
                    }
                    _ => self
                        .unknown
                        .fields
                        .push(protobuf::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            if let Some(v) = self.bb {
                n += protobuf::rt::tag_len(1, protobuf::rt::WIRE_VARINT)
                    + protobuf::rt::varint_len((v) as u64);
            }
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut Vec<u8>) {
            if let Some(v) = self.bb {
                protobuf::rt::encode_tag(out, 1, protobuf::rt::WIRE_VARINT);
                protobuf::rt::encode_varint(out, v as u64);
            }
            self.unknown.encode(out);
        }
    }
    protobuf::impl_typed_message!(NestedMessage, NestedMessageView, NestedMessageMut);
    #[derive(Clone, Debug, PartialEq)]
    pub struct TestProto3OptionalMessage {
        nested_message: protobuf::rt::LazyMsg<TestProto3OptionalMessageNestedMessage>,
        optional_nested_message: protobuf::rt::LazyMsg<TestProto3OptionalMessageNestedMessage>,
        unknown: UnknownFields,
        cached_size: protobuf::rt::CachedSize,
    }
    impl Default for TestProto3OptionalMessage {
        fn default() -> Self {
            Self {
                nested_message: Default::default(),
                optional_nested_message: Default::default(),
                unknown: UnknownFields::default(),
                cached_size: protobuf::rt::CachedSize::default(),
            }
        }
    }
    impl TestProto3OptionalMessage {
        pub fn new() -> Self {
            Self::default()
        }
        pub const FULL_NAME: &'static str =
            "rust_unittest_proto3_optional.TestProto3OptionalMessage";
        pub fn has_nested_message(&self) -> bool {
            self.nested_message.is_some()
        }
        pub fn nested_message(&self) -> Option<&TestProto3OptionalMessageNestedMessage> {
            self.nested_message.as_deref()
        }
        pub fn nested_message_view(
            &self,
        ) -> Option<TestProto3OptionalMessageNestedMessageView<'_>> {
            self.nested_message
                .as_deref()
                .map(TestProto3OptionalMessageNestedMessageView)
        }
        pub fn set_nested_message(&mut self, v: TestProto3OptionalMessageNestedMessage) {
            self.cached_size.dirty();
            self.nested_message = protobuf::rt::LazyMsg::from_owned(v);
        }
        pub fn nested_message_mut(&mut self) -> &mut TestProto3OptionalMessageNestedMessage {
            self.cached_size.dirty();
            self.nested_message.get_or_insert()
        }
        pub fn clear_nested_message(&mut self) {
            self.cached_size.dirty();
            self.nested_message.clear();
        }
        pub fn has_optional_nested_message(&self) -> bool {
            self.optional_nested_message.is_some()
        }
        pub fn optional_nested_message(&self) -> Option<&TestProto3OptionalMessageNestedMessage> {
            self.optional_nested_message.as_deref()
        }
        pub fn optional_nested_message_view(
            &self,
        ) -> Option<TestProto3OptionalMessageNestedMessageView<'_>> {
            self.optional_nested_message
                .as_deref()
                .map(TestProto3OptionalMessageNestedMessageView)
        }
        pub fn set_optional_nested_message(&mut self, v: TestProto3OptionalMessageNestedMessage) {
            self.cached_size.dirty();
            self.optional_nested_message = protobuf::rt::LazyMsg::from_owned(v);
        }
        pub fn optional_nested_message_mut(
            &mut self,
        ) -> &mut TestProto3OptionalMessageNestedMessage {
            self.cached_size.dirty();
            self.optional_nested_message.get_or_insert()
        }
        pub fn clear_optional_nested_message(&mut self) {
            self.cached_size.dirty();
            self.optional_nested_message.clear();
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            let w = protobuf::rt::Wire::from_slice(data);
            let mut pos = 0;
            self.merge_inner(&w, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            let w = protobuf::rt::Wire::from_slice(data);
            let mut pos = 0;
            self.merge_inner(&w, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            wire: &protobuf::rt::Wire,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            wire: &protobuf::rt::Wire,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > protobuf::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = protobuf::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == protobuf::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match (n, w) {
                    (1, protobuf::rt::WIRE_LEN) => {
                        let (s, e) = protobuf::rt::read_len_span(data, pos)?;
                        if self.nested_message.is_some() {
                            let mut ip = 0;
                            self.nested_message.get_or_insert().merge_inner(
                                &wire.window(s, e),
                                &mut ip,
                                depth + 1,
                                true,
                                None,
                            )?;
                        } else {
                            let mut inner = TestProto3OptionalMessageNestedMessage::default();
                            let mut ip = 0;
                            inner.merge_inner(
                                &wire.window(s, e),
                                &mut ip,
                                depth + 1,
                                true,
                                None,
                            )?;
                            self.nested_message =
                                protobuf::rt::LazyMsg::from_parsed(inner, wire.window(s, e));
                        }
                    }
                    (2, protobuf::rt::WIRE_LEN) => {
                        let (s, e) = protobuf::rt::read_len_span(data, pos)?;
                        if self.optional_nested_message.is_some() {
                            let mut ip = 0;
                            self.optional_nested_message.get_or_insert().merge_inner(
                                &wire.window(s, e),
                                &mut ip,
                                depth + 1,
                                true,
                                None,
                            )?;
                        } else {
                            let mut inner = TestProto3OptionalMessageNestedMessage::default();
                            let mut ip = 0;
                            inner.merge_inner(
                                &wire.window(s, e),
                                &mut ip,
                                depth + 1,
                                true,
                                None,
                            )?;
                            self.optional_nested_message =
                                protobuf::rt::LazyMsg::from_parsed(inner, wire.window(s, e));
                        }
                    }
                    _ => self
                        .unknown
                        .fields
                        .push(protobuf::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            if let Some(p) = self.nested_message.wire_bytes() {
                n += protobuf::rt::key_len_value_len(1, p.len() as u64);
            } else if let Some(m) = self.nested_message.as_deref() {
                n += protobuf::rt::key_len_value_len(1, m.compute_size());
            }
            if let Some(p) = self.optional_nested_message.wire_bytes() {
                n += protobuf::rt::key_len_value_len(2, p.len() as u64);
            } else if let Some(m) = self.optional_nested_message.as_deref() {
                n += protobuf::rt::key_len_value_len(2, m.compute_size());
            }
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut Vec<u8>) {
            if let Some(p) = self.nested_message.wire_bytes() {
                protobuf::rt::encode_len_header(out, 1, p.len() as u64);
                out.extend_from_slice(p);
            } else if let Some(m) = self.nested_message.as_deref() {
                protobuf::rt::encode_len_header(out, 1, m.compute_size());
                m.write_to(out);
            }
            if let Some(p) = self.optional_nested_message.wire_bytes() {
                protobuf::rt::encode_len_header(out, 2, p.len() as u64);
                out.extend_from_slice(p);
            } else if let Some(m) = self.optional_nested_message.as_deref() {
                protobuf::rt::encode_len_header(out, 2, m.compute_size());
                m.write_to(out);
            }
            self.unknown.encode(out);
        }
    }
    protobuf::impl_typed_message!(
        TestProto3OptionalMessage,
        TestProto3OptionalMessageView,
        TestProto3OptionalMessageMut
    );
    #[derive(Clone, Debug, PartialEq)]
    pub struct TestProto3OptionalMessageNestedMessage {
        s: protobuf::rt::LazyStr,
        unknown: UnknownFields,
        cached_size: protobuf::rt::CachedSize,
    }
    impl Default for TestProto3OptionalMessageNestedMessage {
        fn default() -> Self {
            Self {
                s: Default::default(),
                unknown: UnknownFields::default(),
                cached_size: protobuf::rt::CachedSize::default(),
            }
        }
    }
    impl TestProto3OptionalMessageNestedMessage {
        pub fn new() -> Self {
            Self::default()
        }
        pub const FULL_NAME: &'static str =
            "rust_unittest_proto3_optional.TestProto3OptionalMessage.NestedMessage";
        pub fn s(&self) -> &protobuf::ProtoStr {
            self.s.as_view()
        }
        pub fn set_s(&mut self, v: impl protobuf::IntoProxied<ProtoString>) {
            self.cached_size.dirty();
            self.s = protobuf::rt::LazyStr::owned(v.into_proxied());
        }
        fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            let w = protobuf::rt::Wire::from_slice(data);
            let mut pos = 0;
            self.merge_inner(&w, &mut pos, depth, true, None)
        }
        fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {
            let w = protobuf::rt::Wire::from_slice(data);
            let mut pos = 0;
            self.merge_inner(&w, &mut pos, depth, false, None)
        }
        fn merge_group(
            &mut self,
            wire: &protobuf::rt::Wire,
            pos: &mut usize,
            num: u32,
            depth: u32,
        ) -> Result<(), ParseError> {
            self.merge_inner(wire, pos, depth, false, Some(num))
        }
        fn merge_inner(
            &mut self,
            wire: &protobuf::rt::Wire,
            pos: &mut usize,
            depth: u32,
            enforce: bool,
            until: Option<u32>,
        ) -> Result<(), ParseError> {
            if depth > protobuf::RECURSION_LIMIT {
                return Err(ParseError::new("recursion limit exceeded"));
            }
            let _ = enforce;
            self.cached_size.dirty();
            let data = wire.as_slice();
            while *pos < data.len() {
                let (n, w) = protobuf::rt::decode_tag(data, pos)?;
                if let Some(g) = until {
                    if w == protobuf::rt::WIRE_EGROUP {
                        if n != g {
                            return Err(ParseError::new("mismatched end-group"));
                        }
                        return Ok(());
                    }
                }
                match (n, w) {
                    (1, protobuf::rt::WIRE_LEN) => {
                        let (s, e) = protobuf::rt::read_len_span(data, pos)?;
                        let b = &data[s..e];
                        std::str::from_utf8(b).map_err(|_| ParseError::new("invalid utf-8"))?;
                        self.s = protobuf::rt::LazyStr::from_wire(wire.window(s, e));
                    }
                    _ => self
                        .unknown
                        .fields
                        .push(protobuf::rt::capture_unknown(data, pos, n, w)?),
                }
            }
            if until.is_some() {
                return Err(ParseError::new("truncated group"));
            }
            Ok(())
        }
        fn compute_size(&self) -> u64 {
            if let Some(n) = self.cached_size.get() {
                return n;
            }
            let mut n = self.unknown.encoded_len();
            if !self.s.is_empty() {
                n += protobuf::rt::key_len_value_len(1, self.s.as_bytes().len() as u64);
            }
            self.cached_size.set(n);
            n
        }
        fn write_to(&self, out: &mut Vec<u8>) {
            if !self.s.is_empty() {
                protobuf::rt::encode_len_field(out, 1, self.s.as_bytes());
            }
            self.unknown.encode(out);
        }
    }
    protobuf::impl_typed_message!(
        TestProto3OptionalMessageNestedMessage,
        TestProto3OptionalMessageNestedMessageView,
        TestProto3OptionalMessageNestedMessageMut
    );
}
pub use __gen::*;
