//! A gRPC service that depends on [`pbrs_grpc`] as an ordinary crate.
//!
//! `proto/hello.proto` is compiled by `build.rs` with
//! [`pbrs::codegen::Config::emit_kernel_stubs`]. The binary serves the greeter
//! together with `grpc.health.v1` and `grpc.reflection.v1` on loopback, then
//! calls `SayHello`.

#![allow(
    missing_docs,
    unreachable_pub,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::disallowed_methods,
    reason = "example crate"
)]

mod proto {
    #![allow(
        missing_docs,
        unused,
        unreachable_pub,
        reason = "generated by protoc-gen-pbrs"
    )]
    include!(concat!(env!("OUT_DIR"), "/hello.rs"));
}

use pbrs_grpc::health::service as health_service;
use pbrs_grpc::reflection::service as reflection_service;
use pbrs_grpc::{Channel, Request, Response, Router, Status};
use proto::{Greeter, GreeterClient, GreeterServer, HelloReply, HelloRequest, FILE_DESCRIPTOR_SET};
use std::net::SocketAddr;
use std::time::Duration;
use tokio::net::TcpListener;

struct Live {
    addr: SocketAddr,
    _server: tokio::task::JoinHandle<()>,
}

struct MyGreeter;

impl Greeter for MyGreeter {
    async fn say_hello(
        &self,
        request: Request<HelloRequest>,
    ) -> Result<Response<HelloReply>, Status> {
        let mut reply = HelloReply::new();
        reply.set_message(format!("hello {}", request.get_ref().name()));
        Ok(Response::new(reply))
    }
}

async fn serve() -> Result<Live, Status> {
    let listener = TcpListener::bind(SocketAddr::from(([127, 0, 0, 1], 0))).await?;
    let addr = listener.local_addr()?;
    let (health, reporter) = health_service();
    reporter.set_serving(GreeterServer::<MyGreeter>::NAME);
    let reflection = reflection_service([FILE_DESCRIPTOR_SET])?;
    let _server = tokio::spawn(async move {
        Router::new()
            .add_service(health)
            .add_service(reflection)
            .add_service(GreeterServer::new(MyGreeter))
            .serve_listener(listener)
            .await
            .ok();
    });
    Ok(Live { addr, _server })
}

async fn channel(addr: SocketAddr) -> Result<Channel, Status> {
    let mut last = Status::unavailable("connect");
    for _ in 0..80 {
        match Channel::connect(addr).await {
            Ok(ch) => return Ok(ch),
            Err(e) => {
                last = e;
                tokio::time::sleep(Duration::from_millis(5)).await;
            }
        }
    }
    Err(last)
}

async fn greet(ch: &Channel, name: &str) -> Result<String, Status> {
    let mut req = HelloRequest::new();
    req.set_name(name);
    let reply = GreeterClient::new(ch.clone())
        .say_hello(Request::new(req))
        .await?;
    Ok(reply
        .get_ref()
        .message()
        .to_str()
        .unwrap_or_default()
        .to_owned())
}

/// Bind loopback, serve, call `SayHello`, return the reply text.
pub async fn run() -> Result<String, Status> {
    let live = serve().await?;
    greet(&channel(live.addr).await?, "world").await
}

#[cfg(test)]
mod tests {
    use super::*;
    use pbrs_grpc::health::{HealthCheckRequest, HealthClient, ServingStatus};
    use pbrs_grpc::reflection::{ServerReflectionClient, ServerReflectionRequest};

    #[tokio::test]
    async fn generated_stubs_say_hello() {
        assert_eq!(run().await.unwrap(), "hello world");
    }

    #[tokio::test]
    async fn health_reports_the_greeter() {
        let live = serve().await.unwrap();
        let client = HealthClient::new(channel(live.addr).await.unwrap());
        let mut req = HealthCheckRequest::new();
        req.set_service(GreeterServer::<MyGreeter>::NAME);
        let status = client
            .check(Request::new(req))
            .await
            .unwrap()
            .into_inner()
            .status();
        assert_eq!(status, ServingStatus::Serving);
    }

    #[tokio::test]
    async fn reflection_lists_the_greeter() {
        let live = serve().await.unwrap();
        let client = ServerReflectionClient::new(channel(live.addr).await.unwrap());
        let (tx, call) = client.server_reflection_info(Request::new(()));
        let mut inbound = call.await.unwrap().into_inner();
        let mut req = ServerReflectionRequest::new();
        req.set_list_services("");
        tx.send(req).await.unwrap();
        tx.close();
        let resp = inbound.message().await.unwrap().unwrap();
        let names: Vec<String> = resp
            .list_services_response()
            .service()
            .iter()
            .map(|s| s.name().to_str().unwrap_or("").to_owned())
            .collect();
        assert!(
            names.contains(&GreeterServer::<MyGreeter>::NAME.to_owned()),
            "{names:?}"
        );
    }
}
