// Portions of this fixture are adapted from the Tonic helloworld example.
//
// Copyright (c) 2025 Lucio Franco
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

pub mod hello_world {
    #![allow(missing_docs, unused, reason = "generated by pbrs for this fixture")]
    include!(concat!(env!("OUT_DIR"), "/helloworld/helloworld.rs"));
}

use hello_world::{Greeter, GreeterClient, GreeterServer, HelloReply, HelloRequest};
use pbrs_grpc::compat::{Request, Response, Status};

#[derive(Default)]
pub struct MyGreeter {}

impl Greeter for MyGreeter {
    async fn say_hello(
        &self,
        request: Request<HelloRequest>,
    ) -> Result<Response<HelloReply>, Status> {
        let mut reply = HelloReply::new();
        reply.set_message(format!("Hello {}!", request.into_inner().name()));
        Ok(Response::new(reply))
    }
}

#[tokio::main]
async fn main() -> Result<(), Status> {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let addr = listener.local_addr().unwrap();
    let greeter = MyGreeter::default();

    let server_task =
        tokio::spawn(async move { GreeterServer::new(greeter).serve_listener(listener).await });

    let mut client = GreeterClient::connect(addr).await?;

    let mut request = HelloRequest::new();
    request.set_name("Tonic");

    let response = client.say_hello(Request::new(request)).await?;
    assert_eq!(response.into_inner().message(), "Hello Tonic!");

    server_task.abort();
    println!("helloworld compat ok");
    Ok(())
}
