// Portions of this fixture are adapted from the Tonic routeguide example.
//
// Copyright (c) 2025 Lucio Franco
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

use std::collections::HashMap;
use std::sync::Arc;
use std::time::Instant;

pub mod routeguide {
    #![allow(missing_docs, unused, reason = "generated by pbrs for this fixture")]
    include!(concat!(env!("OUT_DIR"), "/routeguide/route_guide.rs"));
}

use pbrs_grpc::compat::{self, Request, Response, Status, Streaming};
use routeguide::{
    Feature, Point, Rectangle, RouteGuide, RouteGuideClient, RouteGuideServer, RouteNote,
    RouteSummary,
};

#[derive(Debug)]
pub struct RouteGuideService {
    features: Arc<Vec<Feature>>,
}

impl RouteGuide for RouteGuideService {
    type ListFeaturesStream = compat::Iter<Result<Feature, Status>>;
    type RouteChatStream = compat::Iter<Result<RouteNote, Status>>;

    async fn get_feature(&self, request: Request<Point>) -> Result<Response<Feature>, Status> {
        for feature in &self.features[..] {
            if same_point(feature.location(), request.get_ref()) {
                return Ok(Response::new(feature.clone()));
            }
        }

        Ok(Response::new(Feature::default()))
    }

    async fn list_features(
        &self,
        request: Request<Rectangle>,
    ) -> Result<Response<Self::ListFeaturesStream>, Status> {
        let items = self
            .features
            .iter()
            .filter(|feature| in_range(feature.location(), request.get_ref()))
            .cloned()
            .map(Ok)
            .collect::<Vec<_>>();

        Ok(Response::new(compat::iter(items)))
    }

    async fn record_route(
        &self,
        request: Request<Streaming<Point>>,
    ) -> Result<Response<RouteSummary>, Status> {
        let mut stream = request.into_inner();

        let mut summary = RouteSummary::default();
        let mut last_point = None;
        let now = Instant::now();

        while let Some(point) = stream.message().await? {
            summary.set_point_count(summary.point_count() + 1);

            for feature in &self.features[..] {
                if same_point(feature.location(), &point) {
                    summary.set_feature_count(summary.feature_count() + 1);
                }
            }

            if let Some(ref last_point) = last_point {
                summary.set_distance(summary.distance() + calc_distance(last_point, &point));
            }

            last_point = Some(point);
        }

        summary.set_elapsed_time(now.elapsed().as_secs() as i32);

        Ok(Response::new(summary))
    }

    async fn route_chat(
        &self,
        request: Request<Streaming<RouteNote>>,
    ) -> Result<Response<Self::RouteChatStream>, Status> {
        let mut notes: HashMap<(i32, i32), Vec<RouteNote>> = HashMap::new();
        let mut stream = request.into_inner();
        let mut output = Vec::new();

        while let Some(note) = stream.message().await? {
            let location = note.location().clone();
            let key = (location.latitude(), location.longitude());

            let location_notes = notes.entry(key).or_default();
            location_notes.push(note);

            for note in location_notes {
                output.push(Ok(note.clone()));
            }
        }

        Ok(Response::new(compat::iter(output)))
    }
}

#[tokio::main]
async fn main() -> Result<(), Status> {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let addr = listener.local_addr().unwrap();
    let route_guide = RouteGuideService {
        features: Arc::new(load_features()),
    };
    let server_task =
        tokio::spawn(async move { RouteGuideServer::new(route_guide).serve_listener(listener).await });

    let mut client = RouteGuideClient::connect(addr).await?;

    let response = client.get_feature(Request::new(point(409_146_138, -746_188_906))).await?;
    assert_eq!(response.into_inner().name(), "Berkshire Valley Management Area Trail");

    let mut rect = Rectangle::new();
    rect.set_lo(point(400_000_000, -750_000_000));
    rect.set_hi(point(420_000_000, -730_000_000));
    let mut features = client.list_features(Request::new(rect)).await?.into_inner();
    assert!(features.message().await?.is_some());

    let summary = client
        .record_route(compat::iter(vec![
            point(409_146_138, -746_188_906),
            point(407_838_351, -746_143_763),
        ]))
        .await?
        .into_inner();
    assert_eq!(summary.point_count(), 2);
    assert_eq!(summary.feature_count(), 2);
    assert!(summary.distance() > 0);

    let mut route_notes = client
        .route_chat(compat::iter(vec![
            note(point(409_146_138, -746_188_906), "first message"),
            note(point(409_146_138, -746_188_906), "second message"),
        ]))
        .await?
        .into_inner();
    assert_eq!(route_notes.message().await?.unwrap().message(), "first message");
    assert_eq!(route_notes.message().await?.unwrap().message(), "first message");
    assert_eq!(route_notes.message().await?.unwrap().message(), "second message");

    server_task.abort();
    println!("routeguide compat ok");
    Ok(())
}

fn load_features() -> Vec<Feature> {
    vec![
        feature(
            "Berkshire Valley Management Area Trail",
            point(409_146_138, -746_188_906),
        ),
        feature(
            "Patriots Path, Mendham, NJ 07945, USA",
            point(407_838_351, -746_143_763),
        ),
        feature("outside rectangle", point(0, 0)),
    ]
}

fn point(latitude: i32, longitude: i32) -> Point {
    let mut point = Point::new();
    point.set_latitude(latitude);
    point.set_longitude(longitude);
    point
}

fn feature(name: &str, location: Point) -> Feature {
    let mut feature = Feature::new();
    feature.set_name(name);
    feature.set_location(location);
    feature
}

fn note(location: Point, message: &str) -> RouteNote {
    let mut note = RouteNote::new();
    note.set_location(location);
    note.set_message(message);
    note
}

fn same_point(a: &Point, b: &Point) -> bool {
    a.latitude() == b.latitude() && a.longitude() == b.longitude()
}

fn in_range(point: &Point, rect: &Rectangle) -> bool {
    use std::cmp;

    let lo = rect.lo();
    let hi = rect.hi();

    let left = cmp::min(lo.longitude(), hi.longitude());
    let right = cmp::max(lo.longitude(), hi.longitude());
    let top = cmp::max(lo.latitude(), hi.latitude());
    let bottom = cmp::min(lo.latitude(), hi.latitude());

    point.longitude() >= left
        && point.longitude() <= right
        && point.latitude() >= bottom
        && point.latitude() <= top
}

/// Calculates the distance between two points using the "haversine" formula.
/// This code was taken from http://www.movable-type.co.uk/scripts/latlong.html.
fn calc_distance(p1: &Point, p2: &Point) -> i32 {
    const CORD_FACTOR: f64 = 1e7;
    const R: f64 = 6_371_000.0; // meters

    let lat1 = p1.latitude() as f64 / CORD_FACTOR;
    let lat2 = p2.latitude() as f64 / CORD_FACTOR;
    let lng1 = p1.longitude() as f64 / CORD_FACTOR;
    let lng2 = p2.longitude() as f64 / CORD_FACTOR;

    let lat_rad1 = lat1.to_radians();
    let lat_rad2 = lat2.to_radians();

    let delta_lat = (lat2 - lat1).to_radians();
    let delta_lng = (lng2 - lng1).to_radians();

    let a = (delta_lat / 2f64).sin() * (delta_lat / 2f64).sin()
        + (lat_rad1).cos() * (lat_rad2).cos() * (delta_lng / 2f64).sin() * (delta_lng / 2f64).sin();

    let c = 2f64 * a.sqrt().atan2((1f64 - a).sqrt());

    (R * c) as i32
}
