syntax = "proto3";
package grpc.testing;

message BoolValue {
  bool value = 1;
}

enum PayloadType {
  COMPRESSABLE = 0;
}

message Payload {
  PayloadType type = 1;
  bytes body = 2;
}

message EchoStatus {
  int32 code = 1;
  string message = 2;
}

enum GrpclbRouteType {
  GRPCLB_ROUTE_TYPE_UNKNOWN = 0;
  GRPCLB_ROUTE_TYPE_FALLBACK = 1;
  GRPCLB_ROUTE_TYPE_BACKEND = 2;
}

message TestOrcaReport {
  double cpu_utilization = 1;
  double memory_utilization = 2;
  map<string, double> request_cost = 3;
  map<string, double> utilization = 4;
}

message SimpleRequest {
  PayloadType response_type = 1;
  int32 response_size = 2;
  Payload payload = 3;
  bool fill_username = 4;
  bool fill_oauth_scope = 5;
  BoolValue response_compressed = 6;
  EchoStatus response_status = 7;
  BoolValue expect_compressed = 8;
  bool fill_server_id = 9;
  bool fill_grpclb_route_type = 10;
  TestOrcaReport orca_per_query_report = 11;
}

message SimpleResponse {
  Payload payload = 1;
  string username = 2;
  string oauth_scope = 3;
  string server_id = 4;
  GrpclbRouteType grpclb_route_type = 5;
  string hostname = 6;
}

message StreamingInputCallRequest {
  Payload payload = 1;
  BoolValue expect_compressed = 2;
}

message StreamingInputCallResponse {
  int32 aggregated_payload_size = 1;
}

message ResponseParameters {
  int32 size = 1;
  int32 interval_us = 2;
  BoolValue compressed = 3;
  BoolValue fill_peer_socket_address = 4;
}

message StreamingOutputCallRequest {
  PayloadType response_type = 1;
  repeated ResponseParameters response_parameters = 2;
  Payload payload = 3;
  EchoStatus response_status = 7;
  TestOrcaReport orca_oob_report = 8;
}

message StreamingOutputCallResponse {
  Payload payload = 1;
  string peer_socket_address = 2;
}
