//! Native pbrs-grpc stubs for prost-build message modules.
//!
//! Use this next to `prost-build`: have prost-build emit prost messages and a
//! `FileDescriptorSet`, then call [`compile_descriptor_set`] to emit native
//! transport stubs that reference those prost message types.

use super::{
    CodegenError, clean_proto_target_name, extract_proto_file_name_from_blob, file_matches,
    normalize_proto_path_str, to_snake, write_file_atomic_if_changed,
};
use crate::dynamic::{DescriptorPool, MethodDescriptor, ServiceDescriptor};
use crate::wire::{WIRE_LEN, decode_tag, read_len_bytes};
use std::fmt::Write as _;
use std::path::Path;

const G: &str = "::pbrs_grpc";
const P: &str = "::pbrs_grpc::codec::prost";

/// Generate prost-message native stubs from an encoded `FileDescriptorSet`.
///
/// The generated file is intended to be included in the same Rust module as
/// prost-build's message output for the same proto file.
pub fn generate_from_file_descriptor_set(
    fds: &[u8],
    files_to_generate: &[impl AsRef<str>],
) -> Result<Vec<(String, String)>, CodegenError> {
    let pool = DescriptorPool::from_file_descriptor_set(fds).map_err(|_| {
        CodegenError::MalformedDescriptor {
            detail: "failed to parse FileDescriptorSet for prost stubs".to_string(),
            path: None,
        }
    })?;
    let targets: Vec<String> = files_to_generate
        .iter()
        .map(|file| clean_proto_target_name(file.as_ref()))
        .collect();
    let mut out = Vec::new();
    for target in &targets {
        let wanted = std::iter::once(target.clone()).collect();
        let mut services: Vec<_> = pool
            .collect_services()
            .into_iter()
            .filter(|svc| file_matches(&wanted, &svc.file_name))
            .collect();
        services.sort_by(|a, b| a.full_name.cmp(&b.full_name));
        if services.is_empty() {
            continue;
        }
        let mut src = String::from(
            "// @generated by pbrs prost_stubs\n\
#[allow(unused, reason = \"generated prost pbrs-grpc stubs may not exercise every helper\")]\n\
#[allow(clippy::all, reason = \"generated prost pbrs-grpc stubs\")]\n\
#[allow(clippy::pedantic, reason = \"generated prost pbrs-grpc stubs\")]\n",
        );
        src.push_str("use std::sync::Arc;\n\n");
        for svc in &services {
            emit_service(&mut src, svc);
        }
        let rel = output_name(target);
        out.push((rel, src));
    }
    out.sort_by(|a, b| a.0.cmp(&b.0));
    Ok(out)
}

/// Write prost native stubs from a descriptor set into `out_dir`.
///
/// This is deliberately independent of [`Config`](super::Config) so a
/// consumer build script can run `prost_build::Config::compile_protos` first
/// and then call this helper with the same descriptor set.
pub fn compile_descriptor_set(
    descriptor_set: impl AsRef<Path>,
    files_to_generate: &[impl AsRef<str>],
    out_dir: impl AsRef<Path>,
) -> Result<(), CodegenError> {
    let descriptor_set = descriptor_set.as_ref();
    let bytes = std::fs::read(descriptor_set).map_err(|source| CodegenError::Io {
        path: descriptor_set.to_path_buf(),
        source,
    })?;
    validate_fds_has_file_names(&bytes)?;
    let out_dir = out_dir.as_ref();
    std::fs::create_dir_all(out_dir).map_err(|source| CodegenError::UnwritableOutput {
        path: out_dir.to_path_buf(),
        source,
    })?;
    for (name, src) in generate_from_file_descriptor_set(&bytes, files_to_generate)? {
        write_file_atomic_if_changed(&out_dir.join(name), &src)?;
    }
    Ok(())
}

fn validate_fds_has_file_names(fds: &[u8]) -> Result<(), CodegenError> {
    let mut pos = 0;
    let mut found = false;
    while pos < fds.len() {
        let (n, w) = decode_tag(fds, &mut pos).map_err(|_| CodegenError::MalformedDescriptor {
            detail: "failed to decode FileDescriptorSet wire tag".to_string(),
            path: None,
        })?;
        if n == 1 && w == WIRE_LEN {
            let blob =
                read_len_bytes(fds, &mut pos).map_err(|_| CodegenError::MalformedDescriptor {
                    detail: "failed to read FileDescriptorProto".to_string(),
                    path: None,
                })?;
            if extract_proto_file_name_from_blob(blob).is_empty() {
                return Err(CodegenError::MalformedDescriptor {
                    detail: "FileDescriptorProto is malformed or has no file name".to_string(),
                    path: None,
                });
            }
            found = true;
        } else {
            crate::wire::skip_field(fds, &mut pos, w).map_err(|_| {
                CodegenError::MalformedDescriptor {
                    detail: "failed to skip field in FileDescriptorSet".to_string(),
                    path: None,
                }
            })?;
        }
    }
    if found {
        Ok(())
    } else {
        Err(CodegenError::MalformedDescriptor {
            detail: "FileDescriptorSet contains no files".to_string(),
            path: None,
        })
    }
}

fn output_name(target: &str) -> String {
    let norm = normalize_proto_path_str(target);
    if let Some(stripped) = norm.strip_suffix(".proto") {
        format!("{stripped}.pbrs_grpc.rs")
    } else {
        format!("{norm}.pbrs_grpc.rs")
    }
}

fn prost_type_path(full_name: &str) -> String {
    let key = full_name.trim_start_matches('.');
    let last = key.rsplit('.').next().unwrap_or(key);
    super::ident_last(last)
}

fn service_ident(full_name: &str) -> String {
    super::ident_last(full_name.trim_start_matches('.'))
}

fn emit_service(src: &mut String, svc: &ServiceDescriptor) {
    let service = service_ident(&svc.full_name);
    let server = format!("{service}Server");
    let client = format!("{service}Client");
    let full_name = &svc.full_name;
    let path_prefix = format!("/{full_name}");
    emit_trait(src, &service, svc);
    emit_server(src, &service, &server, full_name, svc);
    emit_client(src, &client, svc, &path_prefix);
}

fn emit_trait(src: &mut String, trait_name: &str, svc: &ServiceDescriptor) {
    let _ = writeln!(src, "pub trait {trait_name}: Send + Sync + 'static {{");
    for method in sorted_methods(svc) {
        let fn_name = to_snake(&method.name);
        let req = prost_type_path(&method.input_type);
        let resp = prost_type_path(&method.output_type);
        match (method.client_streaming, method.server_streaming) {
            (false, false) => {
                let _ = writeln!(
                    src,
                    "    fn {fn_name}(&self, request: {G}::Request<{req}>) -> impl ::core::future::Future<Output = ::core::result::Result<{G}::Response<{resp}>, {G}::Status>> + Send {{"
                );
            }
            (true, false) => {
                let _ = writeln!(
                    src,
                    "    fn {fn_name}(&self, request: {G}::Request<{P}::Streaming<{req}>>) -> impl ::core::future::Future<Output = ::core::result::Result<{G}::Response<{resp}>, {G}::Status>> + Send {{"
                );
            }
            (false, true) => {
                let _ = writeln!(
                    src,
                    "    fn {fn_name}(&self, request: {G}::Request<{req}>) -> impl ::core::future::Future<Output = ::core::result::Result<{G}::Response<{P}::Streaming<{resp}>>, {G}::Status>> + Send {{"
                );
            }
            (true, true) => {
                let _ = writeln!(
                    src,
                    "    fn {fn_name}(&self, request: {G}::Request<{P}::Streaming<{req}>>) -> impl ::core::future::Future<Output = ::core::result::Result<{G}::Response<{P}::Streaming<{resp}>>, {G}::Status>> + Send {{"
                );
            }
        }
        let _ = writeln!(src, "        async move {{");
        let _ = writeln!(src, "            drop(request);");
        let _ = writeln!(
            src,
            "            ::core::result::Result::Err({G}::Status::unimplemented(\"method {}/{} not implemented\"))",
            svc.full_name, method.name
        );
        let _ = writeln!(src, "        }}");
        let _ = writeln!(src, "    }}");
    }
    let _ = writeln!(src, "}}\n");
}

fn emit_server(
    src: &mut String,
    trait_name: &str,
    server: &str,
    full_name: &str,
    svc: &ServiceDescriptor,
) {
    let _ = writeln!(src, "#[derive(Clone)]");
    let _ = writeln!(src, "pub struct {server}<T> {{ inner: Arc<T> }}");
    let _ = writeln!(src, "impl<T: {trait_name}> {server}<T> {{");
    let _ = writeln!(
        src,
        "    pub fn new(inner: T) -> Self {{ Self {{ inner: Arc::new(inner) }} }}"
    );
    let _ = writeln!(src, "}}\n");
    let _ = writeln!(src, "impl<T: {trait_name}> {G}::Service for {server}<T> {{");
    let _ = writeln!(src, "    const NAME: &'static str = \"{full_name}\";");
    let _ = writeln!(src, "    async fn call(&self, rpc: {G}::Rpc) {{");
    let _ = writeln!(src, "        match rpc.method() {{");
    for method in sorted_methods(svc) {
        let fn_name = to_snake(&method.name);
        let req = prost_type_path(&method.input_type);
        let _ = writeln!(src, "            \"{}\" => {{", method.name);
        let _ = writeln!(src, "                let inner = Arc::clone(&self.inner);");
        match (method.client_streaming, method.server_streaming) {
            (false, false) => {
                let _ = writeln!(
                    src,
                    "                rpc.unary(move |request: {G}::Request<{P}::Message<{req}>>| async move {{"
                );
                let _ = writeln!(
                    src,
                    "                    inner.{fn_name}(request.map({P}::Message::into_inner)).await.map({P}::response_to_native)"
                );
                let _ = writeln!(src, "                }}).await;");
            }
            (true, false) => {
                let _ = writeln!(
                    src,
                    "                rpc.client_streaming(move |request: {G}::Request<{G}::Streaming<{P}::Message<{req}>>>| async move {{"
                );
                let _ = writeln!(
                    src,
                    "                    inner.{fn_name}(request.map({P}::Streaming::from_native)).await.map({P}::response_to_native)"
                );
                let _ = writeln!(src, "                }}).await;");
            }
            (false, true) => {
                let _ = writeln!(
                    src,
                    "                rpc.server_streaming(move |request: {G}::Request<{P}::Message<{req}>>| async move {{"
                );
                let _ = writeln!(
                    src,
                    "                    inner.{fn_name}(request.map({P}::Message::into_inner)).await.map({P}::streaming_response_to_native)"
                );
                let _ = writeln!(src, "                }}).await;");
            }
            (true, true) => {
                let _ = writeln!(
                    src,
                    "                rpc.bidi_streaming(move |request: {G}::Request<{G}::Streaming<{P}::Message<{req}>>>| async move {{"
                );
                let _ = writeln!(
                    src,
                    "                    inner.{fn_name}(request.map({P}::Streaming::from_native)).await.map({P}::streaming_response_to_native)"
                );
                let _ = writeln!(src, "                }}).await;");
            }
        }
        let _ = writeln!(src, "            }}");
    }
    let _ = writeln!(src, "            _ => rpc.unimplemented(),");
    let _ = writeln!(src, "        }}");
    let _ = writeln!(src, "    }}");
    let _ = writeln!(src, "}}\n");
}

fn emit_client(src: &mut String, client: &str, svc: &ServiceDescriptor, path_prefix: &str) {
    let _ = writeln!(src, "#[derive(Clone, Debug)]");
    let _ = writeln!(src, "pub struct {client} {{ channel: {G}::Channel }}");
    let _ = writeln!(src, "impl {client} {{");
    let _ = writeln!(
        src,
        "    pub fn new(channel: {G}::Channel) -> Self {{ Self {{ channel }} }}"
    );
    for method in sorted_methods(svc) {
        emit_client_method(src, &method, path_prefix);
    }
    let _ = writeln!(src, "}}\n");
}

fn emit_client_method(src: &mut String, method: &MethodDescriptor, path_prefix: &str) {
    let fn_name = to_snake(&method.name);
    let path = format!("{path_prefix}/{}", method.name);
    let req = prost_type_path(&method.input_type);
    let resp = prost_type_path(&method.output_type);
    match (method.client_streaming, method.server_streaming) {
        (false, false) => {
            let _ = writeln!(
                src,
                "    pub async fn {fn_name}(&self, request: {G}::Request<{req}>) -> ::core::result::Result<{G}::Response<{resp}>, {G}::Status> {{"
            );
            let _ = writeln!(
                src,
                "        self.channel.unary::<{P}::Message<{req}>, {P}::Message<{resp}>>(\"{path}\", request.map({P}::Message::new)).await.map({P}::response_from_native)"
            );
            let _ = writeln!(src, "    }}");
        }
        (true, false) => {
            let _ = writeln!(
                src,
                "    pub fn {fn_name}(&self, request: {G}::Request<()>) -> ({P}::StreamSender<{req}>, impl ::core::future::Future<Output = ::core::result::Result<{G}::Response<{resp}>, {G}::Status>> + Send + 'static) {{"
            );
            let _ = writeln!(
                src,
                "        let (sender, call) = self.channel.client_streaming::<{P}::Message<{req}>, {P}::Message<{resp}>>(\"{path}\", request);"
            );
            let _ = writeln!(
                src,
                "        let fut = async move {{ call.await.map({P}::response_from_native) }};"
            );
            let _ = writeln!(src, "        ({P}::StreamSender::from_native(sender), fut)");
            let _ = writeln!(src, "    }}");
        }
        (false, true) => {
            let _ = writeln!(
                src,
                "    pub async fn {fn_name}(&self, request: {G}::Request<{req}>) -> ::core::result::Result<{G}::Response<{P}::Streaming<{resp}>>, {G}::Status> {{"
            );
            let _ = writeln!(
                src,
                "        self.channel.server_streaming::<{P}::Message<{req}>, {P}::Message<{resp}>>(\"{path}\", request.map({P}::Message::new)).await.map({P}::streaming_response_from_native)"
            );
            let _ = writeln!(src, "    }}");
        }
        (true, true) => {
            let _ = writeln!(
                src,
                "    pub fn {fn_name}(&self, request: {G}::Request<()>) -> ({P}::StreamSender<{req}>, impl ::core::future::Future<Output = ::core::result::Result<{G}::Response<{P}::Streaming<{resp}>>, {G}::Status>> + Send + 'static) {{"
            );
            let _ = writeln!(
                src,
                "        let (sender, call) = self.channel.bidi::<{P}::Message<{req}>, {P}::Message<{resp}>>(\"{path}\", request);"
            );
            let _ = writeln!(
                src,
                "        let fut = async move {{ call.await.map({P}::streaming_response_from_native) }};"
            );
            let _ = writeln!(src, "        ({P}::StreamSender::from_native(sender), fut)");
            let _ = writeln!(src, "    }}");
        }
    }
}

fn sorted_methods(svc: &ServiceDescriptor) -> Vec<MethodDescriptor> {
    let mut methods = svc.methods.clone();
    methods.sort_by(|a, b| a.name.cmp(&b.name));
    methods
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn prost_helloworld_stubs_cover_all_shapes() {
        let root = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let fds = std::fs::read(root.join("pbrs-grpc/proto/hello.fds")).expect("hello fds");
        let files = generate_from_file_descriptor_set(&fds, &["hello.proto"]).expect("stubs");
        let src = files
            .iter()
            .find(|(name, _)| name == "hello.pbrs_grpc.rs")
            .map(|(_, src)| src.as_str())
            .expect("hello prost stubs");
        for needle in [
            "pub trait Greeter",
            "pub struct GreeterServer",
            "pub struct GreeterClient",
            "pub async fn say_hello",
            "pub fn client_hello",
            "pub async fn server_hello",
            "pub fn stream_hello",
            "::pbrs_grpc::codec::prost::Message<HelloRequest>",
            "::pbrs_grpc::codec::prost::Streaming<HelloReply>",
        ] {
            assert!(src.contains(needle), "{needle}\n{src}");
        }
    }
}
