//! Generate field-wise typed messages (not DynamicMessage wrappers, not upb).

use crate::dynamic::{
    Cardinality, DescriptorPool, FieldDescriptor, FieldType, MessageDescriptor, MethodDescriptor,
    Presence, ServiceDescriptor,
};
use crate::error::ParseError;
use crate::wire::{self, decode_tag, encode_len_field, encode_varint, read_len_bytes, WIRE_LEN};
use std::cell::RefCell;
use std::fmt::Write as _;

thread_local! {
    static IDENTS: RefCell<std::collections::BTreeMap<String, String>> =
        const { RefCell::new(std::collections::BTreeMap::new()) };
    static FIELD_IDENTS: RefCell<std::collections::BTreeMap<u32, String>> =
        const { RefCell::new(std::collections::BTreeMap::new()) };
}

pub fn generate_from_code_generator_request(
    bytes: &[u8],
) -> Result<Vec<(String, String)>, ParseError> {
    let mut files_to_generate = Vec::new();
    let mut proto_files = Vec::new();
    let mut pos = 0;
    while pos < bytes.len() {
        let (n, w) = decode_tag(bytes, &mut pos)?;
        match (n, w) {
            (1, WIRE_LEN) => {
                let s = read_len_bytes(bytes, &mut pos)?;
                files_to_generate.push(String::from_utf8_lossy(s).into_owned());
            }
            (15, WIRE_LEN) => {
                let blob = read_len_bytes(bytes, &mut pos)?.to_vec();
                proto_files.push(blob);
            }
            _ => wire::skip_field(bytes, &mut pos, w)?,
        }
    }
    let mut fds = Vec::new();
    for blob in &proto_files {
        encode_len_field(&mut fds, 1, blob);
    }
    let pool = DescriptorPool::from_file_descriptor_set(&fds)?;
    let names: Vec<String> = pool.collect_names();
    let targets = if files_to_generate.is_empty() {
        vec!["generated.proto".into()]
    } else {
        files_to_generate.clone()
    };
    let mut out_files = Vec::new();
    for target in &targets {
        let wanted: std::collections::BTreeSet<String> = std::iter::once(target.clone()).collect();
        let target_is_wkt = wanted.iter().any(|w| {
            let s = w.replace('\\', "/");
            s.contains("google/protobuf/") && !s.contains("test_messages")
        });
        let mut src = String::from(
            "// @generated by protoc-gen-pure-protobuf\n#[allow(unused, non_snake_case, non_camel_case_types, clippy::all)]\nmod __gen {\n#![allow(unused, non_snake_case, non_camel_case_types, clippy::all)]\nuse protobuf::prelude::*;\nuse protobuf::{Map, MapMut, MapView, ParseError, ProtoBytes, ProtoString, Repeated, RepeatedMut, RepeatedView, SerializeError};\nuse protobuf::UnknownFields;\n\n",
        );
        if std::env::var("PURE_PROTOBUF_SHARED_POOL").as_deref() == Ok("1") {
            src.push_str(
                "fn generated_pool() -> std::sync::Arc<protobuf::DescriptorPool> {\n    protobuf::gencode::conformance_pool()\n}\n\n",
            );
        } else {
            emit_fds(&mut src, &fds);
            src.push_str(
                "fn generated_pool() -> std::sync::Arc<protobuf::DescriptorPool> {\n    static P: std::sync::OnceLock<std::sync::Arc<protobuf::DescriptorPool>> = std::sync::OnceLock::new();\n    P.get_or_init(|| {\n        std::sync::Arc::new(protobuf::DescriptorPool::from_file_descriptor_set(FILE_DESCRIPTOR_SET).expect(\"fds\"))\n    }).clone()\n}\n\n",
            );
        }
        let mut emit_names = Vec::new();
        for name in &names {
            let Some(desc) = pool.get_message(name) else {
                continue;
            };
            if desc.is_map_entry {
                continue;
            }
            let wkt = desc.full_name.starts_with("google.protobuf.");
            if !file_matches(&wanted, &desc.file_name) && !(wkt && !target_is_wkt) {
                continue;
            }
            emit_names.push(name.clone());
        }
        IDENTS.with(|c| *c.borrow_mut() = unique_idents(&emit_names));
        for name in &emit_names {
            let desc = pool.get_message(name).expect("emit");
            emit_message(&mut src, &desc);
            emit_map_decoders(&mut src, &desc);
        }
        let services: Vec<_> = pool
            .collect_services()
            .into_iter()
            .filter(|s| file_matches(&wanted, &s.file_name))
            .collect();
        if !services.is_empty() {
            src.push_str("\n// --- gRPC stubs (protobuf-tonic, not tonic-prost) ---\n");
            src.push_str("use protobuf_tonic::ProtobufCodec;\n");
            src.push_str("use std::convert::Infallible;\n");
            src.push_str("use std::future::Future;\n");
            src.push_str("use std::pin::Pin;\n");
            src.push_str("use std::sync::Arc;\n");
            src.push_str("use std::task::{Context, Poll};\n");
            for svc in &services {
                emit_service(&mut src, svc);
            }
        }
        src.push_str("}\npub use __gen::*;\n");
        let stem = std::path::Path::new(target)
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("generated");
        out_files.push((format!("{stem}.rs"), src));
    }
    Ok(out_files)
}

/// Generate from a FileDescriptorSet plus the proto paths to emit.
pub fn generate_from_file_descriptor_set(
    fds: &[u8],
    files_to_generate: &[String],
) -> Result<Vec<(String, String)>, ParseError> {
    let mut req = Vec::new();
    for f in files_to_generate {
        encode_string_field(&mut req, 1, f);
    }
    let mut pos = 0;
    while pos < fds.len() {
        let (n, w) = decode_tag(fds, &mut pos)?;
        if n == 1 && w == WIRE_LEN {
            let blob = read_len_bytes(fds, &mut pos)?;
            encode_len_field(&mut req, 15, blob);
        } else {
            wire::skip_field(fds, &mut pos, w)?;
        }
    }
    generate_from_code_generator_request(&req)
}

pub fn encode_code_generator_response(files: &[(String, String)]) -> Vec<u8> {
    let mut out = Vec::new();
    // PROTO3_OPTIONAL | SUPPORTS_EDITIONS
    encode_varint_field(&mut out, 2, 3);
    encode_varint_field(&mut out, 3, 998); // EDITION_PROTO2
    encode_varint_field(&mut out, 4, 1000); // EDITION_2023
    for (name, content) in files {
        let mut file = Vec::new();
        encode_string_field(&mut file, 1, name);
        encode_string_field(&mut file, 15, content);
        encode_len_field(&mut out, 15, &file);
    }
    out
}

fn file_matches(wanted: &std::collections::BTreeSet<String>, file_name: &str) -> bool {
    if file_name.is_empty() {
        return true;
    }
    let file_stem = std::path::Path::new(file_name)
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or(file_name);
    wanted.iter().any(|w| {
        let w_stem = std::path::Path::new(w)
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or(w);
        w == file_name || w.ends_with(file_name) || file_name.ends_with(w) || w_stem == file_stem
    })
}

fn emit_fds(src: &mut String, fds: &[u8]) {
    src.push_str("const FILE_DESCRIPTOR_SET: &[u8] = &[\n");
    for (i, b) in fds.iter().enumerate() {
        if i % 16 == 0 {
            src.push_str("    ");
        }
        let _ = write!(src, "0x{b:02x},");
        if i % 16 == 15 {
            src.push('\n');
        }
    }
    if fds.len() % 16 != 0 {
        src.push('\n');
    }
    src.push_str("];\n\n");
}

fn encode_varint_field(out: &mut Vec<u8>, n: u32, v: u64) {
    crate::wire::encode_tag(out, n, crate::wire::WIRE_VARINT);
    encode_varint(out, v);
}

fn encode_string_field(out: &mut Vec<u8>, n: u32, s: &str) {
    encode_len_field(out, n, s.as_bytes());
}

fn ident_last(s: &str) -> String {
    let key = s.trim_start_matches('.');
    let last = key.rsplit('.').next().unwrap_or(key);
    rust_ident_from_last(last)
}

fn unique_idents(full_names: &[String]) -> std::collections::BTreeMap<String, String> {
    let mut used: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    let mut out = std::collections::BTreeMap::new();
    for full in full_names {
        let last = ident_last(full);
        let id = if used.contains(&last) {
            let parent = full.rsplit_once('.').map(|x| x.0).unwrap_or("X");
            format!("{}{last}", ident_last(parent))
        } else {
            last
        };
        used.insert(id.clone());
        out.insert(full.clone(), id);
    }
    out
}

fn rust_ident(s: &str) -> String {
    let key = s.trim_start_matches('.');
    if let Some(id) = IDENTS.with(|c| c.borrow().get(key).cloned()) {
        return id;
    }
    ident_last(key)
}

fn is_rust_keyword(id: &str) -> bool {
    matches!(
        id,
        "as" | "async"
            | "await"
            | "break"
            | "const"
            | "continue"
            | "crate"
            | "dyn"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "union"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "abstract"
            | "become"
            | "box"
            | "do"
            | "final"
            | "macro"
            | "override"
            | "priv"
            | "try"
            | "typeof"
            | "unsized"
            | "virtual"
            | "yield"
            | "gen"
            | "unknown"
    )
}

fn field_ident_base(name: &str) -> String {
    let mut id = String::new();
    for (i, c) in name.chars().enumerate() {
        if c.is_ascii_alphanumeric() || c == '_' {
            id.push(c);
        } else if i > 0 {
            id.push('_');
        }
    }
    if id.is_empty() {
        id.push('_');
    }
    if id.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        id = format!("f_{id}");
    }
    if is_rust_keyword(&id) {
        format!("r#{id}")
    } else {
        id
    }
}

fn bind_field_idents(desc: &MessageDescriptor) {
    let mut used = std::collections::BTreeSet::new();
    used.insert("unknown".into());
    let mut out = std::collections::BTreeMap::new();
    for f in desc.fields.values() {
        let mut id = field_ident_base(&f.name);
        if !used.insert(id.clone()) {
            id = format!("{}_{}", id.trim_start_matches("r#"), f.number);
            used.insert(id.clone());
        }
        out.insert(f.number, id);
    }
    FIELD_IDENTS.with(|c| *c.borrow_mut() = out);
}

fn field_id(f: &FieldDescriptor) -> String {
    FIELD_IDENTS.with(|c| {
        c.borrow()
            .get(&f.number)
            .cloned()
            .unwrap_or_else(|| field_ident_base(&f.name))
    })
}

fn rust_ident_from_last(last: &str) -> String {
    let mut id = String::new();
    for (i, c) in last.chars().enumerate() {
        if c.is_ascii_alphanumeric() || c == '_' {
            id.push(c);
        } else if i > 0 {
            id.push('_');
        }
    }
    if id.is_empty() {
        id.push('M');
    }
    if is_rust_keyword(&id) {
        return format!("r#{id}");
    }
    if matches!(
        id.as_str(),
        "Value" | "Option" | "Result" | "Vec" | "String" | "Box" | "Type"
    ) {
        return format!("Pb{id}");
    }
    id
}

fn scalar_type(field: &FieldDescriptor) -> String {
    match field.field_type {
        FieldType::Double => "f64".into(),
        FieldType::Float => "f32".into(),
        FieldType::Int64 | FieldType::Sint64 | FieldType::Sfixed64 => "i64".into(),
        FieldType::Int32 | FieldType::Sint32 | FieldType::Sfixed32 | FieldType::Enum => {
            "i32".into()
        }
        FieldType::Uint64 | FieldType::Fixed64 => "u64".into(),
        FieldType::Uint32 | FieldType::Fixed32 => "u32".into(),
        FieldType::Bool => "bool".into(),
        FieldType::String => "ProtoString".into(),
        FieldType::Bytes => "ProtoBytes".into(),
        FieldType::Message | FieldType::Group => rust_ident(
            field
                .type_name
                .as_deref()
                .or_else(|| field.message.as_ref().map(|m| m.full_name.as_str()))
                .unwrap_or("UnknownMsg"),
        ),
    }
}

fn map_kv(field: &FieldDescriptor) -> (String, String) {
    let entry = field.message.as_ref();
    let k = entry
        .and_then(|e| e.field(1))
        .map(scalar_type)
        .unwrap_or_else(|| "ProtoString".into());
    let v = entry
        .and_then(|e| e.field(2))
        .map(scalar_type)
        .unwrap_or_else(|| "i32".into());
    (k, v)
}

fn is_option(field: &FieldDescriptor) -> bool {
    !field.is_map
        && field.cardinality != Cardinality::Repeated
        && (field.field_type == FieldType::Message
            || field.field_type == FieldType::Group
            || field.presence == Presence::Explicit)
}

fn field_storage_ty(f: &FieldDescriptor) -> String {
    if f.is_map {
        let (k, v) = map_kv(f);
        return format!("Map<{k}, {v}>");
    }
    let t = scalar_type(f);
    if f.cardinality == Cardinality::Repeated {
        format!("Repeated<{t}>")
    } else if f.field_type == FieldType::Message || f.field_type == FieldType::Group {
        format!("Option<Box<{t}>>")
    } else if is_option(f) {
        format!("Option<{t}>")
    } else {
        t
    }
}

fn emit_message(src: &mut String, desc: &MessageDescriptor) {
    bind_field_idents(desc);
    let name = rust_ident(&desc.full_name);
    let view = format!("{name}View");
    let mut_ = format!("{name}Mut");
    let _ = writeln!(src, "#[derive(Clone, Debug, PartialEq)]");
    let _ = writeln!(src, "pub struct {name} {{");
    for f in desc.fields.values() {
        let _ = writeln!(src, "    {}: {},", field_id(f), field_storage_ty(f));
    }
    let _ = writeln!(src, "    unknown: UnknownFields,");
    let _ = writeln!(src, "    cached_size: protobuf::rt::CachedSize,");
    let _ = writeln!(src, "}}");
    let _ = writeln!(src, "impl Default for {name} {{");
    let _ = writeln!(src, "    fn default() -> Self {{");
    let _ = writeln!(src, "        Self {{");
    for f in desc.fields.values() {
        let id = field_id(f);
        if f.is_map {
            let _ = writeln!(src, "            {id}: Map::new(),");
        } else if f.cardinality == Cardinality::Repeated {
            let _ = writeln!(src, "            {id}: Repeated::new(),");
        } else if is_option(f) {
            let _ = writeln!(src, "            {id}: None,");
        } else {
            let _ = writeln!(src, "            {id}: Default::default(),");
        }
    }
    let _ = writeln!(src, "            unknown: UnknownFields::default(),");
    let _ = writeln!(
        src,
        "            cached_size: protobuf::rt::CachedSize::default(),"
    );
    let _ = writeln!(src, "        }}");
    let _ = writeln!(src, "    }}");
    let _ = writeln!(src, "}}");

    let _ = writeln!(src, "impl {name} {{");
    let _ = writeln!(src, "    pub fn new() -> Self {{ Self::default() }}");
    let _ = writeln!(
        src,
        "    pub const FULL_NAME: &'static str = \"{}\";",
        desc.full_name
    );
    for f in desc.fields.values() {
        emit_accessors(src, desc, f);
    }
    emit_codec(src, desc);
    emit_json_text(src, &desc.full_name);
    let _ = writeln!(src, "}}");
    let _ = writeln!(
        src,
        "protobuf::impl_typed_message!({name}, {view}, {mut_});"
    );
}

fn emit_oneof_clear(src: &mut String, desc: &MessageDescriptor, f: &FieldDescriptor) {
    let Some(idx) = f.oneof_index else {
        return;
    };
    let Some(members) = desc.oneofs.get(idx as usize) else {
        return;
    };
    for n in members {
        if *n == f.number {
            continue;
        }
        if let Some(sib) = desc.field(*n) {
            let sid = field_id(sib);
            if is_option(sib) {
                let _ = writeln!(src, "        self.{sid} = None;");
            } else if sib.cardinality == Cardinality::Repeated || sib.is_map {
                let _ = writeln!(src, "        self.{sid}.clear();");
            } else {
                let _ = writeln!(src, "        self.{sid} = Default::default();");
            }
        }
    }
}

fn emit_accessors(src: &mut String, desc: &MessageDescriptor, f: &FieldDescriptor) {
    let id = field_id(f);
    if f.is_map {
        let (k, v) = map_kv(f);
        let _ = writeln!(
            src,
            "    pub fn {id}(&self) -> MapView<'_, {k}, {v}> {{ self.{id}.as_view() }}"
        );
        let _ = writeln!(
            src,
            "    pub fn {id}_mut(&mut self) -> MapMut<'_, {k}, {v}> {{ self.cached_size.dirty(); self.{id}.as_mut() }}"
        );
        let _ = writeln!(
            src,
            "    pub fn set_{id}(&mut self, v: Map<{k}, {v}>) {{ self.cached_size.dirty(); self.{id} = v; }}"
        );
        return;
    }
    if f.cardinality == Cardinality::Repeated {
        let t = scalar_type(f);
        let _ = writeln!(
            src,
            "    pub fn {id}(&self) -> RepeatedView<'_, {t}> {{ self.{id}.as_view() }}"
        );
        let _ = writeln!(
            src,
            "    pub fn {id}_mut(&mut self) -> RepeatedMut<'_, {t}> {{ self.cached_size.dirty(); self.{id}.as_mut() }}"
        );
        let _ = writeln!(
            src,
            "    pub fn set_{id}(&mut self, v: Repeated<{t}>) {{ self.cached_size.dirty(); self.{id} = v; }}"
        );
        return;
    }
    if f.field_type == FieldType::Message || f.field_type == FieldType::Group {
        let t = scalar_type(f);
        let _ = writeln!(
            src,
            "    pub fn has_{id}(&self) -> bool {{ self.{id}.is_some() }}"
        );
        let _ = writeln!(
            src,
            "    pub fn {id}(&self) -> Option<&{t}> {{ self.{id}.as_deref() }}"
        );
        let _ = writeln!(
            src,
            "    pub fn {id}_view(&self) -> Option<{t}View<'_>> {{ self.{id}.as_deref().map({t}View) }}"
        );
        let _ = writeln!(src, "    pub fn set_{id}(&mut self, v: {t}) {{");
        let _ = writeln!(src, "        self.cached_size.dirty();");
        emit_oneof_clear(src, desc, f);
        let _ = writeln!(src, "        self.{id} = Some(Box::new(v));");
        let _ = writeln!(src, "    }}");
        let _ = writeln!(
            src,
            "    pub fn clear_{id}(&mut self) {{ self.cached_size.dirty(); self.{id} = None; }}"
        );
        return;
    }
    if f.field_type == FieldType::String {
        if is_option(f) {
            let _ = writeln!(
                src,
                "    pub fn has_{id}(&self) -> bool {{ self.{id}.is_some() }}"
            );
            let _ = writeln!(
                src,
                "    pub fn {id}(&self) -> &protobuf::ProtoStr {{ self.{id}.as_ref().map(|s| s.as_view()).unwrap_or_else(|| protobuf::ProtoStr::from_bytes(b\"\")) }}"
            );
            let _ = writeln!(
                src,
                "    pub fn set_{id}(&mut self, v: impl protobuf::IntoProxied<ProtoString>) {{"
            );
            let _ = writeln!(src, "        self.cached_size.dirty();");
            emit_oneof_clear(src, desc, f);
            let _ = writeln!(src, "        self.{id} = Some(v.into_proxied());");
            let _ = writeln!(src, "    }}");
            let _ = writeln!(
                src,
                "    pub fn clear_{id}(&mut self) {{ self.cached_size.dirty(); self.{id} = None; }}"
            );
        } else {
            let _ = writeln!(
                src,
                "    pub fn {id}(&self) -> &protobuf::ProtoStr {{ self.{id}.as_view() }}"
            );
            let _ = writeln!(
                src,
                "    pub fn set_{id}(&mut self, v: impl protobuf::IntoProxied<ProtoString>) {{ self.cached_size.dirty(); self.{id} = v.into_proxied(); }}"
            );
        }
        return;
    }
    if f.field_type == FieldType::Bytes {
        if is_option(f) {
            let _ = writeln!(
                src,
                "    pub fn {id}(&self) -> &[u8] {{ self.{id}.as_ref().map(|b| b.as_bytes()).unwrap_or(&[]) }}"
            );
            let _ = writeln!(
                src,
                "    pub fn set_{id}(&mut self, v: impl protobuf::IntoProxied<ProtoBytes>) {{ self.cached_size.dirty(); self.{id} = Some(v.into_proxied()); }}"
            );
        } else {
            let _ = writeln!(
                src,
                "    pub fn {id}(&self) -> &[u8] {{ self.{id}.as_bytes() }}"
            );
            let _ = writeln!(
                src,
                "    pub fn set_{id}(&mut self, v: impl protobuf::IntoProxied<ProtoBytes>) {{ self.cached_size.dirty(); self.{id} = v.into_proxied(); }}"
            );
        }
        return;
    }
    let t = scalar_type(f);
    if is_option(f) {
        let _ = writeln!(
            src,
            "    pub fn {id}(&self) -> {t} {{ self.{id}.unwrap_or_default() }}"
        );
        let _ = writeln!(src, "    pub fn set_{id}(&mut self, v: {t}) {{");
        let _ = writeln!(src, "        self.cached_size.dirty();");
        emit_oneof_clear(src, desc, f);
        let _ = writeln!(src, "        self.{id} = Some(v);");
        let _ = writeln!(src, "    }}");
    } else {
        let _ = writeln!(src, "    pub fn {id}(&self) -> {t} {{ self.{id} }}");
        let _ = writeln!(
            src,
            "    pub fn set_{id}(&mut self, v: {t}) {{ self.cached_size.dirty(); self.{id} = v; }}"
        );
    }
}

fn emit_json_text(src: &mut String, full_name: &str) {
    let _ = writeln!(
        src,
        "    pub fn to_json(&self) -> Result<String, SerializeError> {{"
    );
    let _ = writeln!(src, "        let b = protobuf::Serialize::serialize(self).map_err(|_| SerializeError::new(\"json\"))?;");
    let _ = writeln!(src, "        let pool = generated_pool();");
    let _ = writeln!(
        src,
        "        let desc = pool.get_message(\"{full_name}\").ok_or_else(|| SerializeError::new(\"missing desc\"))?;"
    );
    let _ = writeln!(src, "        protobuf::DynamicMessage::parse_with_pool(desc, Some(pool), &b).map_err(|_| SerializeError::new(\"json\"))?.to_json()");
    let _ = writeln!(src, "    }}");
    let _ = writeln!(
        src,
        "    pub fn from_json(json: &str) -> Result<Self, ParseError> {{ Self::from_json_ignore(json, false) }}"
    );
    let _ = writeln!(
        src,
        "    pub fn from_json_ignore(json: &str, ignore: bool) -> Result<Self, ParseError> {{"
    );
    let _ = writeln!(src, "        let pool = generated_pool();");
    let _ = writeln!(
        src,
        "        let desc = pool.get_message(\"{full_name}\").ok_or_else(|| ParseError::owned(\"missing desc\".into()))?;"
    );
    let _ = writeln!(src, "        let d = protobuf::DynamicMessage::from_json_with_pool(desc, Some(pool), json, ignore)?;");
    let _ = writeln!(src, "        let b = protobuf::Serialize::serialize(&d).map_err(|e| ParseError::owned(e.to_string()))?;");
    let _ = writeln!(src, "        <Self as protobuf::Parse>::parse(&b)");
    let _ = writeln!(src, "    }}");
    let _ = writeln!(
        src,
        "    pub fn to_text(&self) -> Result<String, SerializeError> {{"
    );
    let _ = writeln!(src, "        let b = protobuf::Serialize::serialize(self).map_err(|_| SerializeError::new(\"text\"))?;");
    let _ = writeln!(src, "        let pool = generated_pool();");
    let _ = writeln!(
        src,
        "        let desc = pool.get_message(\"{full_name}\").ok_or_else(|| SerializeError::new(\"missing desc\"))?;"
    );
    let _ = writeln!(src, "        protobuf::DynamicMessage::parse_with_pool(desc, Some(pool), &b).map_err(|_| SerializeError::new(\"text\"))?.to_text()");
    let _ = writeln!(src, "    }}");
    let _ = writeln!(
        src,
        "    pub fn to_text_with_unknown(&self) -> Result<String, SerializeError> {{"
    );
    let _ = writeln!(src, "        let b = protobuf::Serialize::serialize(self).map_err(|_| SerializeError::new(\"text\"))?;");
    let _ = writeln!(src, "        let pool = generated_pool();");
    let _ = writeln!(
        src,
        "        let desc = pool.get_message(\"{full_name}\").ok_or_else(|| SerializeError::new(\"missing desc\"))?;"
    );
    let _ = writeln!(src, "        protobuf::DynamicMessage::parse_with_pool(desc, Some(pool), &b).map_err(|_| SerializeError::new(\"text\"))?.to_text_with_unknown()");
    let _ = writeln!(src, "    }}");
    let _ = writeln!(
        src,
        "    pub fn from_text(text: &str) -> Result<Self, ParseError> {{"
    );
    let _ = writeln!(src, "        let pool = generated_pool();");
    let _ = writeln!(
        src,
        "        let desc = pool.get_message(\"{full_name}\").ok_or_else(|| ParseError::owned(\"missing desc\".into()))?;"
    );
    let _ = writeln!(
        src,
        "        let d = protobuf::DynamicMessage::from_text_with_pool(desc, Some(pool), text)?;"
    );
    let _ = writeln!(src, "        let b = protobuf::Serialize::serialize(&d).map_err(|e| ParseError::owned(e.to_string()))?;");
    let _ = writeln!(src, "        <Self as protobuf::Parse>::parse(&b)");
    let _ = writeln!(src, "    }}");
}

fn wire_const(ty: FieldType) -> &'static str {
    match ty {
        FieldType::Fixed64 | FieldType::Sfixed64 | FieldType::Double => "protobuf::rt::WIRE_I64",
        FieldType::Fixed32 | FieldType::Sfixed32 | FieldType::Float => "protobuf::rt::WIRE_I32",
        FieldType::String | FieldType::Bytes | FieldType::Message | FieldType::Group => {
            "protobuf::rt::WIRE_LEN"
        }
        _ => "protobuf::rt::WIRE_VARINT",
    }
}

fn implicit_present(id: &str, ty: FieldType) -> String {
    match ty {
        FieldType::Bool => format!("self.{id}"),
        FieldType::Float | FieldType::Double => format!("self.{id}.to_bits() != 0"),
        FieldType::String | FieldType::Bytes => format!("!self.{id}.is_empty()"),
        _ => format!("self.{id} != 0"),
    }
}

fn map_key_ty(field: &FieldDescriptor) -> FieldType {
    field
        .message
        .as_ref()
        .and_then(|e| e.field(1))
        .map(|f| f.field_type)
        .unwrap_or(FieldType::String)
}

fn map_val_ty(field: &FieldDescriptor) -> FieldType {
    field
        .message
        .as_ref()
        .and_then(|e| e.field(2))
        .map(|f| f.field_type)
        .unwrap_or(FieldType::Int32)
}

fn emit_codec(src: &mut String, desc: &MessageDescriptor) {
    let _ = writeln!(
        src,
        "    fn merge_bytes(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {{ let mut pos = 0; self.merge_inner(data, &mut pos, depth, true, None) }}"
    );
    let _ = writeln!(
        src,
        "    fn merge_bytes_dont_enforce(&mut self, data: &[u8], depth: u32) -> Result<(), ParseError> {{ let mut pos = 0; self.merge_inner(data, &mut pos, depth, false, None) }}"
    );
    let _ = writeln!(
        src,
        "    fn merge_group(&mut self, data: &[u8], pos: &mut usize, num: u32, depth: u32) -> Result<(), ParseError> {{ self.merge_inner(data, pos, depth, false, Some(num)) }}"
    );
    let _ = writeln!(
        src,
        "    fn merge_inner(&mut self, data: &[u8], pos: &mut usize, depth: u32, enforce: bool, until: Option<u32>) -> Result<(), ParseError> {{"
    );
    let _ = writeln!(
        src,
        "        if depth > protobuf::RECURSION_LIMIT {{ return Err(ParseError::new(\"recursion limit exceeded\")); }} let _ = enforce;"
    );
    let _ = writeln!(src, "        self.cached_size.dirty();");
    let _ = writeln!(src, "        while *pos < data.len() {{");
    let _ = writeln!(
        src,
        "            let (n, w) = protobuf::rt::decode_tag(data, pos)?;"
    );
    let _ = writeln!(src, "            if let Some(g) = until {{ if w == protobuf::rt::WIRE_EGROUP {{ if n != g {{ return Err(ParseError::new(\"mismatched end-group\")); }} return Ok(()); }} }}");
    let _ = writeln!(src, "            match (n, w) {{");
    for f in desc.fields.values() {
        emit_merge_arm(src, desc, f);
    }
    if desc.message_set_wire_format {
        emit_message_set_merge(src, desc);
    }
    let _ = writeln!(
        src,
        "                _ => self.unknown.fields.push(protobuf::rt::capture_unknown(data, pos, n, w)?),"
    );
    let _ = writeln!(src, "            }}");
    let _ = writeln!(src, "        }}");
    let _ = writeln!(
        src,
        "        if until.is_some() {{ return Err(ParseError::new(\"truncated group\")); }}"
    );
    let required: Vec<_> = desc
        .fields
        .values()
        .filter(|f| f.cardinality == Cardinality::Required)
        .collect();
    if !required.is_empty() {
        let _ = writeln!(src, "        if enforce {{");
        for f in required {
            let id = field_id(f);
            if is_option(f) {
                let _ = writeln!(
                    src,
                    "            if self.{id}.is_none() {{ return Err(ParseError::new(\"missing required field\")); }}"
                );
            }
        }
        let _ = writeln!(src, "        }}");
    }
    let _ = writeln!(src, "        Ok(())");
    let _ = writeln!(src, "    }}");

    let _ = writeln!(src, "    fn compute_size(&self) -> u64 {{");
    let _ = writeln!(
        src,
        "        if let Some(n) = self.cached_size.get() {{ return n; }}"
    );
    let _ = writeln!(src, "        let mut n = self.unknown.encoded_len();");
    if desc.message_set_wire_format {
        emit_message_set_size(src, desc);
    } else {
        for f in desc.fields.values() {
            emit_size(src, f);
        }
    }
    let _ = writeln!(src, "        self.cached_size.set(n);");
    let _ = writeln!(src, "        n");
    let _ = writeln!(src, "    }}");

    let _ = writeln!(src, "    fn write_to(&self, out: &mut Vec<u8>) {{");
    if desc.message_set_wire_format {
        emit_message_set_write(src, desc);
    } else {
        for f in desc.fields.values() {
            emit_write(src, f);
        }
    }
    let _ = writeln!(src, "        self.unknown.encode(out);");
    let _ = writeln!(src, "    }}");
}

fn emit_message_set_merge(src: &mut String, desc: &MessageDescriptor) {
    let _ = writeln!(
        src,
        "                (1, protobuf::rt::WIRE_SGROUP) | (1, protobuf::rt::WIRE_LEN) => {{"
    );
    let _ = writeln!(
        src,
        "                    let mut type_id = 0u32; let mut payload: Vec<u8> = Vec::new();"
    );
    let _ = writeln!(src, "                    if w == protobuf::rt::WIRE_LEN {{ let inner = protobuf::rt::read_len_bytes(data, pos)?; let mut p = 0; while p < inner.len() {{ let (n, ww) = protobuf::rt::decode_tag(inner, &mut p)?; match (n, ww) {{ (2, protobuf::rt::WIRE_VARINT) => type_id = protobuf::rt::decode_varint(inner, &mut p)? as u32, (3, protobuf::rt::WIRE_LEN) => payload = protobuf::rt::read_len_bytes(inner, &mut p)?.to_vec(), _ => protobuf::rt::skip_field(inner, &mut p, ww)?, }} }} }} else {{ loop {{ let (n, ww) = protobuf::rt::decode_tag(data, pos)?; if ww == protobuf::rt::WIRE_EGROUP && n == 1 {{ break; }} match (n, ww) {{ (2, protobuf::rt::WIRE_VARINT) => type_id = protobuf::rt::decode_varint(data, pos)? as u32, (3, protobuf::rt::WIRE_LEN) => payload = protobuf::rt::read_len_bytes(data, pos)?.to_vec(), _ => protobuf::rt::skip_field(data, pos, ww)?, }} }} }}");
    let _ = writeln!(src, "                    match type_id {{");
    for f in desc.fields.values() {
        let id = field_id(f);
        let t = scalar_type(f);
        let num = f.number;
        let _ = writeln!(src, "                        {num} => {{ match &mut self.{id} {{ Some(existing) => existing.merge_bytes(&payload, depth + 1)?, None => {{ let mut inner = {t}::default(); inner.merge_bytes(&payload, depth + 1)?; self.{id} = Some(Box::new(inner)); }} }} }}");
    }
    let _ = writeln!(src, "                        _ => {{ let mut u = protobuf::UnknownFields::default(); u.fields.push(protobuf::rt::UnknownField::Varint {{ number: 2, value: u64::from(type_id) }}); u.fields.push(protobuf::rt::UnknownField::LengthDelimited {{ number: 3, value: payload }}); self.unknown.fields.push(protobuf::rt::UnknownField::Group {{ number: 1, fields: u }}); }}");
    let _ = writeln!(src, "                    }}");
    let _ = writeln!(src, "                }}");
}

fn emit_message_set_size(src: &mut String, desc: &MessageDescriptor) {
    for f in desc.fields.values() {
        let id = field_id(f);
        let num = f.number;
        let _ = writeln!(src, "        if let Some(m) = &self.{id} {{ let inner = m.compute_size(); let item = protobuf::rt::tag_len(2, protobuf::rt::WIRE_VARINT) + protobuf::rt::varint_len({num} as u64) + protobuf::rt::key_len_value_len(3, inner); n += protobuf::rt::tag_len(1, protobuf::rt::WIRE_SGROUP) + item + protobuf::rt::tag_len(1, protobuf::rt::WIRE_EGROUP); }}");
    }
}

fn emit_message_set_write(src: &mut String, desc: &MessageDescriptor) {
    for f in desc.fields.values() {
        let id = field_id(f);
        let num = f.number;
        let _ = writeln!(src, "        if let Some(m) = &self.{id} {{ protobuf::rt::encode_tag(out, 1, protobuf::rt::WIRE_SGROUP); protobuf::rt::encode_tag(out, 2, protobuf::rt::WIRE_VARINT); protobuf::rt::encode_varint(out, {num} as u64); protobuf::rt::encode_len_header(out, 3, m.compute_size()); m.write_to(out); protobuf::rt::encode_tag(out, 1, protobuf::rt::WIRE_EGROUP); }}");
    }
}

fn read_scalar_expr(ty: FieldType, buf: &str, pos: &str) -> String {
    match ty {
        FieldType::Double => format!("f64::from_bits(protobuf::rt::read_fixed64({buf}, {pos})?)"),
        FieldType::Float => format!("f32::from_bits(protobuf::rt::read_fixed32({buf}, {pos})?)"),
        FieldType::Fixed64 => format!("protobuf::rt::read_fixed64({buf}, {pos})?"),
        FieldType::Sfixed64 => format!("protobuf::rt::read_fixed64({buf}, {pos})? as i64"),
        FieldType::Fixed32 => format!("protobuf::rt::read_fixed32({buf}, {pos})?"),
        FieldType::Sfixed32 => format!("protobuf::rt::read_fixed32({buf}, {pos})? as i32"),
        FieldType::Sint32 => {
            format!("protobuf::rt::decode_zigzag32(protobuf::rt::decode_varint({buf}, {pos})?)")
        }
        FieldType::Sint64 => {
            format!("protobuf::rt::decode_zigzag64(protobuf::rt::decode_varint({buf}, {pos})?)")
        }
        FieldType::Bool => format!("protobuf::rt::decode_varint({buf}, {pos})? != 0"),
        FieldType::Int64 => format!("protobuf::rt::decode_varint({buf}, {pos})? as i64"),
        FieldType::Uint64 => format!("protobuf::rt::decode_varint({buf}, {pos})?"),
        FieldType::Uint32 => format!("protobuf::rt::decode_varint({buf}, {pos})? as u32"),
        _ => format!("protobuf::rt::decode_varint({buf}, {pos})? as i32"),
    }
}

fn emit_merge_arm(src: &mut String, desc: &MessageDescriptor, f: &FieldDescriptor) {
    let id = field_id(f);
    let num = f.number;
    if f.is_map {
        let _ = writeln!(src, "                ({num}, protobuf::rt::WIRE_LEN) => {{");
        let _ = writeln!(
            src,
            "                    let p = protobuf::rt::read_len_bytes(data, pos)?;"
        );
        let _ = writeln!(
            src,
            "                    let (kk, vv) = decode_map_entry_{}_{num}(p, depth + 1)?;",
            id.replace("r#", "")
        );
        let _ = writeln!(src, "                    self.{id}.insert(kk, vv);");
        let _ = writeln!(src, "                }}");
        return;
    }
    if f.cardinality == Cardinality::Repeated {
        if f.field_type == FieldType::String {
            let utf = if f.utf8_validate {
                "std::str::from_utf8(b).map_err(|_| ParseError::new(\"invalid utf-8\"))?;"
            } else {
                ""
            };
            let _ = writeln!(src, "                ({num}, protobuf::rt::WIRE_LEN) => {{ let b = protobuf::rt::read_len_bytes(data, pos)?; {utf} self.{id}.push(ProtoString::from_bytes(b)); }}");
        } else if f.field_type == FieldType::Bytes {
            let _ = writeln!(src, "                ({num}, protobuf::rt::WIRE_LEN) => self.{id}.push(ProtoBytes::from(protobuf::rt::read_len_bytes(data, pos)?)),");
        } else if f.field_type == FieldType::Message || f.field_type == FieldType::Group {
            let t = scalar_type(f);
            if f.field_type == FieldType::Group || f.delimited {
                let _ = writeln!(src, "                ({num}, protobuf::rt::WIRE_SGROUP) => {{ let mut inner = {t}::default(); inner.merge_group(data, pos, {num}, depth + 1)?; self.{id}.push(inner); }}");
            } else {
                let _ = writeln!(src, "                ({num}, protobuf::rt::WIRE_LEN) => {{ let p = protobuf::rt::read_len_bytes(data, pos)?; let mut inner = {t}::default(); inner.merge_bytes(p, depth + 1)?; self.{id}.push(inner); }}");
            }
        } else if f.field_type.is_packable() {
            let expr = read_scalar_expr(f.field_type, "p", "&mut i");
            let unpacked = read_scalar_expr(f.field_type, "data", "pos");
            let packed_wire = wire_const(f.field_type);
            let _ = writeln!(src, "                ({num}, protobuf::rt::WIRE_LEN) => {{ let p = protobuf::rt::read_len_bytes(data, pos)?; let mut i = 0; while i < p.len() {{ self.{id}.push({expr}); }} }}");
            let _ = writeln!(
                src,
                "                ({num}, {packed_wire}) => self.{id}.push({unpacked}),"
            );
        } else {
            let unpacked = read_scalar_expr(f.field_type, "data", "pos");
            let w = wire_const(f.field_type);
            let _ = writeln!(
                src,
                "                ({num}, {w}) => self.{id}.push({unpacked}),"
            );
        }
        return;
    }
    if f.field_type == FieldType::Message || f.field_type == FieldType::Group {
        let t = scalar_type(f);
        if f.field_type == FieldType::Group || f.delimited {
            let _ = writeln!(
                src,
                "                ({num}, protobuf::rt::WIRE_SGROUP) => {{"
            );
            emit_oneof_clear(src, desc, f);
            let _ = writeln!(src, "                    match &mut self.{id} {{ Some(existing) => existing.merge_group(data, pos, {num}, depth + 1)?, None => {{ let mut inner = {t}::default(); inner.merge_group(data, pos, {num}, depth + 1)?; self.{id} = Some(Box::new(inner)); }} }}");
            let _ = writeln!(src, "                }}");
        } else {
            let _ = writeln!(src, "                ({num}, protobuf::rt::WIRE_LEN) => {{");
            emit_oneof_clear(src, desc, f);
            let _ = writeln!(
                src,
                "                    let p = protobuf::rt::read_len_bytes(data, pos)?;"
            );
            let _ = writeln!(src, "                    match &mut self.{id} {{ Some(existing) => existing.merge_bytes(p, depth + 1)?, None => {{ let mut inner = {t}::default(); inner.merge_bytes(p, depth + 1)?; self.{id} = Some(Box::new(inner)); }} }}");
            let _ = writeln!(src, "                }}");
        }
        return;
    }
    if f.field_type == FieldType::String {
        let utf = if f.utf8_validate {
            "std::str::from_utf8(b).map_err(|_| ParseError::new(\"invalid utf-8\"))?;"
        } else {
            ""
        };
        let assign = if is_option(f) {
            format!("self.{id} = Some(ProtoString::from_bytes(b))")
        } else {
            format!("self.{id} = ProtoString::from_bytes(b)")
        };
        let _ = writeln!(src, "                ({num}, protobuf::rt::WIRE_LEN) => {{");
        emit_oneof_clear(src, desc, f);
        let _ = writeln!(
            src,
            "                    let b = protobuf::rt::read_len_bytes(data, pos)?; {utf} {assign};"
        );
        let _ = writeln!(src, "                }}");
        return;
    }
    if f.field_type == FieldType::Bytes {
        let assign = if is_option(f) {
            format!("self.{id} = Some(ProtoBytes::from(protobuf::rt::read_len_bytes(data, pos)?))")
        } else {
            format!("self.{id} = ProtoBytes::from(protobuf::rt::read_len_bytes(data, pos)?)")
        };
        let _ = writeln!(src, "                ({num}, protobuf::rt::WIRE_LEN) => {{");
        emit_oneof_clear(src, desc, f);
        let _ = writeln!(src, "                    {assign};");
        let _ = writeln!(src, "                }}");
        return;
    }
    let expr = read_scalar_expr(f.field_type, "data", "pos");
    let w = wire_const(f.field_type);
    let assign = if is_option(f) {
        format!("self.{id} = Some({expr})")
    } else {
        format!("self.{id} = {expr}")
    };
    let _ = writeln!(src, "                ({num}, {w}) => {{");
    emit_oneof_clear(src, desc, f);
    let _ = writeln!(src, "                    {assign};");
    let _ = writeln!(src, "                }}");
}

fn packed_len_expr(v: &str, ty: FieldType) -> String {
    match ty {
        FieldType::Fixed64 | FieldType::Sfixed64 | FieldType::Double => "8".into(),
        FieldType::Fixed32 | FieldType::Sfixed32 | FieldType::Float => "4".into(),
        FieldType::Sint32 => {
            format!("protobuf::rt::varint_len(protobuf::rt::encode_zigzag32({v}))")
        }
        FieldType::Sint64 => {
            format!("protobuf::rt::varint_len(protobuf::rt::encode_zigzag64({v}))")
        }
        FieldType::Bool => format!("protobuf::rt::varint_len(u64::from({v}))"),
        _ => format!("protobuf::rt::varint_len(({v}) as u64)"),
    }
}

fn write_packed_stmt(out: &str, v: &str, ty: FieldType) -> String {
    match ty {
        FieldType::Double => format!("({out}).extend_from_slice(&({v}).to_bits().to_le_bytes())"),
        FieldType::Float => format!("({out}).extend_from_slice(&({v}).to_bits().to_le_bytes())"),
        FieldType::Fixed64 => format!("({out}).extend_from_slice(&({v}).to_le_bytes())"),
        FieldType::Sfixed64 => format!("({out}).extend_from_slice(&(({v}) as u64).to_le_bytes())"),
        FieldType::Fixed32 => format!("({out}).extend_from_slice(&({v}).to_le_bytes())"),
        FieldType::Sfixed32 => format!("({out}).extend_from_slice(&(({v}) as u32).to_le_bytes())"),
        FieldType::Sint32 => {
            format!("protobuf::rt::encode_varint({out}, protobuf::rt::encode_zigzag32({v}))")
        }
        FieldType::Sint64 => {
            format!("protobuf::rt::encode_varint({out}, protobuf::rt::encode_zigzag64({v}))")
        }
        FieldType::Bool => format!("protobuf::rt::encode_varint({out}, u64::from({v}))"),
        _ => format!("protobuf::rt::encode_varint({out}, {v} as u64)"),
    }
}

fn emit_size(src: &mut String, f: &FieldDescriptor) {
    let id = field_id(f);
    let num = f.number;
    if f.is_map {
        let _ = writeln!(src, "        for (k, v) in self.{id}.iter() {{");
        let key_sz = map_key_size(map_key_ty(f), "k");
        let val_sz = map_val_size(map_val_ty(f), "v");
        let _ = writeln!(src, "            let inner = {key_sz} + {val_sz};");
        let _ = writeln!(
            src,
            "            n += protobuf::rt::key_len_value_len({num}, inner);"
        );
        let _ = writeln!(src, "        }}");
        return;
    }
    if f.cardinality == Cardinality::Repeated {
        if f.field_type == FieldType::String || f.field_type == FieldType::Bytes {
            let _ = writeln!(src, "        for t in self.{id}.iter() {{ n += protobuf::rt::key_len_value_len({num}, t.as_bytes().len() as u64); }}");
        } else if f.field_type == FieldType::Group || f.delimited {
            let _ = writeln!(src, "        for t in self.{id}.iter() {{ n += protobuf::rt::tag_len({num}, protobuf::rt::WIRE_SGROUP) + t.compute_size() + protobuf::rt::tag_len({num}, protobuf::rt::WIRE_EGROUP); }}");
        } else if f.field_type == FieldType::Message {
            let _ = writeln!(src, "        for t in self.{id}.iter() {{ n += protobuf::rt::key_len_value_len({num}, t.compute_size()); }}");
        } else if f.packed && f.field_type.is_packable() {
            let plen = packed_len_expr("*t", f.field_type);
            let _ = writeln!(src, "        if !self.{id}.is_empty() {{ let mut payload = 0u64; for t in self.{id}.iter() {{ payload += {plen}; }} n += protobuf::rt::key_len_value_len({num}, payload); }}");
        } else {
            let plen = packed_len_expr("*t", f.field_type);
            let w = wire_const(f.field_type);
            let _ = writeln!(src, "        for t in self.{id}.iter() {{ n += protobuf::rt::tag_len({num}, {w}) + {plen}; }}");
        }
        return;
    }
    if f.field_type == FieldType::Group || f.delimited {
        let _ = writeln!(src, "        if let Some(m) = &self.{id} {{ n += protobuf::rt::tag_len({num}, protobuf::rt::WIRE_SGROUP) + m.compute_size() + protobuf::rt::tag_len({num}, protobuf::rt::WIRE_EGROUP); }}");
        return;
    }
    if f.field_type == FieldType::Message {
        let _ = writeln!(src, "        if let Some(m) = &self.{id} {{ n += protobuf::rt::key_len_value_len({num}, m.compute_size()); }}");
        return;
    }
    if f.field_type == FieldType::String || f.field_type == FieldType::Bytes {
        if is_option(f) {
            let _ = writeln!(src, "        if let Some(s) = &self.{id} {{ n += protobuf::rt::key_len_value_len({num}, s.as_bytes().len() as u64); }}");
        } else {
            let _ = writeln!(src, "        if !self.{id}.is_empty() {{ n += protobuf::rt::key_len_value_len({num}, self.{id}.as_bytes().len() as u64); }}");
        }
        return;
    }
    let sz = packed_len_expr("v", f.field_type);
    let w = wire_const(f.field_type);
    if is_option(f) {
        let _ = writeln!(
            src,
            "        if let Some(v) = self.{id} {{ n += protobuf::rt::tag_len({num}, {w}) + {sz}; }}"
        );
    } else {
        let pred = implicit_present(&id, f.field_type);
        let sz2 = packed_len_expr(&format!("self.{id}"), f.field_type);
        let _ = writeln!(
            src,
            "        if {pred} {{ n += protobuf::rt::tag_len({num}, {w}) + {sz2}; }}"
        );
    }
}

fn map_key_size(ty: FieldType, var: &str) -> String {
    match ty {
        FieldType::String => {
            format!("protobuf::rt::key_len_value_len(1, {var}.as_bytes().len() as u64)")
        }
        FieldType::Bool => format!(
            "protobuf::rt::tag_len(1, protobuf::rt::WIRE_VARINT) + protobuf::rt::varint_len(u64::from(*{var}))"
        ),
        FieldType::Fixed32 | FieldType::Sfixed32 => {
            "protobuf::rt::tag_len(1, protobuf::rt::WIRE_I32) + 4".into()
        }
        FieldType::Fixed64 | FieldType::Sfixed64 => {
            "protobuf::rt::tag_len(1, protobuf::rt::WIRE_I64) + 8".into()
        }
        FieldType::Sint32 => format!(
            "protobuf::rt::tag_len(1, protobuf::rt::WIRE_VARINT) + protobuf::rt::varint_len(protobuf::rt::encode_zigzag32(*{var}))"
        ),
        FieldType::Sint64 => format!(
            "protobuf::rt::tag_len(1, protobuf::rt::WIRE_VARINT) + protobuf::rt::varint_len(protobuf::rt::encode_zigzag64(*{var}))"
        ),
        FieldType::Uint32 => format!(
            "protobuf::rt::tag_len(1, protobuf::rt::WIRE_VARINT) + protobuf::rt::varint_len(u64::from(*{var}))"
        ),
        FieldType::Uint64 => format!(
            "protobuf::rt::tag_len(1, protobuf::rt::WIRE_VARINT) + protobuf::rt::varint_len(*{var})"
        ),
        _ => format!(
            "protobuf::rt::tag_len(1, protobuf::rt::WIRE_VARINT) + protobuf::rt::varint_len((*{var}) as u64)"
        ),
    }
}

fn map_val_size(ty: FieldType, var: &str) -> String {
    match ty {
        FieldType::String | FieldType::Bytes => {
            format!("protobuf::rt::key_len_value_len(2, {var}.as_bytes().len() as u64)")
        }
        FieldType::Message | FieldType::Group => {
            format!("protobuf::rt::key_len_value_len(2, {var}.compute_size())")
        }
        FieldType::Bool => {
            format!("protobuf::rt::tag_len(2, protobuf::rt::WIRE_VARINT) + protobuf::rt::varint_len(u64::from(*{var}))")
        }
        FieldType::Float => "protobuf::rt::tag_len(2, protobuf::rt::WIRE_I32) + 4".into(),
        FieldType::Double => "protobuf::rt::tag_len(2, protobuf::rt::WIRE_I64) + 8".into(),
        FieldType::Fixed32 | FieldType::Sfixed32 => {
            "protobuf::rt::tag_len(2, protobuf::rt::WIRE_I32) + 4".into()
        }
        FieldType::Fixed64 | FieldType::Sfixed64 => {
            "protobuf::rt::tag_len(2, protobuf::rt::WIRE_I64) + 8".into()
        }
        FieldType::Sint32 => format!(
            "protobuf::rt::tag_len(2, protobuf::rt::WIRE_VARINT) + protobuf::rt::varint_len(protobuf::rt::encode_zigzag32(*{var}))"
        ),
        FieldType::Sint64 => format!(
            "protobuf::rt::tag_len(2, protobuf::rt::WIRE_VARINT) + protobuf::rt::varint_len(protobuf::rt::encode_zigzag64(*{var}))"
        ),
        FieldType::Uint32 => format!(
            "protobuf::rt::tag_len(2, protobuf::rt::WIRE_VARINT) + protobuf::rt::varint_len(u64::from(*{var}))"
        ),
        FieldType::Uint64 => format!(
            "protobuf::rt::tag_len(2, protobuf::rt::WIRE_VARINT) + protobuf::rt::varint_len(*{var})"
        ),
        _ => format!(
            "protobuf::rt::tag_len(2, protobuf::rt::WIRE_VARINT) + protobuf::rt::varint_len((*{var}) as u64)"
        ),
    }
}

fn emit_write(src: &mut String, f: &FieldDescriptor) {
    let id = field_id(f);
    let num = f.number;
    if f.is_map {
        let kty = map_key_ty(f);
        let vty = map_val_ty(f);
        let _ = writeln!(src, "        for (k, v) in self.{id}.iter() {{");
        let _ = writeln!(
            src,
            "            let inner = {} + {};",
            map_key_size(kty, "k"),
            map_val_size(vty, "v")
        );
        let _ = writeln!(src, "            protobuf::rt::encode_tag(out, {num}, protobuf::rt::WIRE_LEN); protobuf::rt::encode_varint(out, inner);");
        emit_map_key_write(src, kty);
        emit_map_val_write(src, vty);
        let _ = writeln!(src, "        }}");
        return;
    }
    if f.cardinality == Cardinality::Repeated {
        if f.field_type == FieldType::String || f.field_type == FieldType::Bytes {
            let _ = writeln!(src, "        for t in self.{id}.iter() {{ protobuf::rt::encode_len_field(out, {num}, t.as_bytes()); }}");
        } else if f.field_type == FieldType::Group || f.delimited {
            let _ = writeln!(src, "        for t in self.{id}.iter() {{ protobuf::rt::encode_tag(out, {num}, protobuf::rt::WIRE_SGROUP); t.write_to(out); protobuf::rt::encode_tag(out, {num}, protobuf::rt::WIRE_EGROUP); }}");
        } else if f.field_type == FieldType::Message {
            let _ = writeln!(src, "        for t in self.{id}.iter() {{ protobuf::rt::encode_len_header(out, {num}, t.compute_size()); t.write_to(out); }}");
        } else if f.packed && f.field_type.is_packable() {
            let plen = packed_len_expr("*t", f.field_type);
            let stmt = write_packed_stmt("out", "*t", f.field_type);
            let _ = writeln!(src, "        if !self.{id}.is_empty() {{ let mut payload = 0u64; for t in self.{id}.iter() {{ payload += {plen}; }} protobuf::rt::encode_len_header(out, {num}, payload); for t in self.{id}.iter() {{ {stmt}; }} }}");
        } else {
            let w = wire_const(f.field_type);
            let stmt = write_packed_stmt("out", "*t", f.field_type);
            let _ = writeln!(src, "        for t in self.{id}.iter() {{ protobuf::rt::encode_tag(out, {num}, {w}); {stmt}; }}");
        }
        return;
    }
    if f.field_type == FieldType::Group || f.delimited {
        let _ = writeln!(src, "        if let Some(m) = &self.{id} {{ protobuf::rt::encode_tag(out, {num}, protobuf::rt::WIRE_SGROUP); m.write_to(out); protobuf::rt::encode_tag(out, {num}, protobuf::rt::WIRE_EGROUP); }}");
        return;
    }
    if f.field_type == FieldType::Message {
        let _ = writeln!(src, "        if let Some(m) = &self.{id} {{ protobuf::rt::encode_len_header(out, {num}, m.compute_size()); m.write_to(out); }}");
        return;
    }
    if f.field_type == FieldType::String || f.field_type == FieldType::Bytes {
        if is_option(f) {
            let _ = writeln!(src, "        if let Some(s) = &self.{id} {{ protobuf::rt::encode_len_field(out, {num}, s.as_bytes()); }}");
        } else {
            let _ = writeln!(src, "        if !self.{id}.is_empty() {{ protobuf::rt::encode_len_field(out, {num}, self.{id}.as_bytes()); }}");
        }
        return;
    }
    let w = wire_const(f.field_type);
    if is_option(f) {
        let stmt = write_packed_stmt("out", "v", f.field_type);
        let _ = writeln!(src, "        if let Some(v) = self.{id} {{ protobuf::rt::encode_tag(out, {num}, {w}); {stmt}; }}");
    } else {
        let pred = implicit_present(&id, f.field_type);
        let stmt = write_packed_stmt("out", &format!("self.{id}"), f.field_type);
        let _ = writeln!(
            src,
            "        if {pred} {{ protobuf::rt::encode_tag(out, {num}, {w}); {stmt}; }}"
        );
    }
}

fn emit_map_key_write(src: &mut String, ty: FieldType) {
    emit_map_scalar_write(src, 1, "k", ty);
}

fn emit_map_val_write(src: &mut String, ty: FieldType) {
    emit_map_scalar_write(src, 2, "v", ty);
}

fn emit_map_scalar_write(src: &mut String, n: u32, var: &str, ty: FieldType) {
    match ty {
        FieldType::String | FieldType::Bytes => {
            let _ = writeln!(
                src,
                "            protobuf::rt::encode_len_field(out, {n}, {var}.as_bytes());"
            );
        }
        FieldType::Message | FieldType::Group => {
            let _ = writeln!(src, "            protobuf::rt::encode_len_header(out, {n}, {var}.compute_size()); {var}.write_to(out);");
        }
        FieldType::Float => {
            let _ = writeln!(src, "            protobuf::rt::encode_tag(out, {n}, protobuf::rt::WIRE_I32); out.extend_from_slice(&{var}.to_bits().to_le_bytes());");
        }
        FieldType::Double => {
            let _ = writeln!(src, "            protobuf::rt::encode_tag(out, {n}, protobuf::rt::WIRE_I64); out.extend_from_slice(&{var}.to_bits().to_le_bytes());");
        }
        FieldType::Fixed32 => {
            let _ = writeln!(src, "            protobuf::rt::encode_tag(out, {n}, protobuf::rt::WIRE_I32); out.extend_from_slice(&{var}.to_le_bytes());");
        }
        FieldType::Sfixed32 => {
            let _ = writeln!(src, "            protobuf::rt::encode_tag(out, {n}, protobuf::rt::WIRE_I32); out.extend_from_slice(&(*{var} as u32).to_le_bytes());");
        }
        FieldType::Fixed64 => {
            let _ = writeln!(src, "            protobuf::rt::encode_tag(out, {n}, protobuf::rt::WIRE_I64); out.extend_from_slice(&{var}.to_le_bytes());");
        }
        FieldType::Sfixed64 => {
            let _ = writeln!(src, "            protobuf::rt::encode_tag(out, {n}, protobuf::rt::WIRE_I64); out.extend_from_slice(&(*{var} as u64).to_le_bytes());");
        }
        FieldType::Sint32 => {
            let _ = writeln!(src, "            protobuf::rt::encode_tag(out, {n}, protobuf::rt::WIRE_VARINT); protobuf::rt::encode_varint(out, protobuf::rt::encode_zigzag32(*{var}));");
        }
        FieldType::Sint64 => {
            let _ = writeln!(src, "            protobuf::rt::encode_tag(out, {n}, protobuf::rt::WIRE_VARINT); protobuf::rt::encode_varint(out, protobuf::rt::encode_zigzag64(*{var}));");
        }
        FieldType::Bool => {
            let _ = writeln!(src, "            protobuf::rt::encode_tag(out, {n}, protobuf::rt::WIRE_VARINT); protobuf::rt::encode_varint(out, u64::from(*{var}));");
        }
        FieldType::Uint64 => {
            let _ = writeln!(src, "            protobuf::rt::encode_tag(out, {n}, protobuf::rt::WIRE_VARINT); protobuf::rt::encode_varint(out, *{var});");
        }
        _ => {
            let _ = writeln!(src, "            protobuf::rt::encode_tag(out, {n}, protobuf::rt::WIRE_VARINT); protobuf::rt::encode_varint(out, *{var} as u64);");
        }
    }
}

fn emit_map_decoders(src: &mut String, desc: &MessageDescriptor) {
    bind_field_idents(desc);
    for f in desc.fields.values() {
        if !f.is_map {
            continue;
        }
        let id = field_id(f).replace("r#", "");
        let num = f.number;
        let (k, v) = map_kv(f);
        let kty = map_key_ty(f);
        let vty = map_val_ty(f);
        let _ = writeln!(
            src,
            "fn decode_map_entry_{id}_{num}(data: &[u8], depth: u32) -> Result<({k}, {v}), ParseError> {{"
        );
        let _ = writeln!(src, "    let _ = depth; let mut key = {k}::default(); let mut val = {v}::default(); let mut pos = 0;");
        let _ = writeln!(src, "    while pos < data.len() {{ let (n, w) = protobuf::rt::decode_tag(data, &mut pos)?; match (n, w) {{");
        emit_map_scalar_decode(src, 1, "key", kty, f.utf8_validate);
        emit_map_scalar_decode(src, 2, "val", vty, f.utf8_validate);
        let _ = writeln!(
            src,
            "        _ => protobuf::rt::skip_field(data, &mut pos, w)?,"
        );
        let _ = writeln!(src, "    }} }}");
        let _ = writeln!(src, "    Ok((key, val))");
        let _ = writeln!(src, "}}");
    }
}

fn emit_map_scalar_decode(src: &mut String, n: u32, var: &str, ty: FieldType, utf8: bool) {
    match ty {
        FieldType::String => {
            if utf8 {
                let _ = writeln!(src, "        ({n}, protobuf::rt::WIRE_LEN) => {{ let b = protobuf::rt::read_len_bytes(data, &mut pos)?; std::str::from_utf8(b).map_err(|_| ParseError::new(\"invalid utf-8\"))?; {var} = ProtoString::from_bytes(b); }},");
            } else {
                let _ = writeln!(src, "        ({n}, protobuf::rt::WIRE_LEN) => {var} = ProtoString::from_bytes(protobuf::rt::read_len_bytes(data, &mut pos)?),");
            }
        }
        FieldType::Bytes => {
            let _ = writeln!(src, "        ({n}, protobuf::rt::WIRE_LEN) => {var} = ProtoBytes::from(protobuf::rt::read_len_bytes(data, &mut pos)?),");
        }
        FieldType::Message | FieldType::Group => {
            let _ = writeln!(src, "        ({n}, protobuf::rt::WIRE_LEN) => {{ let p = protobuf::rt::read_len_bytes(data, &mut pos)?; {var}.merge_bytes(p, depth)?; }},");
        }
        FieldType::Float => {
            let _ = writeln!(src, "        ({n}, protobuf::rt::WIRE_I32) => {var} = f32::from_bits(protobuf::rt::read_fixed32(data, &mut pos)?),");
        }
        FieldType::Double => {
            let _ = writeln!(src, "        ({n}, protobuf::rt::WIRE_I64) => {var} = f64::from_bits(protobuf::rt::read_fixed64(data, &mut pos)?),");
        }
        FieldType::Fixed32 => {
            let _ = writeln!(src, "        ({n}, protobuf::rt::WIRE_I32) => {var} = protobuf::rt::read_fixed32(data, &mut pos)?,");
        }
        FieldType::Sfixed32 => {
            let _ = writeln!(src, "        ({n}, protobuf::rt::WIRE_I32) => {var} = protobuf::rt::read_fixed32(data, &mut pos)? as i32,");
        }
        FieldType::Fixed64 => {
            let _ = writeln!(src, "        ({n}, protobuf::rt::WIRE_I64) => {var} = protobuf::rt::read_fixed64(data, &mut pos)?,");
        }
        FieldType::Sfixed64 => {
            let _ = writeln!(src, "        ({n}, protobuf::rt::WIRE_I64) => {var} = protobuf::rt::read_fixed64(data, &mut pos)? as i64,");
        }
        FieldType::Sint32 => {
            let _ = writeln!(src, "        ({n}, protobuf::rt::WIRE_VARINT) => {var} = protobuf::rt::decode_zigzag32(protobuf::rt::decode_varint(data, &mut pos)?),");
        }
        FieldType::Sint64 => {
            let _ = writeln!(src, "        ({n}, protobuf::rt::WIRE_VARINT) => {var} = protobuf::rt::decode_zigzag64(protobuf::rt::decode_varint(data, &mut pos)?),");
        }
        FieldType::Bool => {
            let _ = writeln!(src, "        ({n}, protobuf::rt::WIRE_VARINT) => {var} = protobuf::rt::decode_varint(data, &mut pos)? != 0,");
        }
        FieldType::Uint64 => {
            let _ = writeln!(src, "        ({n}, protobuf::rt::WIRE_VARINT) => {var} = protobuf::rt::decode_varint(data, &mut pos)?,");
        }
        FieldType::Int64 => {
            let _ = writeln!(src, "        ({n}, protobuf::rt::WIRE_VARINT) => {var} = protobuf::rt::decode_varint(data, &mut pos)? as i64,");
        }
        FieldType::Uint32 => {
            let _ = writeln!(src, "        ({n}, protobuf::rt::WIRE_VARINT) => {var} = protobuf::rt::decode_varint(data, &mut pos)? as u32,");
        }
        _ => {
            let _ = writeln!(src, "        ({n}, protobuf::rt::WIRE_VARINT) => {var} = protobuf::rt::decode_varint(data, &mut pos)? as i32,");
        }
    }
}

fn to_snake(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.extend(c.to_lowercase());
        } else {
            out.push(c);
        }
    }
    if is_rust_keyword(&out) {
        format!("r#{out}")
    } else {
        out
    }
}

fn emit_service(src: &mut String, svc: &ServiceDescriptor) {
    let svc_ty = rust_ident(&svc.full_name);
    let client = format!("{svc_ty}Client");
    let server = format!("{svc_ty}Server");
    let path_prefix = format!("/{}", svc.full_name);
    let _ = writeln!(src, "pub trait {svc_ty}: Send + Sync + 'static {{");
    for m in &svc.methods {
        emit_service_trait_method(src, m);
    }
    let _ = writeln!(src, "}}");
    let _ = writeln!(src, "#[derive(Clone, Debug)]");
    let _ = writeln!(src, "pub struct {client} {{");
    let _ = writeln!(
        src,
        "    inner: tonic::client::Grpc<tonic::transport::Channel>,"
    );
    let _ = writeln!(src, "}}");
    let _ = writeln!(src, "impl {client} {{");
    let _ = writeln!(
        src,
        "    pub fn new(channel: tonic::transport::Channel) -> Self {{ Self {{ inner: tonic::client::Grpc::new(channel) }} }}"
    );
    for m in &svc.methods {
        emit_client_method(src, m, &path_prefix);
    }
    let _ = writeln!(src, "}}");
    let _ = writeln!(src, "pub struct {server}<T> {{ inner: Arc<T> }}");
    let _ = writeln!(src, "impl<T> Clone for {server}<T> {{");
    let _ = writeln!(
        src,
        "    fn clone(&self) -> Self {{ Self {{ inner: self.inner.clone() }} }}"
    );
    let _ = writeln!(src, "}}");
    let _ = writeln!(src, "impl<T: {svc_ty}> {server}<T> {{");
    let _ = writeln!(
        src,
        "    pub fn new(inner: T) -> Self {{ Self {{ inner: Arc::new(inner) }} }}"
    );
    let _ = writeln!(src, "}}");
    let _ = writeln!(
        src,
        "impl<T: {svc_ty}> tonic::server::NamedService for {server}<T> {{"
    );
    let _ = writeln!(src, "    const NAME: &'static str = \"{}\";", svc.full_name);
    let _ = writeln!(src, "}}");
    let _ = writeln!(
        src,
        "impl<T, B> tonic::codegen::Service<http::Request<B>> for {server}<T>"
    );
    let _ = writeln!(src, "where");
    let _ = writeln!(src, "    T: {svc_ty},");
    let _ = writeln!(src, "    B: tonic::codegen::Body + Send + 'static,");
    let _ = writeln!(
        src,
        "    B::Error: Into<tonic::codegen::StdError> + Send + 'static,"
    );
    let _ = writeln!(src, "{{");
    let _ = writeln!(
        src,
        "    type Response = http::Response<tonic::body::Body>;"
    );
    let _ = writeln!(src, "    type Error = Infallible;");
    let _ = writeln!(src, "    type Future = Pin<Box<dyn Future<Output = Result<Self::Response, Self::Error>> + Send>>;");
    let _ = writeln!(src, "    fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {{ Poll::Ready(Ok(())) }}");
    let _ = writeln!(
        src,
        "    fn call(&mut self, req: http::Request<B>) -> Self::Future {{"
    );
    let _ = writeln!(src, "        let inner = self.inner.clone();");
    let _ = writeln!(src, "        Box::pin(async move {{");
    let _ = writeln!(src, "            match req.uri().path() {{");
    for m in &svc.methods {
        emit_server_route(src, m, &path_prefix, &svc_ty);
    }
    let _ = writeln!(src, "                _ => {{");
    let _ = writeln!(
        src,
        "                    let mut response = http::Response::new(tonic::body::Body::default());"
    );
    let _ = writeln!(
        src,
        "                    let headers = response.headers_mut();"
    );
    let _ = writeln!(src, "                    headers.insert(tonic::Status::GRPC_STATUS, (tonic::Code::Unimplemented as i32).into());");
    let _ = writeln!(src, "                    headers.insert(http::header::CONTENT_TYPE, tonic::metadata::GRPC_CONTENT_TYPE);");
    let _ = writeln!(src, "                    Ok(response)");
    let _ = writeln!(src, "                }}");
    let _ = writeln!(src, "            }}");
    let _ = writeln!(src, "        }})");
    let _ = writeln!(src, "    }}");
    let _ = writeln!(src, "}}");
}

fn emit_service_trait_method(src: &mut String, m: &MethodDescriptor) {
    let fn_name = to_snake(&m.name);
    let req = rust_ident(&m.input_type);
    let resp = rust_ident(&m.output_type);
    let assoc = format!("{}Stream", m.name);
    match (m.client_streaming, m.server_streaming) {
        (false, false) => {
            let _ = writeln!(src, "    fn {fn_name}(&self, request: tonic::Request<{req}>) -> impl Future<Output = Result<tonic::Response<{resp}>, tonic::Status>> + Send;");
        }
        (true, true) => {
            let _ = writeln!(src, "    type {assoc}: tokio_stream::Stream<Item = Result<{resp}, tonic::Status>> + Send + 'static;");
            let _ = writeln!(src, "    fn {fn_name}(&self, request: tonic::Request<tonic::Streaming<{req}>>) -> impl Future<Output = Result<tonic::Response<Self::{assoc}>, tonic::Status>> + Send;");
        }
        (true, false) => {
            let _ = writeln!(src, "    fn {fn_name}(&self, request: tonic::Request<tonic::Streaming<{req}>>) -> impl Future<Output = Result<tonic::Response<{resp}>, tonic::Status>> + Send;");
        }
        (false, true) => {
            let _ = writeln!(src, "    type {assoc}: tokio_stream::Stream<Item = Result<{resp}, tonic::Status>> + Send + 'static;");
            let _ = writeln!(src, "    fn {fn_name}(&self, request: tonic::Request<{req}>) -> impl Future<Output = Result<tonic::Response<Self::{assoc}>, tonic::Status>> + Send;");
        }
    }
}

fn emit_client_method(src: &mut String, m: &MethodDescriptor, prefix: &str) {
    let fn_name = to_snake(&m.name);
    let req = rust_ident(&m.input_type);
    let resp = rust_ident(&m.output_type);
    let path = format!("{prefix}/{}", m.name);
    match (m.client_streaming, m.server_streaming) {
        (false, false) => {
            let _ = writeln!(src, "    pub async fn {fn_name}(&mut self, request: tonic::Request<{req}>) -> Result<tonic::Response<{resp}>, tonic::Status> {{");
            let _ = writeln!(src, "        self.inner.ready().await.map_err(|e| tonic::Status::unknown(e.to_string()))?;");
            let _ = writeln!(src, "        self.inner.unary(request, \"{path}\".parse().unwrap(), ProtobufCodec::<{req}, {resp}>::default()).await");
            let _ = writeln!(src, "    }}");
        }
        (true, true) => {
            let _ = writeln!(src, "    pub async fn {fn_name}<S>(&mut self, request: tonic::Request<S>) -> Result<tonic::Response<tonic::Streaming<{resp}>>, tonic::Status>");
            let _ = writeln!(
                src,
                "    where S: tokio_stream::Stream<Item = {req}> + Send + 'static {{"
            );
            let _ = writeln!(src, "        self.inner.ready().await.map_err(|e| tonic::Status::unknown(e.to_string()))?;");
            let _ = writeln!(src, "        self.inner.streaming(request, \"{path}\".parse().unwrap(), ProtobufCodec::<{req}, {resp}>::default()).await");
            let _ = writeln!(src, "    }}");
        }
        (true, false) => {
            let _ = writeln!(src, "    pub async fn {fn_name}<S>(&mut self, request: tonic::Request<S>) -> Result<tonic::Response<{resp}>, tonic::Status>");
            let _ = writeln!(
                src,
                "    where S: tokio_stream::Stream<Item = {req}> + Send + 'static {{"
            );
            let _ = writeln!(src, "        self.inner.ready().await.map_err(|e| tonic::Status::unknown(e.to_string()))?;");
            let _ = writeln!(src, "        self.inner.client_streaming(request, \"{path}\".parse().unwrap(), ProtobufCodec::<{req}, {resp}>::default()).await");
            let _ = writeln!(src, "    }}");
        }
        (false, true) => {
            let _ = writeln!(src, "    pub async fn {fn_name}(&mut self, request: tonic::Request<{req}>) -> Result<tonic::Response<tonic::Streaming<{resp}>>, tonic::Status> {{");
            let _ = writeln!(src, "        self.inner.ready().await.map_err(|e| tonic::Status::unknown(e.to_string()))?;");
            let _ = writeln!(src, "        self.inner.server_streaming(request, \"{path}\".parse().unwrap(), ProtobufCodec::<{req}, {resp}>::default()).await");
            let _ = writeln!(src, "    }}");
        }
    }
}

fn emit_server_route(src: &mut String, m: &MethodDescriptor, prefix: &str, svc_ty: &str) {
    let fn_name = to_snake(&m.name);
    let req = rust_ident(&m.input_type);
    let resp = rust_ident(&m.output_type);
    let path = format!("{prefix}/{}", m.name);
    match (m.client_streaming, m.server_streaming) {
        (false, false) => {
            let _ = writeln!(src, "                \"{path}\" => {{");
            let _ = writeln!(src, "                    struct Svc<T>(Arc<T>);");
            let _ = writeln!(src, "                    impl<T: {svc_ty}> tonic::server::UnaryService<{req}> for Svc<T> {{");
            let _ = writeln!(src, "                        type Response = {resp};");
            let _ = writeln!(src, "                        type Future = Pin<Box<dyn Future<Output = Result<tonic::Response<{resp}>, tonic::Status>> + Send>>;");
            let _ = writeln!(src, "                        fn call(&mut self, request: tonic::Request<{req}>) -> Self::Future {{");
            let _ = writeln!(
                src,
                "                            let inner = self.0.clone();"
            );
            let _ = writeln!(src, "                            Box::pin(async move {{ inner.{fn_name}(request).await }})");
            let _ = writeln!(src, "                        }}");
            let _ = writeln!(src, "                    }}");
            let _ = writeln!(src, "                    let mut grpc = tonic::server::Grpc::new(ProtobufCodec::<{resp}, {req}>::default());");
            let _ = writeln!(
                src,
                "                    Ok(grpc.unary(Svc(inner), req).await)"
            );
            let _ = writeln!(src, "                }}");
        }
        (true, true) => {
            let assoc = format!("{}Stream", m.name);
            let _ = writeln!(src, "                \"{path}\" => {{");
            let _ = writeln!(src, "                    struct Svc<T>(Arc<T>);");
            let _ = writeln!(src, "                    impl<T: {svc_ty}> tonic::server::StreamingService<{req}> for Svc<T> {{");
            let _ = writeln!(src, "                        type Response = {resp};");
            let _ = writeln!(
                src,
                "                        type ResponseStream = T::{assoc};"
            );
            let _ = writeln!(src, "                        type Future = Pin<Box<dyn Future<Output = Result<tonic::Response<Self::ResponseStream>, tonic::Status>> + Send>>;");
            let _ = writeln!(src, "                        fn call(&mut self, request: tonic::Request<tonic::Streaming<{req}>>) -> Self::Future {{");
            let _ = writeln!(
                src,
                "                            let inner = self.0.clone();"
            );
            let _ = writeln!(src, "                            Box::pin(async move {{ inner.{fn_name}(request).await }})");
            let _ = writeln!(src, "                        }}");
            let _ = writeln!(src, "                    }}");
            let _ = writeln!(src, "                    let mut grpc = tonic::server::Grpc::new(ProtobufCodec::<{resp}, {req}>::default());");
            let _ = writeln!(
                src,
                "                    Ok(grpc.streaming(Svc(inner), req).await)"
            );
            let _ = writeln!(src, "                }}");
        }
        (true, false) => {
            let _ = writeln!(src, "                \"{path}\" => {{");
            let _ = writeln!(src, "                    struct Svc<T>(Arc<T>);");
            let _ = writeln!(src, "                    impl<T: {svc_ty}> tonic::server::ClientStreamingService<{req}> for Svc<T> {{");
            let _ = writeln!(src, "                        type Response = {resp};");
            let _ = writeln!(src, "                        type Future = Pin<Box<dyn Future<Output = Result<tonic::Response<{resp}>, tonic::Status>> + Send>>;");
            let _ = writeln!(src, "                        fn call(&mut self, request: tonic::Request<tonic::Streaming<{req}>>) -> Self::Future {{");
            let _ = writeln!(
                src,
                "                            let inner = self.0.clone();"
            );
            let _ = writeln!(src, "                            Box::pin(async move {{ inner.{fn_name}(request).await }})");
            let _ = writeln!(src, "                        }}");
            let _ = writeln!(src, "                    }}");
            let _ = writeln!(src, "                    let mut grpc = tonic::server::Grpc::new(ProtobufCodec::<{resp}, {req}>::default());");
            let _ = writeln!(
                src,
                "                    Ok(grpc.client_streaming(Svc(inner), req).await)"
            );
            let _ = writeln!(src, "                }}");
        }
        (false, true) => {
            let assoc = format!("{}Stream", m.name);
            let _ = writeln!(src, "                \"{path}\" => {{");
            let _ = writeln!(src, "                    struct Svc<T>(Arc<T>);");
            let _ = writeln!(src, "                    impl<T: {svc_ty}> tonic::server::ServerStreamingService<{req}> for Svc<T> {{");
            let _ = writeln!(src, "                        type Response = {resp};");
            let _ = writeln!(
                src,
                "                        type ResponseStream = T::{assoc};"
            );
            let _ = writeln!(src, "                        type Future = Pin<Box<dyn Future<Output = Result<tonic::Response<Self::ResponseStream>, tonic::Status>> + Send>>;");
            let _ = writeln!(src, "                        fn call(&mut self, request: tonic::Request<{req}>) -> Self::Future {{");
            let _ = writeln!(
                src,
                "                            let inner = self.0.clone();"
            );
            let _ = writeln!(src, "                            Box::pin(async move {{ inner.{fn_name}(request).await }})");
            let _ = writeln!(src, "                        }}");
            let _ = writeln!(src, "                    }}");
            let _ = writeln!(src, "                    let mut grpc = tonic::server::Grpc::new(ProtobufCodec::<{resp}, {req}>::default());");
            let _ = writeln!(
                src,
                "                    Ok(grpc.server_streaming(Svc(inner), req).await)"
            );
            let _ = writeln!(src, "                }}");
        }
    }
}
