//! Pure-Rust stand-in for Google protobuf `__internal::runtime` (upb kernel ABI).
//! Official `protoc --rust_out` links against these names. No C/upb.

mod arena;
mod array;
mod decode;
mod encode;
mod extension;
mod layout;
mod map;
mod mini_table;
mod reflect;

pub use arena::Arena;
pub use arena::ArenaInner;
pub use array::InnerRepeatedMut;
pub use array::empty_array;
pub use extension::ExtensionRegistryPtr;
pub use extension::MiniTableExtensionPtr;
pub use layout::FieldKind;
pub use layout::MessageMutInner;
pub use layout::MessagePtr;
pub use layout::MessageViewInner;
pub use layout::MsgData;
pub use layout::OwnedMessageInner;
pub use layout::PtrAndLen;
pub use layout::RawArrayInner;
pub use layout::RawMap;
pub use layout::RawMapInner;
pub use layout::RawMessage;
pub use layout::RawRepeatedField;
pub use layout::StringView;
pub use map::InnerMapMut;
pub use map::empty_map;
pub use map::{KernelCollectionValue, KernelEnumCodec};
pub use mini_table::__unstable;
pub use mini_table::FieldType;
pub use mini_table::MiniField;
pub use mini_table::MiniTable;
pub use mini_table::MiniTableEnum;
pub use mini_table::MiniTableEnumInitPtr;
pub use mini_table::MiniTableEnumPtr;
pub use mini_table::MiniTableInitPtr;
pub use mini_table::MiniTablePtr;
pub use mini_table::build_enum_mini_table;
pub use mini_table::build_mini_table;
pub use mini_table::link_mini_table;
pub use reflect::AssociatedMiniTable;
pub use reflect::AssociatedMiniTableEnum;
pub use reflect::InnerProtoString;
pub use reflect::KernelMessage;
pub use reflect::KernelMessageMut;
pub use reflect::KernelMessageView;
pub use reflect::MessageMutInterop;
pub use reflect::MessageViewInterop;
pub use reflect::OwnedMessageInterop;
pub use reflect::UpbGetArena;
pub use reflect::UpbGetMessagePtr;
pub use reflect::UpbGetMessagePtrMut;
pub use reflect::debug_string;
pub use reflect::message_eq;
pub use reflect::message_set_bytes_field;
pub use reflect::message_set_map_field;
pub use reflect::message_set_repeated_field;
pub use reflect::message_set_string_field;
pub use reflect::message_set_sub_message;

pub(crate) use array::*;
pub(crate) use layout::*;
pub(crate) use map::*;
pub(crate) use reflect::*;
