//! ring_hash: consistent hashing over endpoints (A42/A76).
//!
//! Each address owns ring entries proportional to its weight (all 1
//! without xDS endpoint weights), hashed with XXH64 over
//! `<addr>_<index>` and sorted by hash, exactly like grpc-go's ring.
//! A pick hashes the request (the `request_hash_header` value, or a
//! random hash when the header is configured but absent) and walks
//! the ring from the first entry at or past the hash, returning the
//! first usable address. Without xDS and without `request_hash_header`
//! there is no request hash and picks fail (A76). Failed dials back
//! off per address like `round_robin`; the walk skips them, so one
//! down backend disturbs only its own hash range. Health gating
//! matches `round_robin` (A17).

use super::{HealthSignal, LbPolicyFactory, Pick, register_lb_policy_factory};
use crate::resolver::ResolvedAddress;
use crate::service_config::RingHashConfig;
use crate::status::Status;
use std::collections::{HashMap, HashSet};
use std::sync::{Arc, OnceLock};
use tokio::sync::{Mutex, watch};
use tokio::time::Instant;

/// XXH64 (seeded) for ring entries, request hashes, and rendezvous
/// subsetting. Matches `XXH64()` with the given seed; request and
/// entry hashes use seed 0 per A42, subsetting uses the policy seed
/// per A68. Verified against Go's cespare/xxhash in the unit vectors
/// below (generated by `tests/interop/go/xxhcheck`).
pub(crate) fn xxh64(bytes: &[u8], seed: u64) -> u64 {
    const PRIME1: u64 = 0x9E37_79B1_85EB_CA87;
    const PRIME2: u64 = 0xC2B2_AE3D_27D4_EB4F;
    const PRIME3: u64 = 0x1656_67B1_9E37_79F9;
    const PRIME4: u64 = 0x85EB_CA77_C2B2_AE63;
    const PRIME5: u64 = 0x27D4_EB2F_1656_67C5;

    fn round(mut acc: u64, input: u64) -> u64 {
        const PRIME1: u64 = 0x9E37_79B1_85EB_CA87;
        const PRIME2: u64 = 0xC2B2_AE3D_27D4_EB4F;
        acc = acc.wrapping_add(input.wrapping_mul(PRIME2));
        acc = acc.rotate_left(31);
        acc.wrapping_mul(PRIME1)
    }

    fn merge_round(mut acc: u64, mut val: u64) -> u64 {
        const PRIME1: u64 = 0x9E37_79B1_85EB_CA87;
        const PRIME4: u64 = 0x85EB_CA77_C2B2_AE63;
        val = round(0, val);
        acc ^= val;
        acc = acc.wrapping_mul(PRIME1).wrapping_add(PRIME4);
        acc
    }

    fn word8(chunk: &[u8]) -> u64 {
        chunk
            .first_chunk::<8>()
            .copied()
            .map(u64::from_le_bytes)
            .unwrap_or(0)
    }
    fn word4(chunk: &[u8]) -> u32 {
        chunk
            .first_chunk::<4>()
            .copied()
            .map(u32::from_le_bytes)
            .unwrap_or(0)
    }

    let len = bytes.len();
    let mut hash;
    let mut stripes = bytes.chunks_exact(32);
    if len >= 32 {
        let mut v1 = seed.wrapping_add(PRIME1).wrapping_add(PRIME2);
        let mut v2 = seed.wrapping_add(PRIME2);
        let mut v3 = seed;
        let mut v4 = seed.wrapping_sub(PRIME1);
        for stripe in &mut stripes {
            // A 32-byte stripe always yields four words.
            let mut words = stripe.chunks_exact(8).map(word8);
            v1 = round(v1, words.next().unwrap_or(0));
            v2 = round(v2, words.next().unwrap_or(0));
            v3 = round(v3, words.next().unwrap_or(0));
            v4 = round(v4, words.next().unwrap_or(0));
        }
        hash = v1.rotate_left(1).wrapping_add(v2.rotate_left(7));
        hash = hash
            .wrapping_add(v3.rotate_left(12))
            .wrapping_add(v4.rotate_left(18));
        hash = merge_round(merge_round(merge_round(merge_round(hash, v1), v2), v3), v4);
    } else {
        hash = seed.wrapping_add(PRIME5);
    }
    hash = hash.wrapping_add(len as u64);
    let mut tail = stripes.remainder().chunks_exact(8);
    for word in &mut tail {
        hash ^= round(0, word8(word));
        hash = hash
            .rotate_left(27)
            .wrapping_mul(PRIME1)
            .wrapping_add(PRIME4);
    }
    let mut tail = tail.remainder();
    if tail.len() >= 4 {
        hash ^= u64::from(word4(tail)).wrapping_mul(PRIME1);
        hash = hash
            .rotate_left(23)
            .wrapping_mul(PRIME2)
            .wrapping_add(PRIME3);
        tail = tail.get(4..).unwrap_or(&[]);
    }
    for byte in tail {
        hash ^= u64::from(*byte).wrapping_mul(PRIME5);
        hash = hash.rotate_left(11).wrapping_mul(PRIME1);
    }
    // Avalanche.
    hash ^= hash >> 33;
    hash = hash.wrapping_mul(PRIME2);
    hash ^= hash >> 29;
    hash = hash.wrapping_mul(PRIME3);
    hash ^= hash >> 32;
    hash
}

/// ring_hash policy state shared by a channel's picks.
#[derive(Debug)]
pub struct RingHash {
    config: RingHashConfig,
    state: Mutex<State>,
    changed: watch::Receiver<u64>,
    bump: watch::Sender<u64>,
}

#[derive(Debug)]
struct State {
    /// Resolver order; the ring is rebuilt from these on change.
    addresses: Vec<ResolvedAddress>,
    /// Sorted `(hash, address index)` entries; rebuilt on update.
    ring: Vec<(u64, usize)>,
    /// Per-address failure state; absent means ready.
    down: HashMap<ResolvedAddress, Down>,
    /// A17 health reports; absent means unknown (treated ready
    /// unless the address is still awaiting its first Watch).
    unhealthy: HashSet<ResolvedAddress>,
    /// Addresses with a Watch in flight but no report yet.
    health_pending: HashSet<ResolvedAddress>,
    last_error: Option<Status>,
}

#[derive(Clone, Debug)]
struct Down {
    until: Instant,
    rounds: u32,
}

impl RingHash {
    /// Build from a service-config document: the `ring_hash` entry's
    /// config when selected, else defaults. Config snapshots at
    /// channel build, like `pick_first`.
    #[must_use]
    pub fn from_config(config: Option<&crate::service_config::ServiceConfig>) -> Arc<Self> {
        let config = config
            .and_then(|doc| {
                doc.lb_policies().iter().find_map(|entry| match entry {
                    crate::service_config::LbPolicyConfig::RingHash(config) => Some(config.clone()),
                    _ => None,
                })
            })
            .unwrap_or_default();
        Self::with_config(config)
    }

    /// Build with an explicit config (tests and direct construction).
    #[must_use]
    pub fn with_config(config: RingHashConfig) -> Arc<Self> {
        let (bump, changed) = watch::channel(0);
        Arc::new(Self {
            config,
            state: Mutex::new(State {
                addresses: Vec::new(),
                ring: Vec::new(),
                down: HashMap::new(),
                unhealthy: HashSet::new(),
                health_pending: HashSet::new(),
                last_error: None,
            }),
            changed,
            bump,
        })
    }

    /// Effective config (snapshot at build).
    #[must_use]
    pub fn config(&self) -> &RingHashConfig {
        &self.config
    }

    /// Request hash for `md` under this policy's config, or `None`
    /// when no hash applies. With `request_hash_header` set: XXH64
    /// over the comma-joined values, or a random hash when the header
    /// is absent (A76). Without it there is no xDS hash source, so
    /// `None` (picks fail per A76).
    #[must_use]
    pub fn request_hash(&self, md: &crate::Metadata) -> Option<u64> {
        if self.config.request_hash_header.is_empty() {
            return None;
        }
        let values: Vec<&str> = md.get_all(&self.config.request_hash_header).collect();
        if values.is_empty() {
            return Some(super::SplitMix64::seed().next());
        }
        Some(xxh64(values.join(",").as_bytes(), 0))
    }

    /// Reconcile a new address list and rebuild the ring. Surviving
    /// addresses keep readiness (no flap on reorder); removed ones are
    /// forgotten. Wakes [`Self::watch`] on any change.
    pub async fn update(&self, addresses: Vec<ResolvedAddress>) {
        let mut state = self.state.lock().await;
        if addresses == state.addresses {
            return;
        }
        state.down.retain(|addr, _| addresses.contains(addr));
        state.unhealthy.retain(|addr| addresses.contains(addr));
        state.health_pending.retain(|addr| addresses.contains(addr));
        state.addresses = addresses;
        state.ring = build_ring(
            &state.addresses,
            self.config.min_ring_size,
            self.config.max_ring_size,
        );
        self.bump
            .send_modify(|generation| *generation = generation.wrapping_add(1));
    }

    /// Pick by hash: the first usable address at or past `hash` in
    /// ring order (wrapping), skipping down, unhealthy, and
    /// health-pending addresses. `None` (no hash source) fails the
    /// pick per A76. Expired backoffs rejoin lazily.
    pub async fn pick_hash(&self, hash: Option<u64>) -> Pick {
        let Some(hash) = hash else {
            return Pick::Fail(Status::unavailable(
                "ring_hash: no request hash (request_hash_header unset and no xDS hash)",
            ));
        };
        let mut state = self.state.lock().await;
        if state.addresses.is_empty() || state.ring.is_empty() {
            return Pick::Fail(Status::unavailable("ring_hash: no addresses"));
        }
        let now = Instant::now();
        state.down.retain(|_, down| down.until > now);
        let usable = |state: &State, addr: &ResolvedAddress| {
            !state.down.contains_key(addr)
                && !state.unhealthy.contains(addr)
                && !state.health_pending.contains(addr)
        };
        // Binary search the first entry at or past the hash, wrapping.
        let mut start = state
            .ring
            .partition_point(|(entry_hash, _)| *entry_hash < hash);
        if start >= state.ring.len() {
            start = 0;
        }
        let mut seen = HashSet::new();
        for offset in 0..state.ring.len() {
            let index = (start + offset) % state.ring.len();
            let Some((_, addr_index)) = state.ring.get(index) else {
                continue;
            };
            let Some(addr) = state.addresses.get(*addr_index).cloned() else {
                continue;
            };
            if !seen.insert(addr.clone()) {
                continue;
            }
            if usable(&state, &addr) {
                return Pick::Use(addr);
            }
        }
        // Nothing usable: pending Watch calls mean CONNECTING (wait),
        // otherwise fail with the last dial error.
        if state.addresses.iter().any(|addr| {
            !state.down.contains_key(addr)
                && !state.unhealthy.contains(addr)
                && state.health_pending.contains(addr)
        }) {
            return Pick::Wait;
        }
        match state.last_error.clone() {
            Some(status) => Pick::Fail(status),
            None => Pick::Wait,
        }
    }

    /// Record a successful dial: the address is ready and its failure
    /// state clears.
    pub async fn note_success(&self, addr: &ResolvedAddress) {
        let mut state = self.state.lock().await;
        state.down.remove(addr);
    }

    /// Record a Watch starting for a freshly dialed address: it stays
    /// out of picks until the first report (A17 CONNECTING).
    /// Returns whether this call newly marked the address.
    pub async fn note_health_pending(&self, addr: &ResolvedAddress) -> bool {
        let mut state = self.state.lock().await;
        if state.addresses.contains(addr) {
            state.health_pending.insert(addr.clone())
        } else {
            false
        }
    }

    /// Clear a Watch record without reporting: the Watch ended (drain,
    /// discard, shutdown) before any terminal signal.
    pub async fn note_health_gone(&self, addr: &ResolvedAddress) {
        let mut state = self.state.lock().await;
        if state.health_pending.remove(addr) {
            self.bump
                .send_modify(|generation| *generation = generation.wrapping_add(1));
        }
    }

    /// Record a Watch report: unhealthy addresses leave picks
    /// immediately; healthy ones (re)join. Unknown addresses are ignored.
    pub async fn note_health(&self, addr: &ResolvedAddress, signal: HealthSignal) {
        let mut state = self.state.lock().await;
        if !state.addresses.contains(addr) {
            return;
        }
        state.health_pending.remove(addr);
        match signal {
            HealthSignal::Healthy => state.unhealthy.remove(addr),
            HealthSignal::Unhealthy => state.unhealthy.insert(addr.clone()),
        };
        self.bump
            .send_modify(|generation| *generation = generation.wrapping_add(1));
    }

    /// Last reported health: `None` while no Watch has reported.
    /// Unknown addresses report `None`.
    pub async fn health_of(&self, addr: &ResolvedAddress) -> Option<HealthSignal> {
        let state = self.state.lock().await;
        if !state.addresses.contains(addr) || state.health_pending.contains(addr) {
            return None;
        }
        Some(if state.unhealthy.contains(addr) {
            HealthSignal::Unhealthy
        } else {
            HealthSignal::Healthy
        })
    }

    /// Record a failed dial: the address backs off exponentially
    /// (same 1s × 1.6, 120s cap as pick_first) and rejoins when the
    /// backoff lapses. Wakes waiters.
    pub async fn note_failure(&self, addr: &ResolvedAddress, status: Status) {
        let mut state = self.state.lock().await;
        let rounds = state.down.get(addr).map_or(0, |down| down.rounds);
        let delay = super::pick_first::transient_backoff(rounds);
        state.down.insert(
            addr.clone(),
            Down {
                until: Instant::now() + delay,
                rounds: rounds.saturating_add(1),
            },
        );
        state.last_error = Some(status);
        self.bump
            .send_modify(|generation| *generation = generation.wrapping_add(1));
    }

    /// Movement notifications: list updates and failures. Backoff
    /// expiry bumps nothing; waiters re-poll as well as watch.
    #[must_use]
    pub fn watch(&self) -> watch::Receiver<u64> {
        self.changed.clone()
    }
}

/// Endpoint hash-key string: the address text (A76 explicit keys
/// arrive with the resolver attribute interface in the xDS lane).
fn hash_key(addr: &ResolvedAddress) -> String {
    match addr {
        ResolvedAddress::Tcp(sock) => sock.to_string(),
        ResolvedAddress::Unix(path) => path.display().to_string(),
        ResolvedAddress::UnixAbstract(name) => {
            format!("@{}", String::from_utf8_lossy(name))
        }
    }
}

/// Build the sorted ring like grpc-go's `newRing`: weights normalize
/// (all 1 without xDS endpoint weights), the ring scales so the
/// least-weighted endpoint owns whole entries within
/// `min_ring_size`..=`max_ring_size`, entries hash
/// `XXH64("<key>_<per-endpoint index>")`, sorted by hash. Endpoints
/// iterate in hash-key order so the ring is stable across updates
/// that only reorder the resolver list.
fn build_ring(addresses: &[ResolvedAddress], min_size: u64, max_size: u64) -> Vec<(u64, usize)> {
    if addresses.is_empty() {
        return Vec::new();
    }
    let keys: Vec<String> = addresses.iter().map(hash_key).collect();
    let mut ordered: Vec<usize> = (0..addresses.len()).collect();
    ordered.sort_by(|a, b| {
        let ka = keys.get(*a).map(String::as_str).unwrap_or("");
        let kb = keys.get(*b).map(String::as_str).unwrap_or("");
        ka.cmp(kb)
    });
    // All weights are 1: normalized weight 1/n, min 1/n.
    let n = addresses.len() as f64;
    let min_weight = 1.0 / n;
    let scale = ((min_weight * min_size as f64).ceil() / min_weight).min(max_size as f64);
    // The ring never exceeds max_ring_size entries (scale clamps there).
    let capacity = usize::try_from(max_size).unwrap_or(usize::MAX);
    let mut ring = Vec::with_capacity(capacity.min(8_000_000));
    let mut current = 0.0;
    let mut target = 0.0;
    for index in ordered {
        target += scale / n;
        let mut entry = 0u32;
        while current < target {
            let key = keys.get(index).map(String::as_str).unwrap_or("");
            ring.push((xxh64(format!("{key}_{entry}").as_bytes(), 0), index));
            entry += 1;
            current += 1.0;
        }
    }
    ring.sort_by(|a, b| a.0.cmp(&b.0));
    ring
}

/// Factory registering `ring_hash` for A24 selection.
#[derive(Debug, Default)]
pub struct RingHashFactory;

impl LbPolicyFactory for RingHashFactory {
    fn name(&self) -> &str {
        "ring_hash"
    }
}

/// Register `ring_hash`, once. Called on the resolver-channel path
/// so selected configs need no user setup.
pub(crate) fn ensure_registered() {
    static ONCE: OnceLock<()> = OnceLock::new();
    ONCE.get_or_init(|| {
        register_lb_policy_factory(Arc::new(RingHashFactory));
    });
}

#[cfg(test)]
mod tests {
    use super::{RingHash, build_ring, xxh64};
    use crate::resolver::ResolvedAddress;
    use crate::service_config::RingHashConfig;

    fn tcp(n: u8) -> ResolvedAddress {
        ResolvedAddress::Tcp(format!("10.0.0.{n}:80").parse().expect("addr"))
    }

    #[test]
    fn xxh64_matches_go_vectors() {
        // From tests/interop/go/xxhcheck (cespare/xxhash/v2).
        let cases: &[(&str, u64, u64)] = &[
            ("", 0, 17_241_709_254_077_376_921),
            ("a", 0, 15_154_266_338_359_012_955),
            ("abc", 0, 4_952_883_123_889_572_249),
            ("10.0.0.1:80_0", 0, 8_431_885_850_995_268_104),
            ("10.0.0.1:80_1", 0, 1_744_051_470_726_137_489),
            ("session-42", 0, 2_560_834_703_844_116_766),
            ("x-request-id", 0, 6_538_405_562_691_238_499),
        ];
        for (input, seed, want) in cases {
            assert_eq!(xxh64(input.as_bytes(), *seed), *want, "input {input:?}");
        }
        assert_eq!(
            xxh64(b"10.0.0.1:80", 0x1234_5678_9abc_def0),
            16_073_021_882_805_041_330
        );
        assert_eq!(
            xxh64(b"10.0.0.2:80", 0x1234_5678_9abc_def0),
            13_528_995_647_657_640_478
        );
    }

    #[test]
    fn ring_scales_and_sorts() {
        // 3 equal endpoints, min 1024: ceil(1024/3) = 342 entries each,
        // ring holds 1026 (same as grpc-go's newRing).
        let ring = build_ring(&[tcp(1), tcp(2), tcp(3)], 1024, 4096);
        assert_eq!(ring.len(), 1026);
        assert!(ring.windows(2).all(|w| w[0].0 <= w[1].0));
        // Reordered input builds the same multiset of hashes.
        let mut a: Vec<u64> = ring.iter().map(|(h, _)| *h).collect();
        let ring2 = build_ring(&[tcp(3), tcp(1), tcp(2)], 1024, 4096);
        let mut b: Vec<u64> = ring2.iter().map(|(h, _)| *h).collect();
        a.sort_unstable();
        b.sort_unstable();
        assert_eq!(a, b);
    }

    #[test]
    fn ring_clamps_to_max() {
        let ring = build_ring(&[tcp(1), tcp(2)], 100, 64);
        assert!(ring.len() <= 64, "len {}", ring.len());
    }

    #[tokio::test]
    async fn same_hash_sticks_same_backend() {
        let rh = RingHash::with_config(RingHashConfig::default());
        rh.update(vec![tcp(1), tcp(2), tcp(3)]).await;
        let super::Pick::Use(first) = rh.pick_hash(Some(12345)).await else {
            panic!("expected a pick");
        };
        for _ in 0..10 {
            assert!(matches!(rh.pick_hash(Some(12345)).await, super::Pick::Use(a) if a == first));
        }
    }

    #[tokio::test]
    async fn hashes_spread_across_backends() {
        let rh = RingHash::with_config(RingHashConfig::default());
        rh.update(vec![tcp(1), tcp(2), tcp(3)]).await;
        let mut hits = [0u32; 3];
        for hash in 0..3000u64 {
            match rh
                .pick_hash(Some(hash.wrapping_mul(0x9E37_79B9_7F4A_7C15)))
                .await
            {
                super::Pick::Use(a) if a == tcp(1) => hits[0] += 1,
                super::Pick::Use(a) if a == tcp(2) => hits[1] += 1,
                super::Pick::Use(a) if a == tcp(3) => hits[2] += 1,
                other => panic!("unexpected pick: {other:?}"),
            }
        }
        // Roughly even thirds; XXH64 over sequential-ish inputs.
        for (i, h) in hits.iter().enumerate() {
            assert!((700..=1300).contains(h), "backend {i}: {h}");
        }
    }

    #[tokio::test]
    async fn down_backend_fails_over_within_ring_order() {
        let rh = RingHash::with_config(RingHashConfig::default());
        rh.update(vec![tcp(1), tcp(2), tcp(3)]).await;
        // Find a hash stuck to endpoint 1, then fail it: the same hash
        // must move to a surviving backend, not fail.
        let mut hash = None;
        for candidate in 0..500u64 {
            let spread = candidate.wrapping_mul(0x9E37_79B9_7F4A_7C15);
            if matches!(rh.pick_hash(Some(spread)).await, super::Pick::Use(a) if a == tcp(1)) {
                hash = Some(spread);
                break;
            }
        }
        let hash = hash.expect("some hash sticks to tcp(1)");
        rh.note_failure(&tcp(1), crate::status::Status::unavailable("down"))
            .await;
        match rh.pick_hash(Some(hash)).await {
            super::Pick::Use(a) => assert_ne!(a, tcp(1)),
            other => panic!("expected failover, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn missing_hash_fails_fast() {
        let rh = RingHash::with_config(RingHashConfig::default());
        rh.update(vec![tcp(1)]).await;
        assert!(matches!(rh.pick_hash(None).await, super::Pick::Fail(_)));
    }
}
